-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM inv_sled_agent] WHERE constraint_name = 'measurement_manifest_consistency' AND validated = true)),'true','Schema change verification failed: constraint measurement_manifest_consistency not found on table inv_sled_agent') AS BOOL);
