-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM bp_omicron_zone] WHERE constraint_name = 'expunged_disposition_properties' AND validated = true)),'true','Schema change verification failed: constraint expunged_disposition_properties not found on table bp_omicron_zone') AS BOOL);
