-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'host_ereport' AND index_name = 'order_host_ereports_by_timestamp')),'true','Schema change verification failed: index order_host_ereports_by_timestamp on table host_ereport does not exist') AS BOOL);
