-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'metric_producer' AND index_name = 'lookup_producer_by_oximeter')),'true','Schema change verification failed: index lookup_producer_by_oximeter on table metric_producer does not exist') AS BOOL);
