-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'fm_alert_request' AND index_name = 'lookup_fm_alert_requests_for_case')),'true','Schema change verification failed: index lookup_fm_alert_requests_for_case on table fm_alert_request does not exist') AS BOOL);
