// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use super::*;
use anyhow::Context;
use gateway_messages::SpPort;
use omicron_common::OMICRON_DPD_TAG;
use omicron_test_utils::dev;
use proptest::prelude::any;
use proptest::prelude::proptest as proptest_macro;
use proptest::strategy::Strategy;
use test_strategy::Arbitrary;
use test_strategy::proptest;
use tokio::task::block_in_place;

#[proptest]
fn proptest_plan_all_unchanged(service_nat_entries: ServiceZoneNatEntries) {
    let logctx =
        omicron_test_utils::dev::test_setup_log("proptest_plan_all_unchanged");
    let log = &logctx.log;

    let dpd_current_entries =
        service_nat_entries.iter().map(NatEntry::from).collect();
    let plan = ReconciliationPlan::new(
        &dpd_current_entries,
        &service_nat_entries,
        log,
    )
    .expect("planning should succeed");

    let expected = ReconciliationPlan {
        unchanged: service_nat_entries.iter().map(|e| e.zone_id).collect(),
        to_remove: BTreeSet::new(),
        to_create: BTreeMap::new(),
    };

    assert_eq!(plan, expected);

    logctx.cleanup_successful();
}

#[proptest]
fn proptest_plan_create_all(service_nat_entries: ServiceZoneNatEntries) {
    let logctx =
        omicron_test_utils::dev::test_setup_log("proptest_plan_create_all");
    let log = &logctx.log;

    let dpd_current_entries = BTreeSet::new();
    let plan = ReconciliationPlan::new(
        &dpd_current_entries,
        &service_nat_entries,
        log,
    )
    .expect("planning should succeed");

    let expected = ReconciliationPlan {
        unchanged: BTreeSet::new(),
        to_remove: BTreeSet::new(),
        to_create: service_nat_entries
            .iter()
            .map(|e| (e.zone_id, NatEntry::from(e)))
            .collect(),
    };

    assert_eq!(plan, expected);

    logctx.cleanup_successful();
}

#[derive(Debug, Clone, Arbitrary)]
struct TestInput {
    // Complete set of desired `ServiceZoneNatEntries` we want to exist after
    // reconciliation. This is divided into two: the first
    // 0..preexisting_service_nat_entries entries should already exist in dpd,
    // and the remaining should not (until we perform reconciliation).
    desired_service_nat_entries: ServiceZoneNatEntries,
    #[strategy(0..=#desired_service_nat_entries.len())]
    preexisting_service_nat_entries: usize,

    // Stale service entries. We should remove all of these.
    #[strategy(proptest::collection::btree_set(
        any::<ServiceZoneNatEntry>(),
        0..32,
    ).prop_filter(
        "no overlap with desired_service_nat_entries",
        move |entries| {
            filter_out_overlapping_arbitrary_service_entries(
                &#desired_service_nat_entries,
                entries,
            )
        }
    ))]
    stale_service_entries: BTreeSet<ServiceZoneNatEntry>,

    // Non-service entries. We should never touch these.
    #[strategy(proptest::collection::btree_set(
        any::<NatEntry>().prop_filter(
            "non-service VNI",
            |entry| entry.vni != Vni::SERVICES_VNI
        ),
        0..32,
    ).prop_filter(
        "no duplicate IPs",
        move |entries| filter_out_overlapping_arbitrary_non_service_entries(
            &#desired_service_nat_entries,
            &#stale_service_entries,
            entries,
        ),
    ))]
    preexisting_non_service_entries: BTreeSet<NatEntry>,
}

// Helper to collapse ipv4-mapped-ipv6 (generated by proptests sometimes)
// down to just ipv4.
fn collapse_ipv4_mapped(ip: IpAddr) -> IpAddr {
    match ip {
        ip @ IpAddr::V4(_) => ip,
        ip @ IpAddr::V6(ip6) => match ip6.to_ipv4_mapped() {
            Some(ip4) => IpAddr::V4(ip4),
            None => ip,
        },
    }
}

// Proptest filter to ensure we don't get conflicts from dpd on external IPs:
// return false if `entries` contains duplicate IPs or any IP also used by
// `desired_service_nat_entries`.
fn filter_out_overlapping_arbitrary_service_entries(
    desired_service_nat_entries: &ServiceZoneNatEntries,
    entries: &BTreeSet<ServiceZoneNatEntry>,
) -> bool {
    let mut entry_ips = BTreeSet::new();
    for entry in entries {
        if desired_service_nat_entries.contains_key(&entry.zone_id) {
            return false;
        }
        if !entry_ips.insert(collapse_ipv4_mapped(entry.kind.external_ip())) {
            return false;
        }
    }

    desired_service_nat_entries.iter().all(|other| {
        !entry_ips.contains(&collapse_ipv4_mapped(other.kind.external_ip()))
    })
}

// Proptest filter to ensure we don't get conflicts from dpd on external IPs:
// return false if `entries` contains duplicate IPs or any IP also used by
// `desired_service_nat_entries` or `stale_service_entries`.
fn filter_out_overlapping_arbitrary_non_service_entries(
    desired_service_nat_entries: &ServiceZoneNatEntries,
    stale_service_entries: &BTreeSet<ServiceZoneNatEntry>,
    entries: &BTreeSet<NatEntry>,
) -> bool {
    let prior = desired_service_nat_entries
        .iter()
        .chain(stale_service_entries.iter())
        .map(|e| collapse_ipv4_mapped(e.kind.external_ip()))
        .collect::<BTreeSet<_>>();
    let mut entry_ips = BTreeSet::new();
    for e in entries {
        if !entry_ips.insert(collapse_ipv4_mapped(e.target_ip)) {
            return false;
        }
    }
    prior.intersection(&entry_ips).next().is_none()
}

impl TestInput {
    // All entries we should set up in dpd before reconciling.
    fn entries_that_should_exist_at_start_of_test(
        &self,
    ) -> impl Iterator<Item = NatEntry> + '_ {
        self.desired_service_nat_entries
            .iter()
            .take(self.preexisting_service_nat_entries)
            .chain(self.stale_service_entries.iter())
            .map(NatEntry::from)
            .chain(self.preexisting_non_service_entries.iter().copied())
    }

    // All entries we expect to exist in dpd after reconciling.
    fn entries_that_should_exist_after_reconciliation(
        &self,
    ) -> impl Iterator<Item = NatEntry> + '_ {
        self.desired_service_nat_entries
            .iter()
            .map(NatEntry::from)
            .chain(self.preexisting_non_service_entries.iter().copied())
    }

    async fn apply_initial_to_dpd(
        &self,
        client: &dpd_client::Client,
    ) -> anyhow::Result<()> {
        // Reset from any previous test. (One `dendrite` instance is used across
        // multiple proptest invocations).
        self.erase_all_nat_entries(client)
            .await
            .context("failed to erase all NAT entries at start of test")?;

        for entry in self.entries_that_should_exist_at_start_of_test() {
            create_nat_entry(client, &entry).await.with_context(|| {
                format!("failed to create initial entry {entry:?}")
            })?;
        }

        Ok(())
    }

    async fn validate_post_reconciliation(
        &self,
        client: &dpd_client::Client,
    ) -> anyhow::Result<()> {
        let dpd_entries = self.collect_all_dpd_entries(client).await?;
        let expected_entries = self
            .entries_that_should_exist_after_reconciliation()
            .collect::<BTreeSet<_>>();
        assert_eq!(expected_entries, dpd_entries);
        Ok(())
    }

    async fn collect_all_dpd_entries(
        &self,
        client: &dpd_client::Client,
    ) -> anyhow::Result<BTreeSet<NatEntry>> {
        let mut all_entries = BTreeSet::new();

        // Collect IPv4
        let mut stream_addresses =
            client.nat_ipv4_addresses_list_stream(SINGLE_REQUEST_LIMIT);
        while let Some(ip) = stream_addresses
            .try_next()
            .await
            .context("failed while streaming ipv4 addrs")?
        {
            let mut entries =
                client.nat_ipv4_list_stream(&ip, SINGLE_REQUEST_LIMIT);
            while let Some(e) = entries
                .try_next()
                .await
                .context("failed while streaming ipv4 NAT entries")?
            {
                all_entries.insert(
                    NatEntry::try_from(e.clone()).with_context(|| {
                        format!("failed to convert {e:?} to NatEntry")
                    })?,
                );
            }
        }

        // Collect IPv6
        let mut stream_addresses =
            client.nat_ipv6_addresses_list_stream(SINGLE_REQUEST_LIMIT);
        while let Some(ip) = stream_addresses
            .try_next()
            .await
            .context("failed while streaming ipv6 addrs")?
        {
            let mut entries =
                client.nat_ipv6_list_stream(&ip, SINGLE_REQUEST_LIMIT);
            while let Some(e) = entries
                .try_next()
                .await
                .context("failed while streaming ipv6 NAT entries")?
            {
                all_entries.insert(
                    NatEntry::try_from(e.clone()).with_context(|| {
                        format!("failed to convert {e:?} to NatEntry")
                    })?,
                );
            }
        }

        Ok(all_entries)
    }

    async fn erase_all_nat_entries(
        &self,
        client: &dpd_client::Client,
    ) -> anyhow::Result<()> {
        for e in self.collect_all_dpd_entries(client).await? {
            match e.target_ip {
                IpAddr::V4(ip) => {
                    client
                        .nat_ipv4_delete(&ip, e.first_port)
                        .await
                        .with_context(|| format!("failed to delete {e:?}"))?;
                }
                IpAddr::V6(ip) => {
                    client
                        .nat_ipv6_delete(&ip, e.first_port)
                        .await
                        .with_context(|| format!("failed to delete {e:?}"))?;
                }
            }
        }

        Ok(())
    }
}

#[proptest]
fn proptest_plan_mix(input: TestInput) {
    let logctx = omicron_test_utils::dev::test_setup_log("proptest_plan_mix");
    let log = &logctx.log;

    // We expect to remove all stale service entries.
    let expected_to_remove = input
        .stale_service_entries
        .iter()
        .map(NatEntry::from)
        .collect::<BTreeSet<_>>();

    // The "current entries" includes all stale entries plus a subset of the
    // desired entries; start with the stale ones, and we add the subset in the
    // loop below.
    let mut dpd_current_entries = expected_to_remove.clone();

    // Now add the number of common entries we expect.
    let mut expected_unchanged = BTreeSet::new();
    let mut expected_to_create = BTreeMap::new();
    for (i, entry) in input.desired_service_nat_entries.iter().enumerate() {
        if i < input.preexisting_service_nat_entries {
            dpd_current_entries.insert(NatEntry::from(entry));
            expected_unchanged.insert(entry.zone_id);
        } else {
            expected_to_create.insert(entry.zone_id, NatEntry::from(entry));
        }
    }

    let plan = ReconciliationPlan::new(
        &dpd_current_entries,
        &input.desired_service_nat_entries,
        log,
    )
    .expect("planning should succeed");

    let expected = ReconciliationPlan {
        unchanged: expected_unchanged,
        to_remove: expected_to_remove,
        to_create: expected_to_create,
    };

    assert_eq!(plan, expected);

    logctx.cleanup_successful();
}

#[tokio::test(flavor = "multi_thread")]
async fn proptest_full_reconciliation() {
    let logctx =
        omicron_test_utils::dev::test_setup_log("proptest_full_reconciliation");
    let mgsctx = gateway_test_utils::setup::test_setup(
        "proptest_full_reconciliation",
        SpPort::One,
    )
    .await;
    let dpdctx = dev::dendrite::DendriteInstance::start(
        None,
        mgsctx.address().into(),
        &logctx.log,
    )
    .await
    .expect("started dendrite");
    let client = dpd_client::Client::new(
        &format!("http://{}", dpdctx.address()),
        dpd_client::ClientState {
            tag: OMICRON_DPD_TAG.to_owned(),
            log: logctx.log.clone(),
        },
    );
    let rt = tokio::runtime::Handle::current();

    let one_test_invocation = async |input: TestInput| {
        input
            .apply_initial_to_dpd(&client)
            .await
            .expect("applied initial setup to dpd");

        let status =
            reconcile(&client, &input.desired_service_nat_entries, &logctx.log)
                .await;

        match status {
            DpdNatReconcilerStatus::NoNatEntriesConfig
            | DpdNatReconcilerStatus::FailedReadingCurrentDpdNatEntries(_)
            | DpdNatReconcilerStatus::InvalidSystemNetworkingConfig(_)
            | DpdNatReconcilerStatus::PartialSuccess { .. } => {
                panic!("unexpected reconciler status: {status:?}");
            }
            DpdNatReconcilerStatus::Success { .. } => {
                input
                    .validate_post_reconciliation(&client)
                    .await
                    .expect("validated post reconciliation entries");
            }
        }
    };

    proptest_macro!(|(input: TestInput)| {
        // Do a little dance to call our async `one_test_invocation` within the
        // non-async `proptest_macro!()` context.
        block_in_place(|| rt.block_on(one_test_invocation(input)));
    });

    dpdctx.cleanup().await.expect("dpd cleanup succeeded");
    mgsctx.teardown().await;
    logctx.cleanup_successful();
}
