#!/bin/bash

# wrapper around `cockroach` for running `cockroach version` under DTrace

set -o errexit
set -o xtrace

dir="$(dirname "${BASH_SOURCE[0]}")"
cd $dir/..

#real_cockroach="/home/dap/issues/omicron-1130-port-getn-einval/bin/cockroach"
real_cockroach="/home/dap/tools/cockroach-22.1.9-fail-fast.3/cockroach-v22.1.9/bin/cockroach"

if [[ $1 != "version" ]]; then
	echo "debug-bin/cockroach: not instrumenting this invocation"
	exec "$real_cockroach" "$@"
fi

#gotracemem="$HOME/issues/omicron-1130-port-getn-einval/trace-cockroachdb-einval2.d"
gotracemem="$HOME/issues/go-memory/gotraceit.d"
output_dtrace_base="$PWD/dtrace-output/dtrace-$$"

for (( i = 0; ; i++ )) {
	output_dtrace="$output_dtrace_base.$i.out"
	if ! [[ -e $output_dtrace ]]; then
		break
	fi
}

echo "debug-bin/cockroach: using $output_dtrace" >&2

GOTRACEBACK=crash \
    pfexec "$gotracemem" \
        -o $output_dtrace \
	-c "$real_cockroach $*"
