-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'rack' AND index_name = 'lookup_rack_by_subnet')),'true','Schema change verification failed: index lookup_rack_by_subnet on table rack does not exist') AS BOOL);
