:showtitle:
:toc: left
:icons: font

= Oxide Control Plane Prototype

This repo houses a prototype for the Oxide Rack control plane.

image::https://github.com/oxidecomputer/oxide-api-prototype/workflows/Rust/badge.svg[]

== Documentation

Several Oxide RFDs are relevant:

* https://4.rfd.oxide.computer[RFD 4 User Facing API Design]
* https://10.rfd.oxide.computer[RFD 10 API Prototype and Simulated
  Implementation]
* https://48.rfd.oxide.computer[RFD 48 Control Plane Requirements]
* https://61.rfd.oxide.computer[RFD 61 Control Plane Architecture and Design]

For documentation on the control plane architecture, see
https://61.rfd.oxide.computer[RFD 61].

For design and API docs, see the
https://rust.docs.corp.oxide.computer/oxide_api_prototype/[generated
documentation].  You can generate this yourself with:

[source,text]
----
$ cargo doc --document-private-items
----

Note that `--document-private-items` is configured by default, so you can
actually just use `cargo doc`.

== Status

The code here is still rough, but the following are implemented:

* actual API:
** projects: CRUD
** instances: CRUD + boot/halt/reboot
** disks: CRD + attach/detach
** racks: list + get
** sleds: list + get
* architecture:
** oxide controller (OXC): manages a fleet of Oxide racks
** sled agent: manages a single compute sled in an Oxide fleet
* basic server infrastructure: configuration, logging
* test coverage for most of the above

See TODO.adoc for more info.

== Build and run

You can **build and run the whole test suite** with `cargo test`.  The test
suite runs cleanly and should remain clean.

You can **format the code** using `cargo fmt`.  Make sure to run this before
pushing changes.  The CI checks that the code is correctly formatted.

To **run the system:** there are two executables: the `oxide_controller` (which
is a real prototype backed by an in-memory store; this component manages an
Oxide fleet), and the `sled_agent` (which is a simulation of the component that
will manage a single sled).

`oxide_controller` requires a configuration file to run.  You can use
`examples/config.toml` to start with.  Build and run it like this:

[source,text]
----
$ cargo run --bin=oxide_controller -- examples/config.toml
...
listening: http://127.0.0.1:12220
----

`sled_agent` only takes configuration on the command line.  Run it with a uuid
identifying itself (this would be a uuid for the sled it's managing), an
IP:port for itself, and the IP:port of `oxide_controller`'s _internal_
interface.  Using default config, this might look like this:

[source,text]
----
$ cargo run --bin=sled_agent -- $(uuidgen) 127.0.0.1:12345 127.0.0.1:12221
...
Jun 02 12:21:50.989 INFO listening, local_addr: 127.0.0.1:12345, component: dropshot
----

You can use `curl` directly to hit either of these servers, but it's easier to
use the `oxapi_demo` wrapper (see below).

== Quick demo

There's a small demo tool called `./tools/oxapi_demo` that provides a slightly
friendlier interface than `curl`, with the same output format.  Here's a small
demo that creates a project, creates an instance, and attaches a disk to it:

[source,text]
----
$ ./tools/oxapi_demo 
oxapi_demo: command not specified

PROJECTS

    projects_list
    project_create_demo    PROJECT_NAME
    project_delete         PROJECT_NAME
    project_get            PROJECT_NAME
    project_list_instances PROJECT_NAME
    project_list_disks     PROJECT_NAME

INSTANCES

    instance_create_demo PROJECT_NAME INSTANCE_NAME
    instance_get         PROJECT_NAME INSTANCE_NAME
    instance_delete      PROJECT_NAME INSTANCE_NAME

    instance_stop        PROJECT_NAME INSTANCE_NAME
    instance_start       PROJECT_NAME INSTANCE_NAME
    instance_reboot      PROJECT_NAME INSTANCE_NAME

    instance_attach_disk PROJECT_NAME INSTANCE_NAME DISK_NAME
    instance_detach_disk PROJECT_NAME INSTANCE_NAME DISK_NAME
    instance_list_disks  PROJECT_NAME INSTANCE_NAME
    instance_get_disk    PROJECT_NAME INSTANCE_NAME DISK_NAME

DISKS

    disk_create_demo PROJECT_NAME DISK_NAME
    disk_get PROJECT_NAME DISK_NAME

HARDWARE

    racks_list
    rack_get     RACK_ID

    sleds_list
    sled_get     SERVER_ID


$ ./tools/oxapi_demo project_create_demo myproject
++ curl -sSi http://127.0.0.1:12220/projects -X POST -T -
++ json -ga
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
content-type: application/json
x-request-id: 6e357d79-dc11-4418-8f9d-3c50fce13027
content-length: 196
date: Wed, 27 May 2020 00:45:03 GMT

{
  "id": "9c159daa-fdd1-402b-bc98-e1bebaeb578c",
  "name": "myproject",
  "description": "a project called myproject",
  "timeCreated": "2020-05-27T00:45:03.563996Z",
  "timeModified": "2020-05-27T00:45:03.563996Z"
}


$ ./tools/oxapi_demo instance_create_demo myproject myinstance
++ curl -sSi http://127.0.0.1:12220/projects/myproject/instances -X POST -T -
++ json -ga
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
content-type: application/json
x-request-id: ec65473d-7c0f-462d-a0cb-2e35fabb6533
content-length: 388
date: Wed, 27 May 2020 00:45:24 GMT

{
  "id": "d58039dc-4ed3-44de-a5d4-cd4696246799",
  "name": "myinstance",
  "description": "an instance called myinstance",
  "timeCreated": "2020-05-27T00:45:24.784729Z",
  "timeModified": "2020-05-27T00:45:24.784729Z",
  "projectId": "9c159daa-fdd1-402b-bc98-e1bebaeb578c",
  "ncpus": 1,
  "memory": 256,
  "bootDiskSize": 1,
  "hostname": "myproject",
  "runState": "starting",
  "timeRunStateUpdated": "2020-05-27T00:45:24.785445Z"
}


$ ./tools/oxapi_demo instance_get myproject myinstance
++ curl -sSi http://127.0.0.1:12220/projects/myproject/instances/myinstance
++ json -ga
HTTP/1.1 200 OK
content-type: application/json
x-request-id: c228154b-ddd1-4758-b51c-e5c0547727ba
content-length: 387
date: Wed, 27 May 2020 00:45:42 GMT

{
  "id": "d58039dc-4ed3-44de-a5d4-cd4696246799",
  "name": "myinstance",
  "description": "an instance called myinstance",
  "timeCreated": "2020-05-27T00:45:24.784729Z",
  "timeModified": "2020-05-27T00:45:24.784729Z",
  "projectId": "9c159daa-fdd1-402b-bc98-e1bebaeb578c",
  "ncpus": 1,
  "memory": 256,
  "bootDiskSize": 1,
  "hostname": "myproject",
  "runState": "running",
  "timeRunStateUpdated": "2020-05-27T00:45:26.291810Z"
}


$ ./tools/oxapi_demo disk_create_demo myproject mydisk
++ curl -sSi http://127.0.0.1:12220/projects/myproject/disks -X POST -T -
++ json -ga
HTTP/1.1 100 Continue

HTTP/1.1 201 Created
content-type: application/json
x-request-id: e004d88f-d8cc-4721-8000-583b504a5372
content-length: 314
date: Wed, 27 May 2020 00:45:34 GMT

{
  "id": "bb225f2a-bba3-4d5c-9161-117b8a5b678d",
  "name": "mydisk",
  "description": "a disk called mydisk",
  "timeCreated": "2020-05-27T00:45:34.119234Z",
  "timeModified": "2020-05-27T00:45:34.119234Z",
  "projectId": "9c159daa-fdd1-402b-bc98-e1bebaeb578c",
  "snapshotId": null,
  "size": 1024,
  "state": "creating",
  "devicePath": "/mnt/mydisk"
}


$ ./tools/oxapi_demo disk_get myproject mydisk
++ curl -sSi http://127.0.0.1:12220/projects/myproject/disks/mydisk
++ json -ga
HTTP/1.1 200 OK
content-type: application/json
x-request-id: 09608040-f645-4f1e-941f-2f4629cdedd0
content-length: 314
date: Wed, 27 May 2020 00:45:50 GMT

{
  "id": "bb225f2a-bba3-4d5c-9161-117b8a5b678d",
  "name": "mydisk",
  "description": "a disk called mydisk",
  "timeCreated": "2020-05-27T00:45:34.119234Z",
  "timeModified": "2020-05-27T00:45:34.119234Z",
  "projectId": "9c159daa-fdd1-402b-bc98-e1bebaeb578c",
  "snapshotId": null,
  "size": 1024,
  "state": "detached",
  "devicePath": "/mnt/mydisk"
}


$ ./tools/oxapi_demo instance_attach_disk myproject myinstance mydisk
++ curl -sSi http://127.0.0.1:12220/projects/myproject/instances/myinstance/disks/mydisk -X PUT -T /dev/null
++ json -ga
HTTP/1.1 201 Created
content-type: application/json
x-request-id: 933cecce-d356-4cd4-b1b2-728cecf29a45
content-length: 214
date: Wed, 27 May 2020 00:46:04 GMT

{
  "instanceName": "myinstance",
  "instanceId": "d58039dc-4ed3-44de-a5d4-cd4696246799",
  "diskName": "mydisk",
  "diskId": "bb225f2a-bba3-4d5c-9161-117b8a5b678d",
  "diskState": {
    "attaching": "d58039dc-4ed3-44de-a5d4-cd4696246799"
  }
}


$ ./tools/oxapi_demo instance_list_disks myproject myinstance 
++ curl -sSi http://127.0.0.1:12220/projects/myproject/instances/myinstance/disks
++ json -ga
HTTP/1.1 200 OK
content-type: application/x-ndjson
x-request-id: fb3f4d2a-4992-4816-94df-1aa2c461777c
content-length: 214
date: Wed, 27 May 2020 00:46:11 GMT

{
  "instanceName": "myinstance",
  "instanceId": "d58039dc-4ed3-44de-a5d4-cd4696246799",
  "diskName": "mydisk",
  "diskId": "bb225f2a-bba3-4d5c-9161-117b8a5b678d",
  "diskState": {
    "attached": "d58039dc-4ed3-44de-a5d4-cd4696246799"
  }
}
----


== Configuration reference

`oxide_controller` requires a TOML configuration file.  There's an example in
`examples/config.toml`:

[source,toml]
----
include::examples/config.toml[]
----

Supported config properties include:

[cols="1,1,1,3",options="header"]
|===
|Name
|Example
|Required?
|Description

|`dropshot_external`
|
|Yes
|Dropshot configuration for the external server (i.e., the one that operators
and developers using the Oxide rack will use).  Specific properties are
documented below, but see the Dropshot README for details.

|`dropshot_external.bind_address`
|`"127.0.0.1:12220"`
|Yes
|Specifies that the server should bind to the given IP address and TCP port for
the **external** API (i.e., the one that operators and developers using the
Oxide rack will use).  In general, servers can bind to more than one IP address
and port, but this is not (yet?) supported.

|`dropshot_external.request_body_max_bytes`
|`1000`
|Yes
|Specifies the maximum request body size for the **external** API.

|`dropshot_internal`
|
|Yes
|Dropshot configuration for the internal server (i.e., the one used by the sled
agent).  Specific properties are documented below, but see the Dropshot README
for details.

|`dropshot_internal.bind_address`
|`"127.0.0.1:12220"`
|Yes
|Specifies that the server should bind to the given IP address and TCP port for
the **internal** API (i.e., the one used by the sled agent).  In general,
servers can bind to more than one IP address and port, but this is not (yet?)
supported.

|`dropshot_internal.request_body_max_bytes`
|`1000`
|Yes
|Specifies the maximum request body size for the **internal** API.

|`log`
|
|Yes
|Logging configuration.  Specific properties are documented below, but see the
Dropshot README for details.

|`log.mode`
|`"file"`
|Yes
|Controls where server logging will go.  Valid modes are `"stderr-terminal"` and
`"file".  If the mode is `"stderr-terminal"`, human-readable output, with colors
and other terminal formatting if possible, will be sent to stderr.  If the mode
is `"file"`, Bunyan-format output will be sent to the filesystem path given by
`log.path`.  See also `log.if_exists`, which controls the behavior if the
destination path already exists.

|`log.level`
|`"info"`
|Yes
|Specifies what severity of log messages should be included in the log.  Valid
values include `"trace"`, `"debug"`, `"info"`, `"warn"`, `"error"`, and
`"critical"`, which are increasing order of severity.  Log messages at the
specified level and more severe levels will be included in the log.

|`log.path`
|`"logs/server.log"`
|Only if `log.mode = "file"`
|If `log.mode` is `"file"`, this property determines the path to the log file.
See also `log.if_exists`.

|`log.if_exists`
|`"append"`
|Only if `log.mode = "file"`
|If `log.mode` is `"file"`, this property specifies what to do if the
destination log file already exists.  Valid values include `"append"` (which
appends to the existing file), `"truncate"` (which truncates the existing file
and then uses it as though it had just been created), and `"fail"` (which causes
the server to exit immediately with an error).

|===
