-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM fm_config] WHERE constraint_name = 'certificate_expiry_warning_days_validity' AND validated = true)),'true','Schema change verification failed: constraint certificate_expiry_warning_days_validity not found on table fm_config') AS BOOL);
