-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM network_interface] WHERE constraint_name = 'at_least_one_ip_address' AND validated = true)),'true','Schema change verification failed: constraint at_least_one_ip_address not found on table network_interface') AS BOOL);
