-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vmm' AND column_name = 'state' AND is_nullable = 'NO')),'true','Schema change verification failed: column state on table vmm is still nullable') AS BOOL);
