-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM instance] WHERE constraint_name = 'vmm_iff_active_propolis' AND validated = true)),'true','Schema change verification failed: constraint vmm_iff_active_propolis not found on table instance') AS BOOL);
