-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'internet_gateway' AND index_name = 'lookup_internet_gateway_by_vpc')),'true','Schema change verification failed: index lookup_internet_gateway_by_vpc on table internet_gateway does not exist') AS BOOL);
