-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'inv_collection' AND index_name = 'inv_collectionby_time_done')),'true','Schema change verification failed: index inv_collectionby_time_done on table inv_collection does not exist') AS BOOL);
