-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'inv_omicron_zone' AND index_name = 'inv_omicron_zone_nic_id')),'true','Schema change verification failed: index inv_omicron_zone_nic_id on table inv_omicron_zone does not exist') AS BOOL);
