-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'vpc_router' AND index_name = 'lookup_routers_in_vpc')),'true','Schema change verification failed: index lookup_routers_in_vpc on table vpc_router does not exist') AS BOOL);
