:showtitle:
:numbered:

= Database Schemas

This directory describes the schema(s) used by CockroachDB.

We use the following conventions:

* `schema/crdb/VERSION/up*.sql`: Files containing the necessary idempotent
  statements to transition from the previous version of the database schema to
  this version.  All of the statements in a given file will be executed
  together in one transaction; however, usually only one statement should
  appear in each file.  More on this below.
** If there's only one statement required, we put it into `up.sql`.
** If more than one change is needed, any number of files starting with `up`
   and ending with `.sql` may be used. These files  must follow a
   numerically-increasing pattern starting with 1 (leading prefixes are allowed,
   so `up1.sql`, `up2.sql`, ..., or `up01.sql`, `up02.sql`, etc.), and they will
   be sorted numerically by these values.  Each will be executed in a separate
   transaction.
** CockroachDB documentation recommends the following: "Execute schema
   changes ... in an explicit transaction consisting of the single schema
   change statement.".  Practically this means: If you want to change multiple
   tables, columns, types, indices, or constraints, do so in separate files.
   See https://www.cockroachlabs.com/docs/stable/online-schema-changes for
   more.
* `schema/crdb/dbinit.sql`: The necessary operations to create the latest
  version of the schema. Should be equivalent to running all `up.sql`
  migrations, in-order.
* `schema/crdb/dbwipe.sql`: The necessary operations to delete the latest
  version of the schema.

Note that to upgrade from version N to version N+2, we always apply the N+1
upgrade first, before applying the N+2 upgrade. This simplifies our model of DB
schema changes by ensuring an incremental, linear history.

== Offline Upgrade

Nexus currently supports **offline** schema migrations.
This means we're operating with the following constraints:

* We assume that downtime is acceptable to perform an update.
* We assume that while an update is occuring, all Nexus services
  are running the same version of software.
* We assume that no (non-upgrade) concurrent database requests will happen for
  the duration of the migration.

This is not an acceptable long-term solution - we must be able to update
without downtime - but it is an interim solution, and one which provides a
fall-back pathway for performing upgrades.

See RFD 319 for more discussion of the online upgrade plans.

== How to change the schema

Assumptions:

* We'll call the (previously) latest schema version `OLD_VERSION`.
* We'll call your new schema version `NEW_VERSION`.  This will always be a major
  version bump from `OLD_VERSION`.  So if `OLD_VERSION` is 43.0.0, `NEW_VERSION`
  should be `44.0.0`.
* You can write a sequence of SQL statements to update a database that's
  currently running `OLD_VERSION` to one running `NEW_VERSION`.

Process:

* Create a directory of SQL files describing how to update a database running
  version `OLD_VERSION` to one running version `NEW_VERSION`:
** Choose a unique, descriptive name for the directory.  It's suggested that
   you stick to lowercase letters, numbers, and hyphen.  For example, if you're
   adding a table called `widgets`, you might create a directory called
   `create-table-widgets`.
** Create the directory: `schema/crdb/NAME`.
*** If only one SQL statement is necessary to get from `OLD_VERSION` to
    `NEW_VERSION`, put that statement into `schema/crdb/NAME/up.sql`.  If
    multiple statements are required, put each one into a separate file, naming
    these `schema/crdb/NAME/upN.sql` for as many `N` as you need, starting with
    `N=1`.
*** Each file should contain _either_ one schema-modifying statement _or_ some
    number of data-modifying statements.  You can combine multiple data-modifying
    statements.  But you should not mix schema-modifying statements and
    data-modifying statements in one file.  And you should not include multiple
    schema-modifying statements in one file.
*** Beware that the entire file will be run in one transaction.  Expensive data-
    modifying operations leading to long-running transactions are generally
    to-be-avoided; however, there's no better way to do this today if you really
    do need to update thousands of rows as part of the update.
* Update `schema/crdb/dbinit.sql`:
** Update the SQL statements to match what the database should look like
   after your up*.sql files are applied.
** Update the version field of `db_metadata` at the bottom of the file.
* Update `schema/crdb/dbwipe.sql` if needed.  (This is rare.)
* Update `nexus/db-model/src/schema_versions.rs`:
** Update the major number of `SCHEMA_VERSION` so that it matches `NEW_VERSION`.
** Add a new entry to the *top* of `KNOWN_VERSIONS`.  It should be just one
   line: `KnownVersion::new(NEW_VERSION.major, NAME)`
* Optional: check some of this work by running `cargo nextest run -p nexus-db-model -- schema_versions`.  This is recommended because if you get
  one of these steps wrong, these tests should be able to tell you, whereas
  other tests might fail in much worse ways (e.g., they can hang if you've
  updated `SCHEMA_VERSION` but not the database schema version).

There are automated tests to validate many of these steps:

* The `SCHEMA_VERSION` matches the version used in `dbinit.sql`.  (This catches
  the case where you forget to update either one of these).
* The `KNOWN_VERSIONS` are all strictly increasing semvers.  New known versions
  must be sequential major numbers with minor and micro both being `0`.  (This
  catches various mismerge errors: accidentally duplicating a version, putting
  versions in the wrong order, etc.)
* The combination of all `up*.sql` files results in the same schema as
  `dbinit.sql`.  (This catches forgetting to update dbinit.sql, forgetting to
  implement a schema update altogether, or a mismatch between dbinit.sql and
  the update.)
* All `up*.sql` files can be applied twice without error.  (This catches
  non-idempotent update steps.)

**If you've finished all this and another PR lands on "main" that chose the
same `NEW_VERSION`:**, then your `OLD_VERSION` has changed and so _your_
`NEW_VERSION` needs to change, too.  You'll need to:

* In `nexus/db-model/src/schema_versions.rs`.
** Make sure `SCHEMA_VERSION` reflects your new `NEW_VERSION`.
** Make sure the `KNOWN_VERSIONS` entry that you added reflects your new
   `NEW_VERSION` and still appears at the top of the list (logically after the
   new version that came in from "main").
* Update the version in `dbinit.sql` to match the new `NEW_VERSION`.

=== General notes

CockroachDB's representation of the schema includes some opaque
internally-generated fields that are order dependent, like the names of
anonymous CHECK constraints.  Our schema comparison tools intentionally ignore
these values. As a result, when performing schema changes, the order of new
tables and constraints should generally not be important.

As convention, however, we recommend keeping the `db_metadata` file at the end
of `dbinit.sql`, so that the database does not contain a version until it is
fully populated.

=== Scenario-specific gotchas

==== Renaming columns

Idempotently renaming existing columns is unfortunately not possible in our
current database configuration. (Postgres doesn't support the use of an `IF
EXISTS` qualifier on an `ALTER TABLE RENAME COLUMN` statement, and the version
of CockroachDB we use at this writing doesn't support the use of user-defined
functions as a workaround.)

An (imperfect) workaround is to use the `#[diesel(column_name = foo)]` attribute
in Rust code to preserve the existing name of a column in the database while
giving its corresponding struct field a different, more meaningful name.
