
CREATE TABLE IF NOT EXISTS omicron.public.ereport (
    /*
     * the primary key for an ereport is formed from the tuple of the
     * reporter's restart ID (a randomly generated UUID) and the ereport's ENA
     * (a 64-bit integer that uniquely identifies the ereport within that
     * restart of the reporter).
     *
     * see: https://rfd.shared.oxide.computer/rfd/520#ereport-metadata
     */
    restart_id UUID NOT NULL,
    ena INT8 NOT NULL,
    time_deleted TIMESTAMPTZ,

    /* time at which the ereport was collected */
    time_collected TIMESTAMPTZ NOT NULL,
    /* UUID of the Nexus instance that collected the ereport */
    collector_id UUID NOT NULL,

    /*
     * VPD identity of the reporter.
     *
     * unlike the SP location and sled UUID, these fields are always nullable,
     * regardless of whether the ereport was reported by a SP or the host OS.
     * this is necessary because an ereport may be generated in a state where
     * the SP doesn't know who or what it is.
     * consider that "i don't know my own identity" is a reasonable condition
     * to want to generate an ereport about!
     */
    part_number STRING,
    serial_number STRING,

    /*
     * The ereport class, which indicates the category of event reported.
     *
     * This is nullable, as it is extracted from the report JSON, and reports
     * missing class information must still be ingested.
     */
    class STRING,

    /*
     * JSON representation of the ereport as received from the SP.
     *
     * the raw JSON representation of the ereport is always stored, alongside
     * any more structured data that we extract from it, as extracting data
     * from the received ereport requires additional knowledge of the ereport
     * formats generated by the SP and its various tasks. as these may change,
     * and new ereports may be added which Nexus may not yet be aware of,
     * we always store the raw JSON representation of the ereport. as Nexus
     * becomes aware of new ereport schemas, it can go back and extract
     * structured data from previously collected ereports with those schemas,
     * but this is only possible if the JSON blob is persisted.
     *
     * see also: https://rfd.shared.oxide.computer/rfd/520#data-model
     */
    report JSONB NOT NULL,

    /*
     * whether this ereport was generated by SP firmware or the host OS.
     *
     * this determines the key used to identify the reporter:
     * - for SP ereports, the reporter is identified by its SP type and slot,
     *   which is how the SP is indexed when requesting ereports from MGS.
     * - for host OS ereports, the reporter is identified by the sled UUID.
     *
     * depending on the reporter type, either the SP location or sled UUID
     * fields will be non-NULL.
     */
    reporter omicron.public.ereporter_type NOT NULL,

    /*  physical location for SP reporters. */
    sp_type omicron.public.sp_type,
    sp_slot INT4,

    /* sled UUID for host OS reporters. */
    sled_id UUID,

    CONSTRAINT reporter_identity_validity CHECK (
        (
            -- ereports from SPs must have a SP type and slot,
            -- and must not have a sled ID.
            reporter = 'sp'
                AND sp_type IS NOT NULL
                AND sp_slot IS NOT NULL
                AND sled_id IS NULL
        ) OR (
            -- ereports from the sled host OS must have a sled ID,
            -- and must not have a SP type or slot.
            reporter = 'host'
                AND sled_id IS NOT NULL
                AND sp_type IS NULL
                AND sp_slot IS NULL
        )
    ),

    PRIMARY KEY (restart_id, ena)
);
