-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'ereport' AND index_name = 'lookup_ereports_by_sp_slot')),'true','Schema change verification failed: index lookup_ereports_by_sp_slot on table ereport does not exist') AS BOOL);
