-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM silo_user] WHERE constraint_name = 'external_id_consistency' AND validated = true)),'true','Schema change verification failed: constraint external_id_consistency not found on table silo_user') AS BOOL);
