-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM silo_group] WHERE constraint_name = 'user_provision_type_required_for_non_deleted' AND validated = true)),'true','Schema change verification failed: constraint user_provision_type_required_for_non_deleted not found on table silo_group') AS BOOL);
