-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'silo_group' AND index_name = 'lookup_silo_group_by_silo')),'true','Schema change verification failed: index lookup_silo_group_by_silo on table silo_group does not exist') AS BOOL);
