-- Table tracking the timestamp of the first ereport received from each restart
-- ID.
CREATE TABLE IF NOT EXISTS omicron.public.ereporter_restart (
    -- The reporter restart ID.
    --
    -- This corresponds to the `restart_id` column in `omicron.public.ereport`.
    id UUID PRIMARY KEY,
    -- The timestamp at which the first ereport received from this restart ID
    -- was received.
    time_first_seen TIMESTAMPTZ NOT NULL,
    -- Whether this ereport was generated by SP firmware or the host OS.
    reporter omicron.public.ereporter_type NOT NULL,
    -- The type of the physical slot occupied by the reporter.
    slot_type omicron.public.sp_type NOT NULL,
    -- The number of the physical slot occupied by the reporter.
    --
    -- For sled host OS reporters, this may be NULL if the sled's location is
    -- not known to the system when the ereport was received. If the physical
    -- location of the sled is determined later, subsequent attempts to insert
    -- ereports will update this field.
    slot INT4,

    CONSTRAINT reporter_validity CHECK (
        (
            -- ereports from SPs must always have a SP type and slot, so we need
            -- not worry about temporarily accepting NULL slots so that they can
            -- be back-populated later as we do for host OS reporters.
            reporter = 'sp'  AND slot IS NOT NULL
        ) OR (
            -- ereports from the sled host OS must have the 'sled' slot type (as
            -- switches and PSCs do not have a host OS)
            reporter = 'host' AND slot_type = 'sled'
        )
    )
);
