-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'network_interface' AND index_name = 'network_interface_by_parent')),'true','Schema change verification failed: index network_interface_by_parent on table network_interface does not exist') AS BOOL);
