-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'sled' AND index_name = 'sled_by_policy')),'true','Schema change verification failed: index sled_by_policy on table sled does not exist') AS BOOL);
