-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'probe' AND index_name = 'lookup_probe_by_name')),'true','Schema change verification failed: index lookup_probe_by_name on table probe does not exist') AS BOOL);
