-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'external_ip' AND column_name = 'is_probe')),'true','Schema change verification failed: column is_probe on table external_ip does not exist (backfill may not have completed)') AS BOOL);
