-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'switch_port' AND index_name = 'switch_port_name')),'true','Schema change verification failed: index switch_port_name on table switch_port does not exist') AS BOOL);
