-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM external_ip] WHERE constraint_name = 'null_project_id' AND validated = true)),'true','Schema change verification failed: constraint null_project_id not found on table external_ip') AS BOOL);
