#!/bin/ksh

set -ex -o pipefail

. /lib/svc/share/smf_include.sh

# set up the users required for wicket and support.
USERS=(
    (user=wicket group=wicket gecos='Wicket User' nopasswd=1 shell='/bin/sh')
    (user=support group=support gecos='Oxide Support' homedir='/home/support'
        shell='/bin/bash' profiles=('Primary Administrator')
    )
)

for i in "${!USERS[@]}"; do
    nameref u=USERS[$i]

    # Add a new group for the user.
    getent group "${u.group}" >/dev/null 2>&1 || groupadd "${u.group}"
    # Add the user.
    getent passwd "${u.user}" >/dev/null 2>&1 || \
        useradd -m -s "${u.shell}" -g "${u.group}" -c "${u.gecos}" \
        "${u.user}"

    # Either enable passwordless login (wicket) or disable password-based logins
    # completely (support, which logs in via ssh key).
    if ((u.nopasswd)); then
        passwd -d "${u.user}"
    else
        passwd -N "${u.user}"
    fi

    # Assign or remove profiles
    if [[ -n "${u.profiles}" ]]; then
        usermod -P"$(printf '%s,' "${u.profiles[@]}")" "${u.user}"
    else
        usermod -P '' "${u.user}"
    fi

    if [[ -n "${u.homedir}" ]]; then
        mkdir -p "${u.homedir}"
        for f in .bashrc .profile; do
            cp "/root/$f" "${u.homedir}/$f"
        done
        chown -R "${u.user}" "${u.homedir}"
    fi
done

exit $SMF_EXIT_OK
