#!/bin/ksh

set -ex -o pipefail

. /lib/svc/share/smf_include.sh

# set up the users required for wicket and support.
USERS=(
    (user=wicket group=wicket gecos='Wicket User')
    (user=support group=support gecos='Oxide Support'
        profiles=('Primary Administrator')
    )
)

for i in "${!USERS[@]}"; do
    nameref u=USERS[$i]

    # Add a new group for the user.
    getent group "${u.group}" >/dev/null 2>&1 || groupadd "${u.group}"
    # Add the user.
    getent passwd "${u.user}" >/dev/null 2>&1 \
        || useradd -m -g "${u.group}" -c "${u.gecos}" "${u.user}"
    # Remove the password from the user to enable passwordless login.
    passwd -d "${u.user}"
    # Assign or remove profiles
    if [[ -n "${u.profiles}" ]]; then
        usermod -P"$(printf '%s,' "${u.profiles[@]}")" "${u.user}"
    else
        usermod -P '' "${u.user}"
    fi
done

# enable ipv6 forwarding and routing
pfexec routeadm -e ipv6-forwarding -u
pfexec routeadm -e ipv6-routing -u

exit $SMF_EXIT_OK
