-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'bgp_config' AND column_name = 'max_paths' AND is_nullable = 'NO')),'true','Schema change verification failed: column max_paths on table bgp_config is still nullable') AS BOOL);
