# Reflector configuration (oxidecompuer/reflector)

# When any of the listeners configured below activate, run .github/workflows/update-maghemite.yml
# targeting main

workflow = "update-maghemite.yml"
branch = "main"

# Request an installation token when running this workflow

requires_token = true

# Triggers an maghemite update when the job indicating that the commit is read for release completes

[[on]]
repository = "oxidecomputer/maghemite"
event = "check_run"
action = "completed"
check = "omicron-merge"
