# Reflector configuration (oxidecompuer/reflector)

# When any of the listeners configured below activate, run .github/workflows/update-dendrite.yml targeting main

workflow = "update-dendrite.yml"
branch = "main"

# Request an installation token when running this workflow

requires_token = true

# Triggers a dendrite update when the job indicating that the commit is ready for release completes

[[on]]
repository = "oxidecomputer/dendrite"
event = "check_run"
action = "completed"
check = "omicron-merge"
