-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'zpool' AND index_name = 'lookup_zpool_by_disk')),'true','Schema change verification failed: index lookup_zpool_by_disk on table zpool does not exist') AS BOOL);
