-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'sled' AND index_name = 'lookup_sled_by_policy_and_state')),'true','Schema change verification failed: index lookup_sled_by_policy_and_state on table sled does not exist') AS BOOL);
