-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'user_data_export' AND index_name = 'lookup_export_by_resource_type')),'true','Schema change verification failed: index lookup_export_by_resource_type on table user_data_export does not exist') AS BOOL);
