-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM ereport] WHERE constraint_name = 'reporter_identity_validity' AND validated = true)),'true','Schema change verification failed: constraint reporter_identity_validity not found on table ereport') AS BOOL);
