-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT constraint_name FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = 'disk' AND constraint_name = 'check_slot_slot')),'true','Schema change verification failed: constraint check_slot_slot not found on table disk') AS BOOL);
