-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM disk] WHERE constraint_name = 'check_slot_slot' AND validated = true)),'true','Schema change verification failed: constraint check_slot_slot not found on table disk') AS BOOL);
