// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Configuration types for version `LOG_TO_CONSOLE` of the ClickHouse Admin
//! APIs.

use crate::v1;
use camino::Utf8PathBuf;
use omicron_common::api::external::Generation;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::net::Ipv6Addr;

use v1::config::path_schema;

/// Result after generating a configuration file
#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GenerateConfigResult {
    Replica(ReplicaConfig),
    Keeper(KeeperConfig),
}

impl From<GenerateConfigResult> for v1::config::GenerateConfigResult {
    fn from(new: GenerateConfigResult) -> Self {
        match new {
            GenerateConfigResult::Replica(replica) => {
                v1::config::GenerateConfigResult::Replica(replica.into())
            }
            GenerateConfigResult::Keeper(keeper) => {
                v1::config::GenerateConfigResult::Keeper(keeper.into())
            }
        }
    }
}

/// Configuration for a ClickHouse replica server
#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct ReplicaConfig {
    /// Logging settings
    pub logger: LogConfig,
    /// Parameter substitutions for replicated tables
    pub macros: v1::config::Macros,
    /// Address the server is listening on
    pub listen_host: Ipv6Addr,
    /// Port for HTTP connections
    pub http_port: u16,
    /// Port for TCP connections
    pub tcp_port: u16,
    /// Port for interserver HTTP connections
    pub interserver_http_port: u16,
    /// Configuration of clusters used by the Distributed table engine and bythe cluster
    /// table function
    pub remote_servers: v1::config::RemoteServers,
    /// Contains settings that allow ClickHouse servers to interact with a Keeper cluster
    pub keepers: v1::config::KeeperConfigsForReplica,
    /// Directory for all files generated by ClickHouse itself
    #[schemars(schema_with = "path_schema")]
    pub data_path: Utf8PathBuf,
    /// A unique identifier for the configuration generation.
    pub generation: Generation,
}

impl From<ReplicaConfig> for v1::config::ReplicaConfig {
    fn from(new: ReplicaConfig) -> Self {
        // In v1, the path passed to LogConfig::new was the server's datastore
        // path; data_path = datastore_path/data.
        let datastore_path = new
            .data_path
            .parent()
            .expect("ReplicaConfig::data_path always has a parent")
            .to_path_buf();
        v1::config::ReplicaConfig {
            logger: new
                .logger
                .into_v1(&datastore_path, v1::config::NodeType::Server),
            macros: new.macros,
            listen_host: new.listen_host,
            http_port: new.http_port,
            tcp_port: new.tcp_port,
            interserver_http_port: new.interserver_http_port,
            remote_servers: new.remote_servers,
            keepers: new.keepers,
            data_path: new.data_path,
            generation: new.generation,
        }
    }
}

/// Configuration for a ClickHouse keeper
#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct KeeperConfig {
    /// Logging settings
    pub logger: LogConfig,
    /// Address the keeper is listening on
    pub listen_host: Ipv6Addr,
    /// Port for TCP connections
    pub tcp_port: u16,
    /// Unique ID for this keeper node
    pub server_id: v1::keeper::KeeperId,
    /// Directory for coordination logs
    #[schemars(schema_with = "path_schema")]
    pub log_storage_path: Utf8PathBuf,
    /// Directory for coordination snapshot storage
    #[schemars(schema_with = "path_schema")]
    pub snapshot_storage_path: Utf8PathBuf,
    /// Internal coordination settings
    pub coordination_settings: KeeperCoordinationSettings,
    /// Settings for each server in the keeper cluster
    pub raft_config: v1::config::RaftServers,
    /// Directory for all files generated by ClickHouse itself
    #[schemars(schema_with = "path_schema")]
    pub datastore_path: Utf8PathBuf,
    /// A unique identifier for the configuration generation.
    pub generation: Generation,
}

impl From<KeeperConfig> for v1::config::KeeperConfig {
    fn from(new: KeeperConfig) -> Self {
        v1::config::KeeperConfig {
            logger: new
                .logger
                .into_v1(&new.datastore_path, v1::config::NodeType::Keeper),
            listen_host: new.listen_host,
            tcp_port: new.tcp_port,
            server_id: new.server_id,
            log_storage_path: new.log_storage_path,
            snapshot_storage_path: new.snapshot_storage_path,
            coordination_settings: new.coordination_settings.into(),
            raft_config: new.raft_config,
            datastore_path: new.datastore_path,
            generation: new.generation,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct LogConfig {
    pub level: LogLevel,
}

impl LogConfig {
    /// Convert to the v1 representation, synthesizing log paths from the
    /// owning config's directory layout. v1 carries file-based logger
    /// settings that v4 no longer publishes.
    pub fn into_v1(
        self,
        datastore_path: &Utf8PathBuf,
        node_type: v1::config::NodeType,
    ) -> v1::config::LogConfig {
        let prefix = match node_type {
            v1::config::NodeType::Server => "clickhouse",
            v1::config::NodeType::Keeper => "clickhouse-keeper",
        };
        let logs = datastore_path.join("log");
        v1::config::LogConfig {
            level: self.level.into(),
            log: logs.join(format!("{prefix}.log")),
            errorlog: logs.join(format!("{prefix}.err.log")),
            size: 100,
            count: 1,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct KeeperCoordinationSettings {
    pub operation_timeout_ms: u32,
    pub session_timeout_ms: u32,
    pub raft_logs_level: LogLevel,
}

impl From<KeeperCoordinationSettings>
    for v1::config::KeeperCoordinationSettings
{
    fn from(new: KeeperCoordinationSettings) -> Self {
        v1::config::KeeperCoordinationSettings {
            operation_timeout_ms: new.operation_timeout_ms,
            session_timeout_ms: new.session_timeout_ms,
            raft_logs_level: new.raft_logs_level.into(),
        }
    }
}

#[derive(
    Debug, Clone, Default, PartialEq, Eq, JsonSchema, Serialize, Deserialize,
)]
#[serde(rename_all = "snake_case")]
pub enum LogLevel {
    Trace,
    Debug,
    #[default]
    Information,
}

impl From<LogLevel> for v1::config::LogLevel {
    fn from(new: LogLevel) -> Self {
        match new {
            LogLevel::Trace => v1::config::LogLevel::Trace,
            LogLevel::Debug => v1::config::LogLevel::Debug,
            // `Information` is new in v4; map back to Trace for v1 clients.
            LogLevel::Information => v1::config::LogLevel::Trace,
        }
    }
}
