// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Keeper-specific types for version `LOG_TO_CONSOLE` of the ClickHouse
//! Admin Keeper API.

use super::config::{LogConfig, LogLevel};
use crate::v1;
use camino::Utf8PathBuf;
use omicron_common::api::external::Generation;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::net::Ipv6Addr;

use v1::config::path_schema;

/// The top most type for configuring clickhouse-servers via
/// clickhouse-admin-keeper-api
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct KeeperConfigurableSettings {
    /// A unique identifier for the configuration generation.
    pub generation: Generation,
    /// Configurable settings for a ClickHouse keeper node.
    pub settings: KeeperSettings,
}

impl From<v1::keeper::KeeperConfigurableSettings>
    for KeeperConfigurableSettings
{
    fn from(old: v1::keeper::KeeperConfigurableSettings) -> Self {
        Self { generation: old.generation, settings: old.settings.into() }
    }
}

/// Configurable settings for a ClickHouse keeper node.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub struct KeeperSettings {
    /// Directory for the generated keeper configuration XML file
    #[schemars(schema_with = "path_schema")]
    pub config_dir: Utf8PathBuf,
    /// Unique ID of the keeper node
    pub id: v1::keeper::KeeperId,
    /// ID and host of each server in the keeper cluster
    pub raft_servers: Vec<v1::config::RaftServerSettings>,
    /// Directory for all files generated by ClickHouse itself
    #[schemars(schema_with = "path_schema")]
    pub datastore_path: Utf8PathBuf,
    /// Address the keeper is listening on
    pub listen_addr: Ipv6Addr,
    /// Logger configuration
    pub logger: LogConfig,
}

impl From<v1::keeper::KeeperSettings> for KeeperSettings {
    fn from(old: v1::keeper::KeeperSettings) -> Self {
        Self {
            config_dir: old.config_dir,
            id: old.id,
            raft_servers: old.raft_servers,
            datastore_path: old.datastore_path,
            listen_addr: old.listen_addr,
            logger: LogConfig::new(LogLevel::default()),
        }
    }
}

// While we generally use "Config", in this case we use "Conf"
// as it is the four letter word command we are invoking:
// `clickhouse keeper-client --q conf`
/// Keeper configuration information
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub struct KeeperConf {
    /// Unique server id, each participant of the ClickHouse Keeper cluster must
    /// have a unique number (1, 2, 3, and so on).
    pub server_id: v1::keeper::KeeperId,
    /// Whether Ipv6 is enabled.
    pub enable_ipv6: bool,
    /// Port for a client to connect.
    pub tcp_port: u16,
    /// Allow list of 4lw commands.
    pub four_letter_word_allow_list: String,
    /// Max size of batch in requests count before it will be sent to RAFT.
    pub max_requests_batch_size: u64,
    /// Min timeout for client session (ms).
    pub min_session_timeout_ms: u64,
    /// Max timeout for client session (ms).
    pub session_timeout_ms: u64,
    /// Timeout for a single client operation (ms).
    pub operation_timeout_ms: u64,
    /// How often ClickHouse Keeper checks for dead sessions and removes them (ms).
    pub dead_session_check_period_ms: u64,
    /// How often a ClickHouse Keeper leader will send heartbeats to followers (ms).
    pub heart_beat_interval_ms: u64,
    /// If the follower does not receive a heartbeat from the leader in this interval,
    /// then it can initiate leader election. Must be less than or equal to
    /// election_timeout_upper_bound_ms. Ideally they shouldn't be equal.
    pub election_timeout_lower_bound_ms: u64,
    /// If the follower does not receive a heartbeat from the leader in this interval,
    /// then it must initiate leader election.
    pub election_timeout_upper_bound_ms: u64,
    /// How many coordination log records to store before compaction.
    pub reserved_log_items: u64,
    /// How often ClickHouse Keeper will create new snapshots
    /// (in the number of records in logs).
    pub snapshot_distance: u64,
    /// Allow to forward write requests from followers to the leader.
    pub auto_forwarding: bool,
    /// Wait to finish internal connections and shutdown (ms).
    pub shutdown_timeout: u64,
    /// If the server doesn't connect to other quorum participants in the specified
    /// timeout it will terminate (ms).
    pub startup_timeout: u64,
    /// Text logging level about coordination (trace, debug, and so on).
    pub raft_logs_level: LogLevel,
    /// How many snapshots to keep.
    pub snapshots_to_keep: u64,
    /// How many log records to store in a single file.
    pub rotate_log_storage_interval: u64,
    /// Threshold when leader considers follower as stale and sends the snapshot
    /// to it instead of logs.
    pub stale_log_gap: u64,
    /// When the node became fresh.
    pub fresh_log_gap: u64,
    /// Max size in bytes of batch of requests that can be sent to RAFT.
    pub max_requests_batch_bytes_size: u64,
    /// Maximum number of requests that can be in queue for processing.
    pub max_request_queue_size: u64,
    /// Max size of batch of requests to try to get before proceeding with RAFT.
    /// Keeper will not wait for requests but take only requests that are already
    /// in the queue.
    pub max_requests_quick_batch_size: u64,
    /// Whether to execute read requests as writes through whole RAFT consesus with
    /// similar speed.
    pub quorum_reads: bool,
    /// Whether to call fsync on each change in RAFT changelog.
    pub force_sync: bool,
    /// Whether to write compressed coordination logs in ZSTD format.
    pub compress_logs: bool,
    /// Whether to write compressed snapshots in ZSTD format (instead of custom LZ4).
    pub compress_snapshots_with_zstd_format: bool,
    /// How many times we will try to apply configuration change (add/remove server)
    /// to the cluster.
    pub configuration_change_tries_count: u64,
    /// If connection to a peer is silent longer than this limit * (heartbeat interval),
    /// we re-establish the connection.
    pub raft_limits_reconnect_limit: u64,
    /// Path to coordination logs, just like ZooKeeper it is best to store logs
    /// on non-busy nodes.
    #[schemars(schema_with = "path_schema")]
    pub log_storage_path: Utf8PathBuf,
    /// Name of disk used for logs.
    pub log_storage_disk: String,
    /// Path to coordination snapshots.
    #[schemars(schema_with = "path_schema")]
    pub snapshot_storage_path: Utf8PathBuf,
    /// Name of disk used for storage.
    pub snapshot_storage_disk: String,
}

impl From<KeeperConf> for v1::keeper::KeeperConf {
    fn from(new: KeeperConf) -> Self {
        v1::keeper::KeeperConf {
            server_id: new.server_id,
            enable_ipv6: new.enable_ipv6,
            tcp_port: new.tcp_port,
            four_letter_word_allow_list: new.four_letter_word_allow_list,
            max_requests_batch_size: new.max_requests_batch_size,
            min_session_timeout_ms: new.min_session_timeout_ms,
            session_timeout_ms: new.session_timeout_ms,
            operation_timeout_ms: new.operation_timeout_ms,
            dead_session_check_period_ms: new.dead_session_check_period_ms,
            heart_beat_interval_ms: new.heart_beat_interval_ms,
            election_timeout_lower_bound_ms: new
                .election_timeout_lower_bound_ms,
            election_timeout_upper_bound_ms: new
                .election_timeout_upper_bound_ms,
            reserved_log_items: new.reserved_log_items,
            snapshot_distance: new.snapshot_distance,
            auto_forwarding: new.auto_forwarding,
            shutdown_timeout: new.shutdown_timeout,
            startup_timeout: new.startup_timeout,
            raft_logs_level: new.raft_logs_level.into(),
            snapshots_to_keep: new.snapshots_to_keep,
            rotate_log_storage_interval: new.rotate_log_storage_interval,
            stale_log_gap: new.stale_log_gap,
            fresh_log_gap: new.fresh_log_gap,
            max_requests_batch_bytes_size: new.max_requests_batch_bytes_size,
            max_request_queue_size: new.max_request_queue_size,
            max_requests_quick_batch_size: new.max_requests_quick_batch_size,
            quorum_reads: new.quorum_reads,
            force_sync: new.force_sync,
            compress_logs: new.compress_logs,
            compress_snapshots_with_zstd_format: new
                .compress_snapshots_with_zstd_format,
            configuration_change_tries_count: new
                .configuration_change_tries_count,
            raft_limits_reconnect_limit: new.raft_limits_reconnect_limit,
            log_storage_path: new.log_storage_path,
            log_storage_disk: new.log_storage_disk,
            snapshot_storage_path: new.snapshot_storage_path,
            snapshot_storage_disk: new.snapshot_storage_disk,
        }
    }
}
