// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Server-specific types for version `LOG_TO_CONSOLE` of the ClickHouse
//! Admin Server and Single APIs.

use super::config::{LogConfig, LogLevel};
use crate::v1;
use camino::Utf8PathBuf;
use omicron_common::api::external::Generation;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::net::Ipv6Addr;

use v1::config::path_schema;

/// The top most type for configuring clickhouse-servers via
/// clickhouse-admin-server-api
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct ServerConfigurableSettings {
    /// A unique identifier for the configuration generation.
    pub generation: Generation,
    /// Configurable settings for a ClickHouse replica server node.
    pub settings: ServerSettings,
}

impl From<v1::server::ServerConfigurableSettings>
    for ServerConfigurableSettings
{
    fn from(old: v1::server::ServerConfigurableSettings) -> Self {
        Self { generation: old.generation, settings: old.settings.into() }
    }
}

/// Configurable settings for a ClickHouse replica server node.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub struct ServerSettings {
    /// Directory for the generated server configuration XML file
    #[schemars(schema_with = "path_schema")]
    pub config_dir: Utf8PathBuf,
    /// Unique ID of the server node
    pub id: v1::server::ServerId,
    /// Directory for all files generated by ClickHouse itself
    #[schemars(schema_with = "path_schema")]
    pub datastore_path: Utf8PathBuf,
    /// Address the server is listening on
    pub listen_addr: Ipv6Addr,
    /// Addresses for each of the individual nodes in the Keeper cluster
    pub keepers: Vec<v1::config::ClickhouseHost>,
    /// Addresses for each of the individual replica servers
    pub remote_servers: Vec<v1::config::ClickhouseHost>,
    /// Logger configuration
    pub logger: LogConfig,
}

impl From<v1::server::ServerSettings> for ServerSettings {
    fn from(old: v1::server::ServerSettings) -> Self {
        Self {
            config_dir: old.config_dir,
            id: old.id,
            datastore_path: old.datastore_path,
            listen_addr: old.listen_addr,
            keepers: old.keepers,
            remote_servers: old.remote_servers,
            logger: LogConfig::new(LogLevel::default()),
        }
    }
}
