-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM network_interface] WHERE constraint_name = 'transit_ips_require_ip_address' AND validated = true)),'true','Schema change verification failed: constraint transit_ips_require_ip_address not found on table network_interface') AS BOOL);
