-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'fm_case' AND index_name = 'lookup_fm_cases_for_sitrep')),'true','Schema change verification failed: index lookup_fm_cases_for_sitrep on table fm_case does not exist') AS BOOL);
