-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'inv_zpool' AND index_name = 'inv_zpool_by_id_and_time')),'true','Schema change verification failed: index inv_zpool_by_id_and_time on table inv_zpool does not exist') AS BOOL);
