-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'sled_resource_vmm' AND index_name = 'single_vmm_reservation_per_state')),'true','Schema change verification failed: index single_vmm_reservation_per_state on table sled_resource_vmm does not exist') AS BOOL);
