-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'volume_repair' AND index_name = 'lookup_volume_repair_by_repair_id')),'true','Schema change verification failed: index lookup_volume_repair_by_repair_id on table volume_repair does not exist') AS BOOL);
