-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'region_replacement_step' AND index_name = 'step_time_order')),'true','Schema change verification failed: index step_time_order on table region_replacement_step does not exist') AS BOOL);
