// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Configuration types shared across ClickHouse Admin APIs.

use super::keeper::KeeperId;
use super::server::ServerId;
use camino::Utf8PathBuf;
use omicron_common::api::external::Generation;
use schemars::{
    JsonSchema,
    r#gen::SchemaGenerator,
    schema::{Schema, SchemaObject},
};
use serde::{Deserialize, Serialize};
use std::net::{Ipv4Addr, Ipv6Addr};

// Used for schemars to be able to be used with camino:
// See https://github.com/camino-rs/camino/issues/91#issuecomment-2027908513
pub fn path_schema(generator: &mut SchemaGenerator) -> Schema {
    let mut schema: SchemaObject = <String>::json_schema(generator).into();
    schema.format = Some("Utf8PathBuf".to_owned());
    schema.into()
}

/// Result after generating a configuration file
#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GenerateConfigResult {
    Replica(ReplicaConfig),
    Keeper(KeeperConfig),
}

/// Configuration for a ClickHouse replica server
#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct ReplicaConfig {
    /// Logging settings
    pub logger: LogConfig,
    /// Parameter substitutions for replicated tables
    pub macros: Macros,
    /// Address the server is listening on
    pub listen_host: Ipv6Addr,
    /// Port for HTTP connections
    pub http_port: u16,
    /// Port for TCP connections
    pub tcp_port: u16,
    /// Port for interserver HTTP connections
    pub interserver_http_port: u16,
    /// Configuration of clusters used by the Distributed table engine and bythe cluster
    /// table function
    pub remote_servers: RemoteServers,
    /// Contains settings that allow ClickHouse servers to interact with a Keeper cluster
    pub keepers: KeeperConfigsForReplica,
    /// Directory for all files generated by ClickHouse itself
    #[schemars(schema_with = "path_schema")]
    pub data_path: Utf8PathBuf,
    /// A unique identifier for the configuration generation.
    pub generation: Generation,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct Macros {
    pub shard: u64,
    pub replica: ServerId,
    pub cluster: String,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct RemoteServers {
    pub cluster: String,
    pub secret: String,
    pub replicas: Vec<ServerNodeConfig>,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct KeeperConfigsForReplica {
    pub nodes: Vec<KeeperNodeConfig>,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    Deserialize,
    PartialOrd,
    Ord,
    Serialize,
    JsonSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum ClickhouseHost {
    Ipv6(Ipv6Addr),
    Ipv4(Ipv4Addr),
    DomainName(String),
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct KeeperNodeConfig {
    pub host: ClickhouseHost,
    pub port: u16,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct ServerNodeConfig {
    pub host: ClickhouseHost,
    pub port: u16,
}

pub enum NodeType {
    Server,
    Keeper,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct LogConfig {
    pub level: LogLevel,
    #[schemars(schema_with = "path_schema")]
    pub log: Utf8PathBuf,
    #[schemars(schema_with = "path_schema")]
    pub errorlog: Utf8PathBuf,
    pub size: u16,
    pub count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct KeeperCoordinationSettings {
    pub operation_timeout_ms: u32,
    pub session_timeout_ms: u32,
    pub raft_logs_level: LogLevel,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct RaftServers {
    pub servers: Vec<RaftServerConfig>,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct RaftServerSettings {
    pub id: KeeperId,
    pub host: ClickhouseHost,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct RaftServerConfig {
    pub id: KeeperId,
    pub hostname: ClickhouseHost,
    pub port: u16,
}

/// Configuration for a ClickHouse keeper
#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
pub struct KeeperConfig {
    /// Logging settings
    pub logger: LogConfig,
    /// Address the keeper is listening on
    pub listen_host: Ipv6Addr,
    /// Port for TCP connections
    pub tcp_port: u16,
    /// Unique ID for this keeper node
    pub server_id: KeeperId,
    /// Directory for coordination logs
    #[schemars(schema_with = "path_schema")]
    pub log_storage_path: Utf8PathBuf,
    /// Directory for coordination snapshot storage
    #[schemars(schema_with = "path_schema")]
    pub snapshot_storage_path: Utf8PathBuf,
    /// Internal coordination settings
    pub coordination_settings: KeeperCoordinationSettings,
    /// Settings for each server in the keeper cluster
    pub raft_config: RaftServers,
    /// Directory for all files generated by ClickHouse itself
    #[schemars(schema_with = "path_schema")]
    pub datastore_path: Utf8PathBuf,
    /// A unique identifier for the configuration generation.
    pub generation: Generation,
}

#[derive(Debug, Clone, PartialEq, Eq, JsonSchema, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LogLevel {
    Trace,
    Debug,
}
