/*!
 * Interface for making API requests to the Oxide control plane at large (OXC)
 * from within the control plane
 *
 * This should be replaced with a client generated from the OpenAPI spec
 * generated by the server.
 */

use crate::api_error::ApiError;
use crate::api_model::ApiDiskRuntimeState;
use crate::api_model::ApiInstanceRuntimeState;
use crate::api_model::ApiSledAgentStartupInfo;
use crate::http_client::HttpClient;
use http::Method;
use hyper::Body;
use slog::Logger;
use std::net::SocketAddr;
use uuid::Uuid;

/** Client for an OXC instance */
pub struct Client {
    /** underlying HTTP client */
    client: HttpClient,
}

impl Client {
    /**
     * Create a new OXC client to make requests to the OXC instance at
     * `server_addr`.
     */
    pub fn new(server_addr: SocketAddr, log: Logger) -> Client {
        Client {
            client: HttpClient::new("controller", server_addr, log),
        }
    }

    /**
     * Publish information about a sled agent's startup.
     */
    pub async fn notify_sled_agent_online(
        &self,
        id: Uuid,
        info: ApiSledAgentStartupInfo,
    ) -> Result<(), ApiError> {
        let path = format!("/sled_agents/{}", id);
        let body = Body::from(serde_json::to_string(&info).unwrap());
        self.client.request(Method::POST, path.as_str(), body).await.map(|_| ())
    }

    /**
     * Publish an updated runtime state for an Instance.
     */
    pub async fn notify_instance_updated(
        &self,
        id: &Uuid,
        new_runtime_state: &ApiInstanceRuntimeState,
    ) -> Result<(), ApiError> {
        let path = format!("/instances/{}", id);
        let body =
            Body::from(serde_json::to_string(new_runtime_state).unwrap());
        self.client.request(Method::PUT, path.as_str(), body).await.map(|_| ())
    }

    /**
     * Publish an updated runtime state for a Disk.
     */
    pub async fn notify_disk_updated(
        &self,
        id: &Uuid,
        new_state: &ApiDiskRuntimeState,
    ) -> Result<(), ApiError> {
        let path = format!("/disks/{}", id);
        let body = Body::from(serde_json::to_string(new_state).unwrap());
        self.client.request(Method::PUT, path.as_str(), body).await.map(|_| ())
    }
}
