-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'oximeter' AND index_name = 'list_non_expunged_oximeter')),'true','Schema change verification failed: index list_non_expunged_oximeter on table oximeter does not exist') AS BOOL);
