// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Interface for making requests to the wicketd commissioning API.

progenitor::generate_api!(
    spec = "../../openapi/wicketd-commission/wicketd-commission-latest.json",
    interface = Positional,
    inner_type = slog::Logger,
    pre_hook = (|log: &slog::Logger, request: &reqwest::Request| {
        slog::debug!(log, "client request";
            "method" => %request.method(),
            "uri" => %request.url(),
            "body" => ?&request.body(),
        );
    }),
    post_hook = (|log: &slog::Logger, result: &Result<_, _>| {
        slog::debug!(log, "client response"; "result" => ?result);
    }),
    derives = [schemars::JsonSchema],
    crates = {
        "iddqd" = "*",
        "omicron-uuid-kinds" = "*",
        "oxnet" = "0.1.0",
    },
    replace = {
        AllowedSourceIps = wicketd_commission_types_versions::latest::rack_setup::AllowedSourceIps,
        BgpAuthKey = wicketd_commission_types_versions::latest::rack_setup::BgpAuthKey,
        BgpAuthKeyId = wicketd_commission_types_versions::latest::rack_setup::BgpAuthKeyId,
        BaseboardId = wicketd_commission_types_versions::latest::inventory::BaseboardId,
        BgpConfig = wicketd_commission_types_versions::latest::rack_setup::BgpConfig,
        BootstrapSled = wicketd_commission_types_versions::latest::inventory::BootstrapSled,
        Caboose = wicketd_commission_types_versions::latest::inventory::Caboose,
        CertificatePem = wicketd_commission_types_versions::latest::rack_setup::CertificatePem,
        CertificateUploadResponse = wicketd_commission_types_versions::latest::rack_setup::CertificateUploadResponse,
        ClearUpdateStateParams = wicketd_commission_types_versions::latest::update::ClearUpdateStateParams,
        ClearUpdateStateResponse = wicketd_commission_types_versions::latest::update::ClearUpdateStateResponse,
        CmisDatapath = wicketd_commission_types_versions::latest::inventory::CmisDatapath,
        CmisDatapathState = wicketd_commission_types_versions::latest::inventory::CmisDatapathState,
        CmisLaneStatus = wicketd_commission_types_versions::latest::inventory::CmisLaneStatus,
        FaultFlag = wicketd_commission_types_versions::latest::inventory::FaultFlag,
        FetchError = wicketd_commission_types_versions::latest::inventory::FetchError,
        GetBootstrapSledsResponse = wicketd_commission_types_versions::latest::inventory::GetBootstrapSledsResponse,
        IgnitionFaults = wicketd_commission_types_versions::latest::inventory::IgnitionFaults,
        Inventory = wicketd_commission_types_versions::latest::inventory::Inventory,
        InventoryParams = wicketd_commission_types_versions::latest::inventory::InventoryParams,
        IpRange = wicketd_commission_types_versions::latest::rack_setup::IpRange,
        Ipv4Range = wicketd_commission_types_versions::latest::rack_setup::Ipv4Range,
        Ipv6Range = wicketd_commission_types_versions::latest::rack_setup::Ipv6Range,
        LinkFec = wicketd_commission_types_versions::latest::rack_setup::LinkFec,
        LinkSpeed = wicketd_commission_types_versions::latest::rack_setup::LinkSpeed,
        LldpAdminStatus = wicketd_commission_types_versions::latest::rack_setup::LldpAdminStatus,
        LldpPortConfig = wicketd_commission_types_versions::latest::rack_setup::LldpPortConfig,
        LocationInfo = wicketd_commission_types_versions::latest::inventory::LocationInfo,
        ManualPortConfig = wicketd_commission_types_versions::latest::rack_setup::ManualPortConfig,
        MaxPathConfig = wicketd_commission_types_versions::latest::rack_setup::MaxPathConfig,
        PowerState = wicketd_commission_types_versions::latest::inventory::PowerState,
        PrivateKeyPem = wicketd_commission_types_versions::latest::rack_setup::PrivateKeyPem,
        PutRecoveryUserPasswordHash = wicketd_commission_types_versions::latest::rack_setup::PutRecoveryUserPasswordHash,
        PutRssUserConfigInsensitive = wicketd_commission_types_versions::latest::rack_setup::PutRssUserConfigInsensitive,
        RackOperationStatus = wicketd_commission_types_versions::latest::rack_setup::RackOperationStatus,
        ReceiverPower = wicketd_commission_types_versions::latest::inventory::ReceiverPower,
        RepositoryDescription = wicketd_commission_types_versions::latest::update::RepositoryDescription,
        RotImageError = wicketd_commission_types_versions::latest::inventory::RotImageError,
        RotImageValidity = wicketd_commission_types_versions::latest::inventory::RotImageValidity,
        RotInfo = wicketd_commission_types_versions::latest::inventory::RotInfo,
        RotSlot = wicketd_commission_types_versions::latest::inventory::RotSlot,
        RotSlotInfo = wicketd_commission_types_versions::latest::inventory::RotSlotInfo,
        RotStage0Info = wicketd_commission_types_versions::latest::inventory::RotStage0Info,
        RouteConfig = wicketd_commission_types_versions::latest::rack_setup::RouteConfig,
        RouterLifetimeConfig = wicketd_commission_types_versions::latest::rack_setup::RouterLifetimeConfig,
        RssStepInfo = wicketd_commission_types_versions::latest::rack_setup::RssStepInfo,
        RunningProgress = wicketd_commission_types_versions::latest::update::RunningProgress,
        SetBgpAuthKeyStatus = wicketd_commission_types_versions::latest::rack_setup::SetBgpAuthKeyStatus,
        Sff8636LaneFaults = wicketd_commission_types_versions::latest::inventory::Sff8636LaneFaults,
        SlotCaboose = wicketd_commission_types_versions::latest::inventory::SlotCaboose,
        SpIdentifier = wicketd_commission_types_versions::latest::inventory::SpIdentifier,
        SpIgnitionInfo = wicketd_commission_types_versions::latest::inventory::SpIgnitionInfo,
        SpInfo = wicketd_commission_types_versions::latest::inventory::SpInfo,
        SpStateInfo = wicketd_commission_types_versions::latest::inventory::SpStateInfo,
        SpType = wicketd_commission_types_versions::latest::inventory::SpType,
        Stage0Caboose = wicketd_commission_types_versions::latest::inventory::Stage0Caboose,
        SpUpdateProgress = wicketd_commission_types_versions::latest::update::SpUpdateProgress,
        StartUpdateOptions = wicketd_commission_types_versions::latest::update::StartUpdateOptions,
        StartUpdateParams = wicketd_commission_types_versions::latest::update::StartUpdateParams,
        StepOutcome = wicketd_commission_types_versions::latest::update::StepOutcome,
        StepProgress = wicketd_commission_types_versions::latest::update::StepProgress,
        SwitchSlot = wicketd_commission_types_versions::latest::inventory::SwitchSlot,
        SwitchTransceivers = wicketd_commission_types_versions::latest::inventory::SwitchTransceivers,
        Transceiver = wicketd_commission_types_versions::latest::inventory::Transceiver,
        TransceiverDatapath = wicketd_commission_types_versions::latest::inventory::TransceiverDatapath,
        TransceiverMonitors = wicketd_commission_types_versions::latest::inventory::TransceiverMonitors,
        TransceiverPower = wicketd_commission_types_versions::latest::inventory::TransceiverPower,
        TransceiverPowerMode = wicketd_commission_types_versions::latest::inventory::TransceiverPowerMode,
        TransceiverStatus = wicketd_commission_types_versions::latest::inventory::TransceiverStatus,
        TransceiverVendor = wicketd_commission_types_versions::latest::inventory::TransceiverVendor,
        TxEqConfig = wicketd_commission_types_versions::latest::rack_setup::TxEqConfig,
        UnmatchedBootstrapPeer = wicketd_commission_types_versions::latest::inventory::UnmatchedBootstrapPeer,
        UpdateProgress = wicketd_commission_types_versions::latest::update::UpdateProgress,
        UpdateState = wicketd_commission_types_versions::latest::update::UpdateState,
        UpdateStep = wicketd_commission_types_versions::latest::update::UpdateStep,
        UpdateTargets = wicketd_commission_types_versions::latest::update::UpdateTargets,
        UpdateStepStatus = wicketd_commission_types_versions::latest::update::UpdateStepStatus,
        UserSpecifiedBgpPeerConfig = wicketd_commission_types_versions::latest::rack_setup::UserSpecifiedBgpPeerConfig,
        UserSpecifiedImportExportPolicy = wicketd_commission_types_versions::latest::rack_setup::UserSpecifiedImportExportPolicy,
        UserSpecifiedPortConfig = wicketd_commission_types_versions::latest::rack_setup::UserSpecifiedPortConfig,
        UserSpecifiedRackNetworkConfig = wicketd_commission_types_versions::latest::rack_setup::UserSpecifiedRackNetworkConfig,
        UserSpecifiedRouterPeerAddr = wicketd_commission_types_versions::latest::rack_setup::UserSpecifiedRouterPeerAddr,
        UserSpecifiedUplinkAddressConfig = wicketd_commission_types_versions::latest::rack_setup::UserSpecifiedUplinkAddressConfig,
    },
);

pub type ClientError = crate::Error<crate::types::Error>;
