-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'silo_user' AND index_name = 'lookup_silo_user_by_silo_and_user_name')),'true','Schema change verification failed: index lookup_silo_user_by_silo_and_user_name on table silo_user does not exist') AS BOOL);
