// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! # [`Target`] Examples
//!
//! ```rust
//! # // Rename the types crate so the doctests can refer to the public
//! # // `oximeter` crate, not the private impl.
//! # extern crate oximeter_types as oximeter;
//! # use oximeter_macro_impl::*;
//! use oximeter::{traits::Target, types::FieldType};
//! use uuid::Uuid;
//!
//! #[derive(Target)]
//! struct VirtualMachine {
//!     name: String,
//!     id: Uuid,
//! }
//!
//! let vm = VirtualMachine { name: String::from("a-name"), id: Uuid::new_v4() };
//!
//! // The "name" of the target is the struct name in snake_case.
//! assert_eq!(vm.name(), "virtual_machine");
//!
//! // The field names are the names of the struct field, in order.
//! assert_eq!(vm.field_names()[0], "name");
//!
//! // Each field has a specified type and value
//! assert_eq!(vm.field_types()[1], FieldType::Uuid);
//! assert_eq!(vm.field_values()[0], "a-name".into());
//! ```
//!
//! Targets may implement other methods, if the user wishes, but the fields must be one of the
//! supported types.
//!
//! ```compile_fail
//! # // Rename the types crate so the doctests can refer to the public
//! # // `oximeter` crate, not the private impl.
//! # extern crate oximeter_types as oximeter;
//! # use oximeter_macro_impl::*;
//! #[derive(oximeter::Target)]
//! struct Bad {
//!     bad: f64,
//! }
//! ```
//!
//! **Important:** Typically, you should define your timeseries schema through
//! the TOML format described in [the crate documentation](crate), and use the
//! code generated by the `use_timeseries` macro. However, if you need to handle
//! custom sampling logic and must define custom field definitions not published
//! as part of the target schema, you can implement this trait.
//!
//! # [`Metric`] Examples
//!
//! ```rust
//! # // Rename the types crate so the doctests can refer to the public
//! # // `oximeter` crate, not the private impl.
//! # extern crate oximeter_types as oximeter;
//! # use oximeter_macro_impl::*;
//! use chrono::Utc;
//! use oximeter::Metric;
//!
//! // A gauge with a floating-point value.
//! #[derive(Metric)]
//! struct MyMetric {
//!     name: String,
//!     datum: f64,
//! }
//!
//! let met = MyMetric { name: "name".into(), datum: 0.0 };
//! assert_eq!(met.datum_type(), oximeter::DatumType::F64);
//! let measurement = met.measure(Utc::now());
//! assert!(measurement.start_time().is_none());
//! assert_eq!(measurement.datum(), &oximeter::Datum::F64(0.0));
//! ```
//!
//! A compiler error will be generated if the attribute is applied to a struct
//! whose fields are of an unsupported type.
//!
//! ```compile_fail
//! # // Rename the types crate so the doctests can refer to the public
//! # // `oximeter` crate, not the private impl.
//! # extern crate oximeter_types as oximeter;
//! # use oximeter_macro_impl::*;
//! #[derive(Metric)]
//! pub struct BadType {
//!     field: f32,
//! }
//! ```
//!
//! # [`Producer`] Examples
//!
//! ```rust
//! # // Rename the types crate so the doctests can refer to the public
//! # // `oximeter` crate, not the private impl.
//! # extern crate oximeter_types as oximeter;
//! # use oximeter_macro_impl::*;
//! use oximeter::{Datum, MetricsError, Metric, Producer, Target};
//! use oximeter::types::{Measurement, Sample, Cumulative};
//!
//! // The `Server` target identifies some HTTP service being monitored.
//! #[derive(Clone, Debug, Target)]
//! pub struct Server {
//!     pub name: String,
//! }
//!
//! // The `RequestCount` metric describes the cumulative count of requests the
//! // server has organized by their routes, the HTTP method, and the response
//! // code.
//! #[derive(Clone, Debug, Metric)]
//! pub struct RequestCount {
//!     route: String,
//!     method: String,
//!     response_code: i64,
//!     #[datum]
//!     count: Cumulative<i64>
//! }
//!
//! fn route_handler(_route: &str, _method: &str) -> i64 {
//!     // Actually handle the request
//!     200
//! }
//!
//! // The `RequestCounter` type implements the `Producer` trait, to generate
//! // samples of the target/metric being monitored.
//! #[derive(Debug, Clone)]
//! pub struct RequestCounter {
//!     target: Server,
//!     metric: RequestCount,
//! }
//!
//! impl RequestCounter {
//!     pub fn new(target: &Server, metric: &RequestCount) -> Self {
//!         Self {
//!             target: target.clone(),
//!             metric: metric.clone(),
//!         }
//!     }
//!
//!     pub fn bump(&mut self) {
//!         self.metric.datum_mut().increment();
//!     }
//! }
//!
//! impl Producer for RequestCounter {
//!     fn produce(&mut self) -> Result<Box<dyn Iterator<Item = Sample>>, MetricsError> {
//!         let sample = Sample::new(&self.target, &self.metric).unwrap();
//!         Ok(Box::new(vec![sample].into_iter()))
//!     }
//! }
//!
//! fn main() {
//!     let server = Server { name: "Nexus".to_string() };
//!
//!     let request_count = RequestCount {
//!         route: "/".to_string(),
//!         method: "HEAD".to_string(),
//!         response_code: 200,
//!         count: Cumulative::new(0),
//!     };
//!     let mut producer = RequestCounter::new(&server, &request_count);
//!
//!     // No requests yet, there should be zero samples
//!     let sample = producer.produce().unwrap().next().unwrap();
//!     let datum = sample.measurement.datum();
//!     match datum {
//!         Datum::CumulativeI64(d) => assert_eq!(d.value(), 0),
//!         _ => panic!("Expected a CumulativeI64 datum"),
//!     }
//!
//!     // await some request..
//!     let response_code = route_handler("/", "GET");
//!     if response_code == 200 {
//!         producer.bump();
//!     } // Handle other responses
//!
//!     // The incremented counter is reflected in the new sample.
//!     let sample = producer.produce().unwrap().next().unwrap();
//!     let datum = sample.measurement.datum();
//!     match datum {
//!         Datum::CumulativeI64(d) => assert_eq!(d.value(), 1),
//!         _ => panic!("Expected a CumulativeI64 datum"),
//!     }
//! }
//! ```

pub use oximeter_types_versions::latest::histogram::HistogramSupport;
pub use oximeter_types_versions::latest::traits::*;

// These tests live here instead of in `oximeter_types_versions` because
// `oximeter_macro_impl` expects to find a crate named `oximeter` that actually
// points to _this_ crate (`oximeter-types`).
//
// This is also why we have doc tests in this crate instead of more closely
// attached to the types in `oximeter-types-versions`; all the doc tests have a
// (hidden) `extern crate oximeter_types as oximeter;` at the top which allows
// the code emitted by `oximeter_macro_impl` to work.
#[cfg(test)]
mod tests {
    use crate::types;
    use crate::{
        Datum, DatumType, FieldType, FieldValue, Metric, MetricsError,
        Producer, Target,
    };
    use oximeter_macro_impl::{Metric, Target};
    use std::boxed::Box;

    #[derive(Debug, Clone, Target)]
    struct Targ {
        pub happy: bool,
        pub tid: i64,
    }

    #[derive(Debug, Clone, Metric)]
    struct Met {
        good: bool,
        id: i64,
        datum: i64,
    }

    #[derive(Debug, Clone)]
    struct Prod {
        pub target: Targ,
        pub metric: Met,
    }

    impl Producer for Prod {
        fn produce(
            &mut self,
        ) -> Result<Box<dyn Iterator<Item = types::Sample>>, MetricsError>
        {
            Ok(Box::new(
                vec![types::Sample::new(&self.target, &self.metric)?]
                    .into_iter(),
            ))
        }
    }

    #[test]
    fn test_target_trait() {
        let t = Targ { happy: false, tid: 2 };

        assert_eq!(t.name(), "targ");
        assert_eq!(t.field_names(), &["happy", "tid"]);
        assert_eq!(t.field_types(), &[FieldType::Bool, FieldType::I64]);
        assert_eq!(
            t.field_values(),
            &[FieldValue::Bool(false), FieldValue::I64(2)]
        );
    }

    #[test]
    fn test_metric_trait() {
        let m = Met { good: false, id: 2, datum: 0 };
        assert_eq!(m.name(), "met");
        assert_eq!(m.field_names(), &["good", "id"]);
        assert_eq!(m.field_types(), &[FieldType::Bool, FieldType::I64]);
        assert_eq!(
            m.field_values(),
            &[FieldValue::Bool(false), FieldValue::I64(2)]
        );
        assert_eq!(m.datum_type(), DatumType::I64);
        assert!(m.start_time().is_none());
    }

    #[test]
    fn test_producer_trait() {
        let t = Targ { happy: false, tid: 2 };
        let m = Met { good: false, id: 2, datum: 0 };
        let mut p = Prod { target: t.clone(), metric: m.clone() };
        let sample = p.produce().unwrap().next().unwrap();
        assert_eq!(
            sample.timeseries_name,
            format!("{}:{}", t.name(), m.name())
        );
        assert_eq!(sample.measurement.datum(), &Datum::I64(0));
        p.metric.datum += 10;
        let sample = p.produce().unwrap().next().unwrap();
        assert_eq!(sample.measurement.datum(), &Datum::I64(10));
    }
}
