-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'sled' AND column_name = 'sled_state')),'true','Schema change verification failed: column sled_state on table sled does not exist (backfill may not have completed)') AS BOOL);
