-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM inv_omicron_sled_config_zone_nic] WHERE constraint_name = 'at_least_one_ip_address' AND validated = true)),'true','Schema change verification failed: constraint at_least_one_ip_address not found on table inv_omicron_sled_config_zone_nic') AS BOOL);
