// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Fault management types.
//!
//! Of particular importance is the [`Sitrep`], which is the top-level data
//! structure containing fault management state.

pub mod ereport;

use chrono::{DateTime, Utc};
use omicron_uuid_kinds::{CollectionUuid, OmicronZoneUuid, SitrepUuid};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// A fault management situation report, or _sitrep_.
///
/// The sitrep is a data structure that represents a snapshot of the state of
/// the system as understood by the control plane's fault management subsystem.
/// At any point in time, a single sitrep is considered the "current" sitrep.
/// Each sitrep records a _parent sitrep ID_, which indicates the sitrep that
/// was current at the time that the sitrep was created.
/// A sitrep may only be made current if its parent is the current sitrep.
/// This ensures that there is a sequentially consistent history of sitreps.
/// The fault management subsystem only considers data from the current sitrep
/// when making decisions and diagnoses.
///
/// The sitrep, how it is represented in the database, and how the fault
/// management subsystem creates and interacts with sitreps, is described in
/// detail in [RFD 603](https://rfd.shared.oxide.computer/rfd/0603).
#[derive(Clone, Debug, Eq, PartialEq, JsonSchema, Deserialize, Serialize)]
pub struct Sitrep {
    /// Metadata describing this sitrep, when it was created, its parent sitrep
    /// ID, and which Nexus produced it.
    pub metadata: SitrepMetadata,
    // TODO(eliza): draw the rest of the sitrep
}

impl Sitrep {
    pub fn id(&self) -> SitrepUuid {
        self.metadata.id
    }

    pub fn parent_id(&self) -> Option<SitrepUuid> {
        self.metadata.parent_sitrep_id
    }
}

/// Metadata describing a sitrep.
///
/// This corresponds to the records stored in the `fm_sitrep` database table.
#[derive(Clone, Debug, Eq, PartialEq, JsonSchema, Deserialize, Serialize)]
pub struct SitrepMetadata {
    /// The ID of this sitrep.
    pub id: SitrepUuid,

    /// The ID of the parent sitrep.
    ///
    /// A sitrep's _parent_ is the sitrep that was current when the planning
    /// phase that produced that sitrep ran. The parent sitrep is a planning
    /// input that produced this sitrep.
    ///
    /// The parent sitrep ID is optional, because this sitrep _may_ be the first
    /// sitrep ever generated by the system. However, once a current sitrep has
    /// been set, no subsequent sitrep should be created without a parent.
    pub parent_sitrep_id: Option<SitrepUuid>,

    /// The ID of the inventory collection that was used as planning input to
    /// this sitrep.
    ///
    /// When generating a new sitrep, the fault manager should ensure that the
    /// inventory collection it uses as input is at least as new as the parent
    /// sitrep's inventory collection.
    pub inv_collection_id: CollectionUuid,

    /// The Omicron zone UUID of the Nexus that generated this sitrep.
    ///
    /// This is intended for debugging purposes.
    pub creator_id: OmicronZoneUuid,

    /// A human-readable (but mechanically generated) string describing the
    /// reason(s) this sitrep was created.
    ///
    /// This is intended for debugging purposes.
    pub comment: String,

    /// The time at which this sitrep was created.
    pub time_created: DateTime<Utc>,
}

/// An entry in the sitrep version history.
#[derive(Clone, Debug, Eq, PartialEq, JsonSchema, Deserialize, Serialize)]
pub struct SitrepVersion {
    pub id: SitrepUuid,
    pub version: u32,
    pub time_made_current: DateTime<Utc>,
}
