-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM bp_sled_metadata] WHERE constraint_name = 'update_disruption_policy_set_iff_evacuating' AND validated = true)),'true','Schema change verification failed: constraint update_disruption_policy_set_iff_evacuating not found on table bp_sled_metadata') AS BOOL);
