-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM region_snapshot_replacement] WHERE constraint_name = 'proper_replacement_fields' AND validated = true)),'true','Schema change verification failed: constraint proper_replacement_fields not found on table region_snapshot_replacement') AS BOOL);
