-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'console_session' AND index_name = 'lookup_console_by_creation')),'true','Schema change verification failed: index lookup_console_by_creation on table console_session does not exist') AS BOOL);
