-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'device_access_token' AND index_name = 'device_access_token_unique')),'true','Schema change verification failed: index device_access_token_unique on table device_access_token does not exist') AS BOOL);
