-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'region' AND index_name = 'lookup_regions_missing_ports')),'true','Schema change verification failed: index lookup_regions_missing_ports on table region does not exist') AS BOOL);
