# Tombi config to apply TOML autoformatting:
#
# * Keep Cargo.toml dependency lines sorted.
# * Standardize things like "" across our configs.
#
# We don't enable TOML linting in CI for now because there isn't a great way to
# maintain determinism in CI (we don't want `tombi lint` to suddenly start
# failing on main if we can avoid it):
#
# * For, say, the `[workspace.lints.clippy]` config, the clippy schema
#   (https://www.schemastore.org/cargo-lints-clippy.json) is not pinned to a
#   particular Rust version, and isn't fully up-to-date anyway.
# * We could vendor the correct schemas into this repo, but vendoring schemas
#   is ugly.
#
# It would be nice to figure out a solution to that in the future.

# Cargo supports TOML 1.1, under which tombi wraps > 80-column dependency lines
# into multiline inline tables. However, toml-cli in tools/ci_check_opte_ver.sh
# doesn't currently (as of 2026-08) support that syntax, so we restrict
# ourselves to TOML 1.0 here.
toml-version = "v1.0.0"

[files]
# This controls which files a bare `tombi format` applies to.
include = [
    "**/Cargo.toml",
    ".config/nextest.toml",
    ".config/tombi.toml",
]
# workspace-hack/Cargo.toml is generated by cargo-hakari, so we don't try and
# fight that here.
exclude = ["workspace-hack/Cargo.toml"]

[format.rules]
indent-width = 4
# By default, tombi 1.4.0 doesn't have a default line width. We set a line width
# of 80 to match the rest of this code base.
line-width = 80

# Ensure that dependency tables are sorted consistently in Cargo.toml.
[[schemas]]
toml-version = "v1.0.0"
# We don't actually use the JSON schema for validation right now, but tombi
# requires that a schema is specified in this section.
path = "tombi://www.schemastore.org/cargo.json"
include = ["**/Cargo.toml"]
# By default, tombi would sort most tables in Cargo.toml. We mostly care about
# dependency tables, though, so turn off sorting for the rest.
format.rules.array-values-order.enabled = false
format.rules.table-keys-order.enabled = false

[[schemas.overrides]]
targets = [
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "workspace.dependencies",
    "target.*.dependencies",
    "target.*.dev-dependencies",
    "target.*.build-dependencies",
]
format.rules.table-keys-order = "version-sort"
