-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'instance' AND column_name = 'boot_on_fault')),'true','Schema change verification failed: column boot_on_fault on table instance does not exist (backfill may not have completed)') AS BOOL);
