#
# SP simulator: example config file
#

#
# NOTE: for the test suite, all ports MUST be 0 (in order to bind to any
# available port) because the test suite will be running many servers
# concurrently.
#
[[simulated_sps.sidecar]]
serial_number = "SimSidecar0"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000000"

[[simulated_sps.sidecar.network_config]]
[simulated_sps.sidecar.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.network_config]]
[simulated_sps.sidecar.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.ereport_network_config]]
[simulated_sps.sidecar.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.ereport_network_config]]
[simulated_sps.sidecar.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.components]]
id = "dev-0"
device = "fake-tmp-sensor"
description = "FAKE temperature sensor 1"
capabilities = 0x2
presence = "Present"
sensors = [
    {name = "Southwest", kind = "Temperature", last_data.value = 41.7890625, last_data.timestamp = 1234 },
]

[[simulated_sps.sidecar.components]]
id = "dev-1"
device = "fake-tmp-sensor"
description = "FAKE temperature sensor 2"
capabilities = 0x2
presence = "Failed"
sensors = [
    { name = "South", kind = "Temperature", last_error.value = "DeviceError", last_error.timestamp = 1234 },
]

[[simulated_sps.sidecar.components]]
id = "ibc"
device = "bmr491"
description = "FAKE intermediate bus converter"
capabilities = 0x20
presence = "Present"

[simulated_sps.sidecar.components.vpd.pmbus]
mfr_id = "Flex"
mfr_model = "BMR4913203851"
mfr_revision = "R1C A"
mfr_location = "CB6"
mfr_date = "2023-02-25"
mfr_serial = "FP1C481050"

[simulated_sps.sidecar.ereport_config]
restart_id = "0d3e464a-666e-4687-976f-90e31238be8b"

[[simulated_sps.sidecar.ereport_config.ereports]]
task_name = "task_thermal_server"
task_gen = 1
uptime = 1235
k = "oxide.sidecar.thermal.sensor_read_error"
sensor = { id = "dev-1", device = "fake-tmp-sensor", location = "South", presence = "Failed" }
error = "DeviceError"

[[simulated_sps.sidecar]]
serial_number = "SimSidecar1"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000001"

[[simulated_sps.sidecar.network_config]]
[simulated_sps.sidecar.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.network_config]]
[simulated_sps.sidecar.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.ereport_network_config]]
[simulated_sps.sidecar.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.ereport_network_config]]
[simulated_sps.sidecar.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.sidecar.components]]
id = "ibc"
device = "bmr491"
description = "FAKE intermediate bus converter"
capabilities = 0x20
presence = "Present"

[simulated_sps.sidecar.components.vpd.pmbus]
mfr_id = "Flex"
mfr_model = "BMR4913203851"
mfr_revision = "R1C A"
mfr_location = "CB6"
mfr_date = "2023-02-26"
mfr_serial = "FP1C481051"

[[simulated_sps.gimlet]]
serial_number = "SimGimlet00"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000002"

[[simulated_sps.gimlet.network_config]]
[simulated_sps.gimlet.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.network_config]]
[simulated_sps.gimlet.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.ereport_network_config]]
[simulated_sps.gimlet.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.ereport_network_config]]
[simulated_sps.gimlet.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.components]]
id = "sp3-host-cpu"
device = "sp3-host-cpu"
description = "FAKE host cpu"
capabilities = 0
presence = "Present"
serial_console = "[::1]:0"

[[simulated_sps.gimlet.components]]
id = "dev-0"
device = "fake-tmp-sensor"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Failed"
sensors = [
    { name = "Southwest", kind = "Temperature", last_error.value = "DeviceError", last_error.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-1"
device = "tmp117"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Present"
vpd = { tmp11x = { id = 0x0117, eeprom1 = 0x0101, eeprom2 = 0x0102, eeprom3 = 0x0103 } }
sensors = [
    { name = "South", kind = "Temperature", last_data.value = 42.5625, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-2"
device = "tmp117"
description = "FAKE Southeast temperature sensor"
capabilities = 0x2
presence = "Present"
vpd = { tmp11x = { id = 0x0117, eeprom1 = 0x0201, eeprom2 = 0x0202, eeprom3 = 0x0203 } }
sensors = [
    { name = "Southeast", kind = "Temperature", last_data.value = 41.570313, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-6"
device = "at24csw080"
description = "FAKE U.2 Sharkfin A VPD"
capabilities = 0x0
presence = "Present"
vpd = { barcode = "0XV2:913-0000028:001:2SHRKFN1" }

[[simulated_sps.gimlet.components]]
id = "dev-7"
device = "max5970"
description = "FAKE U.2 Sharkfin A hot swap controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "V12_U2A_A0", kind = "Current", last_data.value = 0.45898438, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Current", last_data.value = 0.024414063, last_data.timestamp = 1234 },
    { name = "V12_U2A_A0", kind = "Voltage", last_data.value = 12.03125, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Voltage", last_data.value = 3.328125, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-8"
device = "nvme_bmc"
description = "FAKE U.2 A NVMe Basic Management Command"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "U2_N0", kind = "Temperature", last_data.value = 56.0, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-39"
device = "tmp451"
description = "FAKE T6 temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "t6", kind = "Temperature", last_data.value = 70.625, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-46"
device = "sbtsi"
description = "CPU temperature sensor"
capabilities = 2
presence = "Present"
sensors = [
    { name = "CPU", kind = "Temperature", last_data.value = 64.5, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-53"
device = "max31790"
description = "FAKE Fan controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "Southeast", kind = "Speed", last_data.value = 2607.0, last_data.timestamp = 1234 },
    { name = "Northeast", kind = "Speed", last_data.value = 2476.0, last_data.timestamp = 1234 },
    { name = "South", kind = "Speed", last_data.value = 2553.0, last_data.timestamp = 1234 },
    { name = "North", kind = "Speed", last_data.value = 2265.0, last_data.timestamp = 1234 },
    { name = "Southwest", kind = "Speed", last_data.value = 2649.0, last_data.timestamp = 1234 },
    { name = "Northwest", kind = "Speed", last_data.value = 2275.0, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "fan-tray-vpd"
device = "at24csw080"
description = "FAKE Fan tray VPD"
capabilities = 0x0
presence = "Present"

[simulated_sps.gimlet.components.vpd.sled_fan_tray]
identity = "0XV2:991-0000151:001:TST01234567"
vpd_board_identity = "0XV2:913-0000027:001:TST01234568"
fans = [
    "MPN1:SYD:9CRA0848P8G012:C:WWYY1SSS",
    "0XV1:1250000456:002:FAN01234569",
    "MPN1:ABC:ASDF-1000:032:123456789",
]

[[simulated_sps.gimlet.components]]
id = "ibc"
device = "bmr491"
description = "FAKE intermediate bus converter"
capabilities = 0x20
presence = "Present"

[simulated_sps.gimlet.components.vpd.pmbus]
mfr_id = "Flex"
mfr_model = "BMR4913203851"
mfr_revision = "R1C A"
mfr_location = "CB6"
mfr_date = "2023-02-27"
mfr_serial = "FP1C481052"

[simulated_sps.gimlet.ereport_config]
restart_id = "af1ebf85-36ba-4c31-bbec-b9825d6d9d8b"

[[simulated_sps.gimlet.ereport_config.ereports]]
task_name = "task_apollo_server"
task_gen = 13
uptime = 1233
k = "gov.nasa.apollo.o2_tanks.stir.begin"
message = "stirring the tanks"

[[simulated_sps.gimlet.ereport_config.ereports]]
task_name = "drv_ae35_server"
task_gen = 1
uptime = 1234
k = "io.discovery.ae35.fault"
message = "i've just picked up a fault in the AE-35 unit"
de = { scheme = "fmd", authority = { product-id = "HAL-9000-series computer", server-id = "HAL 9000"}, mod-name = "ae35-diagnosis" }
hours_to_failure = 72

[[simulated_sps.gimlet.ereport_config.ereports]]
task_name = "task_apollo_server"
task_gen = 13
uptime = 1237
k = "gov.nasa.apollo.fault"
message = "houston, we have a problem"
crew = ["Lovell", "Swigert", "Haise"]

[[simulated_sps.gimlet.ereport_config.ereports]]
task_name = "drv_thingy_server"
task_gen = 2
uptime = 1240
k = "flagrant_error"
computer = false

[[simulated_sps.gimlet.ereport_config.ereports]]
task_name = "task_latex_server"
task_gen = 1
uptime = 1245
k = "overfull_hbox"
badness  = 10000

[[simulated_sps.gimlet]]
serial_number = "SimGimlet01"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000003"

[[simulated_sps.gimlet.network_config]]
[simulated_sps.gimlet.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.network_config]]
[simulated_sps.gimlet.network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.ereport_network_config]]
[simulated_sps.gimlet.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.ereport_network_config]]
[simulated_sps.gimlet.ereport_network_config.simulated]
bind_addr = "[::1]:0"

[[simulated_sps.gimlet.components]]
id = "sp3-host-cpu"
device = "sp3-host-cpu"
description = "FAKE host cpu"
capabilities = 0
presence = "Present"
serial_console = "[::1]:0"


[[simulated_sps.gimlet.components]]
id = "dev-0"
device = "tmp117"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Present"
vpd = { tmp11x = { id = 0x0117, eeprom1 = 0x1001, eeprom2 = 0x1002, eeprom3 = 0x1003 } }
sensors = [
    { name = "Southwest", kind = "Temperature", last_data.value = 41.3629, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-1"
device = "tmp117"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Present"
vpd = { tmp11x = { id = 0x0117, eeprom1 = 0x1101, eeprom2 = 0x1102, eeprom3 = 0x1103 } }
sensors = [
    { name = "South", kind = "Temperature", last_data.value = 42.5625, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-2"
device = "tmp117"
description = "FAKE Southeast temperature sensor"
capabilities = 0x2
presence = "Present"
vpd = { tmp11x = { id = 0x0117, eeprom1 = 0x1201, eeprom2 = 0x1202, eeprom3 = 0x1203 } }
sensors = [
    { name = "Southeast", kind = "Temperature", last_data.value = 41.570313, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-6"
device = "at24csw080"
description = "FAKE U.2 Sharkfin A VPD"
capabilities = 0x0
presence = "Present"
vpd = { barcode = "0XV2:913-0000028:001:2SHRKFN2" }

[[simulated_sps.gimlet.components]]
id = "dev-7"
device = "max5970"
description = "FAKE U.2 Sharkfin A hot swap controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "V12_U2A_A0", kind = "Current", last_data.value = 0.41893438, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Current", last_data.value = 0.025614603, last_data.timestamp = 1234 },
    { name = "V12_U2A_A0", kind = "Voltage", last_data.value = 12.02914, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Voltage", last_data.value = 3.2618, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-8"
device = "nvme_bmc"
description = "FAKE U.2 A NVMe Basic Management Command"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "U2_N0", kind = "Temperature", last_data.value = 56.0, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-39"
device = "tmp451"
description = "FAKE T6 temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "t6", kind = "Temperature", last_data.value = 70.625, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-46"
device = "sbtsi"
description = "CPU temperature sensor"
capabilities = 2
presence = "Present"
sensors = [
    { name = "CPU", kind = "Temperature", last_data.value = 62.6, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-53"
device = "max31790"
description = "FAKE Fan controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "Southeast", kind = "Speed", last_data.value = 2510.0, last_data.timestamp = 1234 },
    { name = "Northeast", kind = "Speed", last_data.value = 2390.0, last_data.timestamp = 1234 },
    { name = "South", kind = "Speed", last_data.value = 2467.0, last_data.timestamp = 1234 },
    { name = "North", kind = "Speed", last_data.value = 2195.0, last_data.timestamp = 1234 },
    { name = "Southwest", kind = "Speed", last_data.value = 2680.0, last_data.timestamp = 1234 },
    { name = "Northwest", kind = "Speed", last_data.value = 2212.0, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "ibc"
device = "bmr491"
description = "FAKE intermediate bus converter"
capabilities = 0x20
presence = "Present"

[simulated_sps.gimlet.components.vpd.pmbus]
mfr_id = "Flex"
mfr_model = "BMR4913203851"
mfr_revision = "R1C A"
mfr_location = "CB6"
mfr_date = "2023-02-28"
mfr_serial = "FP1C481053"

[simulated_sps.gimlet.ereport_config]
restart_id = "55e30cc7-a109-492f-aca9-735ed725df3c"

[[simulated_sps.gimlet.ereport_config.ereports]]
task_name = "task_thermal_server"
task_gen = 1
uptime = 1233
class = "computer.oxide.gimlet.chassis_integrity.fault"
nosub_class = "chassis_integrity.cat_hair_detected"
message = "cat hair detected inside gimlet"
de = { scheme = "fmd", mod-name = "hubris-thermal-diagnosis", mod-version = "1.0", authority = { "product-id" = "oxide", server-id = "SimGimlet1" }}
certainty = 0x64
cat_hair_amount = 10000

#
# NOTE: for the test suite, the [log] section is ignored; sp-sim logs are rolled
# into the gateway logfile.
#
[log]
level = "debug"
mode = "stderr-terminal"
