// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use super::ActionRegistry;
use super::NexusActionContext;
use super::NexusSaga;
use super::SagaInitError;
use super::ACTION_GENERATE_ID;
use crate::app::sagas::declare_saga_actions;
use crate::external_api::params;
use nexus_db_queries::db::queries::vpc_subnet::InsertVpcSubnetError;
use nexus_db_queries::{authn, authz, db};
use omicron_common::api::external;
use oxnet::IpNet;
use oxnet::Ipv6Net;
use serde::Deserialize;
use serde::Serialize;
use steno::ActionError;
use steno::Node;
use uuid::Uuid;

// vpc subnet create saga: input parameters

#[derive(Debug, Deserialize, Serialize)]
pub(crate) struct Params {
    pub serialized_authn: authn::saga::Serialized,
    pub subnet_create: params::VpcSubnetCreate,
    pub ipv6_blocks: Vec<Ipv6Net>,
    pub authz_vpc: authz::Vpc,
    pub authz_system_router: authz::VpcRouter,
    pub custom_router: Option<authz::VpcRouter>,
}

// vpc subnet create saga: actions

declare_saga_actions! {
    vpc_subnet_create;
    VPC_SUBNET_CREATE_SUBNET -> "subnet" {
        + svsc_create_subnet
        - svsc_create_subnet_undo
    }
    VPC_SUBNET_CREATE_SYS_ROUTE -> "route" {
        + svsc_create_route
        - svsc_create_route_undo
    }
    VPC_SUBNET_CREATE_LINK_CUSTOM -> "output" {
        + svsc_link_custom
        - svsc_link_custom_undo
    }
    VPC_NOTIFY_RPW -> "no_result" {
        + svsc_notify_rpw
    }
}

// vpc subnet create saga: definition

/// Identical to [SagaVpcSubnetCreate::make_saga_dag], but using types
/// to identify that parameters do not need to be supplied as input.
pub fn create_dag(
    mut builder: steno::DagBuilder,
) -> Result<steno::Dag, SagaInitError> {
    builder.append(Node::action(
        "subnet_id",
        "GenerateVpcSubnetId",
        ACTION_GENERATE_ID.as_ref(),
    ));
    builder.append(Node::action(
        "route_id",
        "GenerateRouteId",
        ACTION_GENERATE_ID.as_ref(),
    ));

    builder.append(vpc_subnet_create_subnet_action());
    builder.append(vpc_subnet_create_sys_route_action());
    builder.append(vpc_subnet_create_link_custom_action());
    builder.append(vpc_notify_rpw_action());

    Ok(builder.build()?)
}

#[derive(Debug)]
pub(crate) struct SagaVpcSubnetCreate;
impl NexusSaga for SagaVpcSubnetCreate {
    const NAME: &'static str = "vpc-subnet-create";
    type Params = Params;

    fn register_actions(registry: &mut ActionRegistry) {
        vpc_subnet_create_register_actions(registry);
    }

    fn make_saga_dag(
        _params: &Self::Params,
        builder: steno::DagBuilder,
    ) -> Result<steno::Dag, super::SagaInitError> {
        create_dag(builder)
    }
}

// vpc subnet create saga: action implementations

async fn svsc_create_subnet(
    sagactx: NexusActionContext,
) -> Result<(authz::VpcSubnet, db::model::VpcSubnet), ActionError> {
    let osagactx = sagactx.user_data();
    let params = sagactx.saga_params::<Params>()?;
    let opctx = crate::context::op_context_for_saga_action(
        &sagactx,
        &params.serialized_authn,
    );
    let log = sagactx.user_data().log();

    let subnet_id = sagactx.lookup::<Uuid>("subnet_id")?;
    let vpc_id = params.authz_vpc.id();

    let num_retries = params.ipv6_blocks.len();
    let retryable = num_retries > 1;

    let mut result = None;
    for ipv6_block in params.ipv6_blocks {
        let subnet = db::model::VpcSubnet::new(
            subnet_id,
            vpc_id,
            params.subnet_create.identity.clone(),
            params.subnet_create.ipv4_block,
            ipv6_block,
        );

        result = Some(
            osagactx
                .datastore()
                .vpc_create_subnet(&opctx, &params.authz_vpc, subnet)
                .await,
        );

        if matches!(result, Some(Ok(_))) {
            break;
        }

        match &result {
            Some(Ok(_)) => break,
            // Allow NUM_RETRIES retries, after the first attempt.
            //
            // Note that we only catch IPv6 overlaps. The client
            // always specifies the IPv4 range, so we fail the
            // request if that overlaps with an existing range.
            Some(Err(InsertVpcSubnetError::OverlappingIpRange(IpNet::V6(
                _,
            )))) if retryable => debug!(
                log,
                "autogenerated random IPv6 range overlap";
                "subnet_id" => ?subnet_id,
                "ipv6_block" => %ipv6_block
            ),
            _ => {}
        }
    }

    (match result {
        None => Err(external::Error::internal_error(
            "Attempted to create VPC subnet without any IPv6 allocation",
        )),
        Some(Err(InsertVpcSubnetError::OverlappingIpRange(IpNet::V6(_))))
            if retryable =>
        {
            // TODO-monitoring TODO-debugging
            //
            // We should maintain a counter for this occurrence, and
            // export that via `oximeter`, so that we can see these
            // failures through the timeseries database. The main
            // goal here is for us to notice that this is happening
            // before it becomes a major issue for customers.
            error!(
                log,
                "failed to generate unique random IPv6 address \
                range in {} retries",
                num_retries;
                "vpc_id" => ?vpc_id,
                "subnet_id" => ?subnet_id,
            );
            Err(external::Error::internal_error(
                "Unable to allocate unique IPv6 address range \
                for VPC Subnet",
            ))
        }
        // Overlapping IPv4/explicit v6 range, which is a client error.
        Some(Err(e @ InsertVpcSubnetError::OverlappingIpRange(_))) => {
            Err(e.into_external())
        }
        Some(Err(InsertVpcSubnetError::External(e))) => Err(e),
        Some(Ok(v)) => Ok(v),
    })
    .map_err(ActionError::action_failed)
}

async fn svsc_create_subnet_undo(
    sagactx: NexusActionContext,
) -> Result<(), anyhow::Error> {
    let osagactx = sagactx.user_data();
    let params = sagactx.saga_params::<Params>()?;
    let opctx = crate::context::op_context_for_saga_action(
        &sagactx,
        &params.serialized_authn,
    );

    let (authz_subnet, db_subnet) =
        sagactx.lookup::<(authz::VpcSubnet, db::model::VpcSubnet)>("subnet")?;

    osagactx
        .datastore()
        .vpc_delete_subnet(&opctx, &db_subnet, &authz_subnet)
        .await?;
    Ok(())
}

async fn svsc_create_route(
    sagactx: NexusActionContext,
) -> Result<authz::RouterRoute, ActionError> {
    let osagactx = sagactx.user_data();
    let params = sagactx.saga_params::<Params>()?;
    let opctx = crate::context::op_context_for_saga_action(
        &sagactx,
        &params.serialized_authn,
    );

    let route_id = sagactx.lookup::<Uuid>("route_id")?;
    let (.., db_subnet) =
        sagactx.lookup::<(authz::VpcSubnet, db::model::VpcSubnet)>("subnet")?;

    osagactx
        .datastore()
        .vpc_create_subnet_route(
            &opctx,
            &params.authz_system_router,
            db_subnet,
            route_id,
        )
        .await
        .map_err(|e| ActionError::action_failed(e.into_external()))
        .map(|(auth, ..)| auth)
}

async fn svsc_create_route_undo(
    sagactx: NexusActionContext,
) -> Result<(), anyhow::Error> {
    let osagactx = sagactx.user_data();
    let params = sagactx.saga_params::<Params>()?;
    let opctx = crate::context::op_context_for_saga_action(
        &sagactx,
        &params.serialized_authn,
    );

    let authz_route = sagactx.lookup::<authz::RouterRoute>("route")?;

    osagactx.datastore().router_delete_route(&opctx, &authz_route).await?;

    Ok(())
}

async fn svsc_link_custom(
    sagactx: NexusActionContext,
) -> Result<db::model::VpcSubnet, ActionError> {
    let osagactx = sagactx.user_data();
    let params = sagactx.saga_params::<Params>()?;
    let opctx = crate::context::op_context_for_saga_action(
        &sagactx,
        &params.serialized_authn,
    );
    let (authz_subnet, db_subnet) =
        sagactx.lookup::<(authz::VpcSubnet, db::model::VpcSubnet)>("subnet")?;

    if let Some(custom_router) = params.custom_router {
        osagactx
            .datastore()
            .vpc_subnet_set_custom_router(&opctx, &authz_subnet, &custom_router)
            .await
            .map_err(ActionError::action_failed)
    } else {
        Ok(db_subnet)
    }
}

async fn svsc_link_custom_undo(
    sagactx: NexusActionContext,
) -> Result<(), anyhow::Error> {
    let osagactx = sagactx.user_data();
    let params = sagactx.saga_params::<Params>()?;
    let opctx = crate::context::op_context_for_saga_action(
        &sagactx,
        &params.serialized_authn,
    );
    let (authz_subnet, ..) =
        sagactx.lookup::<(authz::VpcSubnet, db::model::VpcSubnet)>("subnet")?;

    if params.custom_router.is_some() {
        osagactx
            .datastore()
            .vpc_subnet_unset_custom_router(&opctx, &authz_subnet)
            .await?;
    }

    Ok(())
}

async fn svsc_notify_rpw(
    sagactx: NexusActionContext,
) -> Result<(), ActionError> {
    let osagactx = sagactx.user_data();
    let params = sagactx.saga_params::<Params>()?;
    let opctx = crate::context::op_context_for_saga_action(
        &sagactx,
        &params.serialized_authn,
    );

    osagactx
        .datastore()
        .vpc_increment_rpw_version(&opctx, params.authz_vpc.id())
        .await
        .map_err(ActionError::action_failed)
}

#[cfg(test)]
pub(crate) mod test {
    use crate::{
        app::sagas::vpc_create::Params, app::sagas::vpc_create::SagaVpcCreate,
        external_api::params,
    };
    use async_bb8_diesel::AsyncRunQueryDsl;
    use diesel::{
        ExpressionMethods, OptionalExtension, QueryDsl, SelectableHelper,
    };
    use dropshot::test_util::ClientTestContext;
    use nexus_db_queries::db::fixed_data::vpc::SERVICES_INTERNET_GATEWAY_ID;
    use nexus_db_queries::{
        authn::saga::Serialized, authz, context::OpContext,
        db::datastore::DataStore, db::fixed_data::vpc::SERVICES_VPC_ID,
        db::lookup::LookupPath,
    };
    use nexus_test_utils::resource_helpers::create_default_ip_pool;
    use nexus_test_utils::resource_helpers::create_project;
    use nexus_test_utils_macros::nexus_test;
    use omicron_common::api::external::IdentityMetadataCreateParams;
    use omicron_common::api::external::Name;
    use omicron_common::api::external::NameOrId;
    use uuid::Uuid;

    type ControlPlaneTestContext =
        nexus_test_utils::ControlPlaneTestContext<crate::Server>;

    const PROJECT_NAME: &str = "springfield-squidport";

    async fn create_org_and_project(client: &ClientTestContext) -> Uuid {
        create_default_ip_pool(&client).await;
        let project = create_project(client, PROJECT_NAME).await;
        project.identity.id
    }

    // Helper for creating VPC create parameters
    fn new_test_params(
        opctx: &OpContext,
        authz_project: authz::Project,
    ) -> Params {
        Params {
            serialized_authn: Serialized::for_opctx(opctx),
            vpc_create: params::VpcCreate {
                identity: IdentityMetadataCreateParams {
                    name: "my-vpc".parse().unwrap(),
                    description: "My VPC".to_string(),
                },
                ipv6_prefix: None,
                dns_name: "abc".parse().unwrap(),
            },
            authz_project,
        }
    }

    fn test_opctx(cptestctx: &ControlPlaneTestContext) -> OpContext {
        OpContext::for_tests(
            cptestctx.logctx.log.new(o!()),
            cptestctx.server.server_context().nexus.datastore().clone(),
        )
    }

    async fn get_authz_project(
        cptestctx: &ControlPlaneTestContext,
        project_id: Uuid,
        action: authz::Action,
    ) -> authz::Project {
        let nexus = &cptestctx.server.server_context().nexus;
        let project_selector =
            params::ProjectSelector { project: NameOrId::Id(project_id) };
        let opctx = test_opctx(&cptestctx);
        let (.., authz_project) = nexus
            .project_lookup(&opctx, project_selector)
            .expect("Invalid parameters constructing project lookup")
            .lookup_for(action)
            .await
            .expect("Project does not exist");
        authz_project
    }

    async fn delete_project_vpc_defaults(
        cptestctx: &ControlPlaneTestContext,
        project_id: Uuid,
    ) {
        let opctx = test_opctx(&cptestctx);
        let datastore = cptestctx.server.server_context().nexus.datastore();
        let default_name = Name::try_from("default".to_string()).unwrap();
        let system_name = Name::try_from("system".to_string()).unwrap();

        // Default Subnet
        let (.., authz_subnet, subnet) = LookupPath::new(&opctx, &datastore)
            .project_id(project_id)
            .vpc_name(&default_name.clone().into())
            .vpc_subnet_name(&default_name.clone().into())
            .fetch()
            .await
            .expect("Failed to fetch default Subnet");
        datastore
            .vpc_delete_subnet(&opctx, &subnet, &authz_subnet)
            .await
            .expect("Failed to delete default Subnet");

        // Default gateway routes
        let (.., authz_route, _route) = LookupPath::new(&opctx, &datastore)
            .project_id(project_id)
            .vpc_name(&default_name.clone().into())
            .vpc_router_name(&system_name.clone().into())
            .router_route_name(&"default-v4".parse::<Name>().unwrap().into())
            .fetch()
            .await
            .expect("Failed to fetch default route");
        datastore
            .router_delete_route(&opctx, &authz_route)
            .await
            .expect("Failed to delete default route");

        let (.., authz_route, _route) = LookupPath::new(&opctx, &datastore)
            .project_id(project_id)
            .vpc_name(&default_name.clone().into())
            .vpc_router_name(&system_name.clone().into())
            .router_route_name(&"default-v6".parse::<Name>().unwrap().into())
            .fetch()
            .await
            .expect("Failed to fetch default route");
        datastore
            .router_delete_route(&opctx, &authz_route)
            .await
            .expect("Failed to delete default route");

        // System router
        let (.., authz_router, _router) = LookupPath::new(&opctx, &datastore)
            .project_id(project_id)
            .vpc_name(&default_name.clone().into())
            .vpc_router_name(&system_name.into())
            .fetch()
            .await
            .expect("Failed to fetch system router");
        datastore
            .vpc_delete_router(&opctx, &authz_router)
            .await
            .expect("Failed to delete system router");

        // Default gateway
        let (.., authz_vpc, authz_igw, _igw) =
            LookupPath::new(&opctx, &datastore)
                .project_id(project_id)
                .vpc_name(&default_name.clone().into())
                .internet_gateway_name(&default_name.clone().into())
                .fetch()
                .await
                .expect("Failed to fetch default gateway");
        datastore
            .vpc_delete_internet_gateway(
                &opctx,
                &authz_igw,
                authz_vpc.id(),
                true,
            )
            .await
            .expect("Failed to delete default gateway");

        // Default VPC & Firewall Rules
        let (.., authz_vpc, vpc) = LookupPath::new(&opctx, &datastore)
            .project_id(project_id)
            .vpc_name(&default_name.into())
            .fetch()
            .await
            .expect("Failed to fetch default VPC");
        datastore
            .vpc_delete_all_firewall_rules(&opctx, &authz_vpc)
            .await
            .expect("Failed to delete all firewall rules for VPC");
        datastore
            .project_delete_vpc(&opctx, &vpc, &authz_vpc)
            .await
            .expect("Failed to delete VPC");
    }

    pub(crate) async fn verify_clean_slate(datastore: &DataStore) {
        assert!(no_vpcs_exist(datastore).await);
        assert!(no_routers_exist(datastore).await);
        assert!(no_routes_exist(datastore).await);
        assert!(no_subnets_exist(datastore).await);
        assert!(no_gateways_exist(datastore).await);
        assert!(no_gateway_links_exist(datastore).await);
        assert!(no_firewall_rules_exist(datastore).await);
    }

    async fn no_vpcs_exist(datastore: &DataStore) -> bool {
        use nexus_db_queries::db::model::Vpc;
        use nexus_db_queries::db::schema::vpc::dsl;

        dsl::vpc
            .filter(dsl::time_deleted.is_null())
            // ignore built-in services VPC
            .filter(dsl::id.ne(*SERVICES_VPC_ID))
            .select(Vpc::as_select())
            .first_async::<Vpc>(
                &*datastore.pool_connection_for_tests().await.unwrap(),
            )
            .await
            .optional()
            .unwrap()
            .map(|vpc| {
                eprintln!("VPC exists: {vpc:?}");
            })
            .is_none()
    }

    async fn no_routers_exist(datastore: &DataStore) -> bool {
        use nexus_db_queries::db::model::VpcRouter;
        use nexus_db_queries::db::schema::vpc_router::dsl;

        dsl::vpc_router
            .filter(dsl::time_deleted.is_null())
            // ignore built-in services VPC
            .filter(dsl::vpc_id.ne(*SERVICES_VPC_ID))
            .select(VpcRouter::as_select())
            .first_async::<VpcRouter>(
                &*datastore.pool_connection_for_tests().await.unwrap(),
            )
            .await
            .optional()
            .unwrap()
            .map(|router| {
                eprintln!("Router exists: {router:?}");
            })
            .is_none()
    }

    async fn no_gateways_exist(datastore: &DataStore) -> bool {
        use nexus_db_queries::db::model::InternetGateway;
        use nexus_db_queries::db::schema::internet_gateway::dsl;

        dsl::internet_gateway
            .filter(dsl::time_deleted.is_null())
            // ignore built-in services VPC
            .filter(dsl::vpc_id.ne(*SERVICES_VPC_ID))
            .select(InternetGateway::as_select())
            .first_async::<InternetGateway>(
                &*datastore.pool_connection_for_tests().await.unwrap(),
            )
            .await
            .optional()
            .unwrap()
            .map(|igw| {
                eprintln!("Internet gateway exists: {igw:?}");
            })
            .is_none()
    }

    async fn no_gateway_links_exist(datastore: &DataStore) -> bool {
        use nexus_db_queries::db::model::InternetGatewayIpPool;
        use nexus_db_queries::db::schema::internet_gateway_ip_pool::dsl;

        dsl::internet_gateway_ip_pool
            .filter(dsl::time_deleted.is_null())
            .filter(dsl::internet_gateway_id.ne(*SERVICES_INTERNET_GATEWAY_ID))
            .select(InternetGatewayIpPool::as_select())
            .first_async::<InternetGatewayIpPool>(
                &*datastore.pool_connection_for_tests().await.unwrap(),
            )
            .await
            .optional()
            .unwrap()
            .map(|igw_ip_pool| {
                eprintln!(
                    "Internet gateway ip pool links exists: {igw_ip_pool:?}"
                );
            })
            .is_none()
    }

    async fn no_routes_exist(datastore: &DataStore) -> bool {
        use nexus_db_queries::db::model::RouterRoute;
        use nexus_db_queries::db::schema::router_route::dsl;
        use nexus_db_queries::db::schema::vpc_router::dsl as vpc_router_dsl;

        dsl::router_route
            .filter(dsl::time_deleted.is_null())
            // ignore built-in services VPC
            .filter(
                dsl::vpc_router_id.ne_all(
                    vpc_router_dsl::vpc_router
                        .select(vpc_router_dsl::id)
                        .filter(vpc_router_dsl::vpc_id.eq(*SERVICES_VPC_ID))
                        .filter(vpc_router_dsl::time_deleted.is_null()),
                ),
            )
            .select(RouterRoute::as_select())
            .first_async::<RouterRoute>(
                &*datastore.pool_connection_for_tests().await.unwrap(),
            )
            .await
            .optional()
            .unwrap()
            .map(|route| {
                eprintln!("Route exists: {route:?}");
            })
            .is_none()
    }

    async fn no_subnets_exist(datastore: &DataStore) -> bool {
        use nexus_db_queries::db::model::VpcSubnet;
        use nexus_db_queries::db::schema::vpc_subnet::dsl;

        dsl::vpc_subnet
            .filter(dsl::time_deleted.is_null())
            // ignore built-in services VPC
            .filter(dsl::vpc_id.ne(*SERVICES_VPC_ID))
            .select(VpcSubnet::as_select())
            .first_async::<VpcSubnet>(
                &*datastore.pool_connection_for_tests().await.unwrap(),
            )
            .await
            .optional()
            .unwrap()
            .map(|subnet| {
                eprintln!("Subnet exists: {subnet:?}");
            })
            .is_none()
    }

    async fn no_firewall_rules_exist(datastore: &DataStore) -> bool {
        use nexus_db_queries::db::model::VpcFirewallRule;
        use nexus_db_queries::db::schema::vpc_firewall_rule::dsl;

        dsl::vpc_firewall_rule
            .filter(dsl::time_deleted.is_null())
            // ignore built-in services VPC
            .filter(dsl::vpc_id.ne(*SERVICES_VPC_ID))
            .select(VpcFirewallRule::as_select())
            .first_async::<VpcFirewallRule>(
                &*datastore.pool_connection_for_tests().await.unwrap(),
            )
            .await
            .optional()
            .unwrap()
            .map(|rule| {
                eprintln!("Firewall rule exists: {rule:?}");
            })
            .is_none()
    }

    #[nexus_test(server = crate::Server)]
    async fn test_saga_basic_usage_succeeds(
        cptestctx: &ControlPlaneTestContext,
    ) {
        let client = &cptestctx.external_client;
        let nexus = &cptestctx.server.server_context().nexus;
        let project_id = create_org_and_project(&client).await;
        delete_project_vpc_defaults(&cptestctx, project_id).await;

        // Before running the test, confirm we have no records of any VPCs.
        verify_clean_slate(nexus.datastore()).await;

        // Build the saga DAG with the provided test parameters
        let opctx = test_opctx(&cptestctx);
        let authz_project = get_authz_project(
            &cptestctx,
            project_id,
            authz::Action::CreateChild,
        )
        .await;
        let params = new_test_params(&opctx, authz_project);
        nexus.sagas.saga_execute::<SagaVpcCreate>(params).await.unwrap();
    }

    #[nexus_test(server = crate::Server)]
    async fn test_action_failure_can_unwind(
        cptestctx: &ControlPlaneTestContext,
    ) {
        let log = &cptestctx.logctx.log;

        let client = &cptestctx.external_client;
        let nexus = &cptestctx.server.server_context().nexus;
        let project_id = create_org_and_project(&client).await;
        delete_project_vpc_defaults(&cptestctx, project_id).await;

        let opctx = test_opctx(&cptestctx);
        crate::app::sagas::test_helpers::action_failure_can_unwind::<
            SagaVpcCreate,
            _,
            _,
        >(
            nexus,
            || {
                Box::pin(async {
                    new_test_params(
                        &opctx,
                        get_authz_project(
                            &cptestctx,
                            project_id,
                            authz::Action::CreateChild,
                        )
                        .await,
                    )
                })
            },
            || {
                Box::pin(async {
                    verify_clean_slate(nexus.datastore()).await;
                })
            },
            log,
        )
        .await;
    }
}
