-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'multicast_group' AND index_name = 'lookup_external_multicast_by_ip')),'true','Schema change verification failed: index lookup_external_multicast_by_ip on table multicast_group does not exist') AS BOOL);
