-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'multicast_group_member' AND index_name = 'multicast_member_cleanup')),'true','Schema change verification failed: index multicast_member_cleanup on table multicast_group_member does not exist') AS BOOL);
