-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'affinity_group' AND index_name = 'lookup_affinity_group_by_project')),'true','Schema change verification failed: index lookup_affinity_group_by_project on table affinity_group does not exist') AS BOOL);
