-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'saga' AND index_name = 'lookup_saga_by_state')),'true','Schema change verification failed: index lookup_saga_by_state on table saga does not exist') AS BOOL);
