-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'hw_baseboard_id' AND index_name = 'lookup_baseboard_id_by_props')),'true','Schema change verification failed: index lookup_baseboard_id_by_props on table hw_baseboard_id does not exist') AS BOOL);
