-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'ip_pool_resource' AND index_name = 'one_default_ip_pool_per_resource')),'true','Schema change verification failed: index one_default_ip_pool_per_resource on table ip_pool_resource does not exist') AS BOOL);
