-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'ip_pool' AND column_name = 'pool_type')),'true','Schema change verification failed: column pool_type on table ip_pool does not exist (backfill may not have completed)') AS BOOL);
