-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'federation_session' AND index_name = 'federation_session_token')),'true','Schema change verification failed: index federation_session_token on table federation_session does not exist') AS BOOL);
