#!/bin/bash

echo "Disk space:"
df -h

if [ -d "/usr/share/dotnet" ]; then
  echo "Removing dotnet"
  sudo rm -rf /usr/share/dotnet
fi
if [ -d "/usr/local/lib/android" ]; then
  echo "Removing android"
  sudo rm -rf /usr/local/lib/android
fi
if [ -d "/opt/ghc" ]; then
  echo "Removing haskell"
  sudo rm -rf /opt/ghc
fi

echo "Disk space:"
df -h