#!/bin/bash
#
# This script fetches the following from CI
#
#   - the softnpu ASIC simulator (softnpu)
#   - a softnpu admin program (scadm)
#   - the sidecar-lite precompiled P4 program
#

set -euo pipefail

TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

OUT_DIR="out/npuzone"

# Pinned commit for softnpu ASIC simulator
SOFTNPU_REPO="softnpu"
SOFTNPU_COMMIT="41b3a67b3d44f51528816ff8e539b4001df48305"

# This is the softnpu ASIC simulator
echo "fetching npuzone"
mkdir -p $OUT_DIR
"$TOOLS_DIR"/ensure_buildomat_artifact.sh \
    -O $OUT_DIR \
    "npuzone" \
    "$SOFTNPU_REPO" \
    "$SOFTNPU_COMMIT"
chmod +x $OUT_DIR/npuzone
