#!/usr/bin/env bash

#
# ci_download_clickhouse: fetches the appropriate ClickHouse binary tarball
# based on the currently running operating system, unpacks it, and creates a
# copy called "clickhouse", all in the current directory.
#

set -o pipefail
set -o xtrace
set -o errexit

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ARG0="$(basename "${BASH_SOURCE[0]}")"

TARGET_DIR="out"
# Location where intermediate artifacts are downloaded / unpacked.
DOWNLOAD_DIR="$TARGET_DIR/downloads"
# Location where the final clickhouse directory should end up.
DEST_DIR="./$TARGET_DIR/clickhouse"

# If you change the version in clickhouse_version, you must also update the
# md5sums in clickhouse_checksums
CIDL_VERSION="$(cat "$SOURCE_DIR/clickhouse_version")"
source "$SOURCE_DIR/clickhouse_checksums"

# Download from manually-populated S3 bucket for now
CIDL_URL_BASE="https://oxide-clickhouse-build.s3.us-west-2.amazonaws.com"

function main
{
	#
	# Process command-line arguments. We generally don't expect any, but
	# we allow callers to specify a value to override OSTYPE, just for
	# testing.
	#
	if [[ $# != 0 ]]; then
		CIDL_OS="$1"
		shift
	else
		CIDL_OS="$OSTYPE"
	fi

	if [[ $# != 0 ]]; then
		echo "unexpected arguments" >&2
		exit 2
	fi

	# Configure this program
	configure_os "$CIDL_OS"
	CIDL_URL="$CIDL_URL_BASE/$TARBALL_FILENAME"

	# Download the file.
	echo "URL: $CIDL_URL"
	echo "Local file: $TARBALL_FILE"

	mkdir -p "$DOWNLOAD_DIR"
	mkdir -p "$DEST_DIR"

	local DO_DOWNLOAD="true"
	if [[ -f "$TARBALL_FILE" ]]; then
		# If the file exists with a valid checksum, we can skip downloading.
		calculated_md5="$($CIDL_MD5FUNC "$TARBALL_FILE")" || \
				fail "failed to calculate md5sum"
		if [[ "$calculated_md5" == "$CIDL_MD5" ]]; then
			DO_DOWNLOAD="false"
		fi
	fi

	if [ "$DO_DOWNLOAD" == "true" ]; then
		echo "Downloading..."
		do_download_curl "$CIDL_URL" "$TARBALL_FILE" || \
				fail "failed to download file"

		# Verify the md5sum.
		calculated_md5="$($CIDL_MD5FUNC "$TARBALL_FILE")" || \
				fail "failed to calculate md5sum"
		if [[ "$calculated_md5" != "$CIDL_MD5" ]]; then
			fail "md5sum mismatch \
					(expected $CIDL_MD5, found $calculated_md5)"
		fi
	fi

	# Unpack the tarball into a local directory
	do_untar "$TARBALL_FILE" "$DEST_DIR"

	# on macOS, we need to take the binary out of quarantine after download
	# https://github.com/ClickHouse/clickhouse-docs/blob/08d7a329d/knowledgebase/fix-developer-verification-error-in-macos.md
	if [[ $CIDL_OS == darwin* ]]; then
		xattr -d com.apple.quarantine "$DEST_DIR/clickhouse"
	fi

	# Run the binary as a sanity-check.
	"$DEST_DIR/clickhouse" server --version
}

function fail
{
	echo "$ARG0: $*" >&2
	exit 1
}

function configure_os
{
	echo "current directory: $PWD"
	echo "configuring based on OS: \"$1\""
	CIDL_DASHREV=
	case "$1" in
		darwin*)
			CIDL_PLATFORM="macos"
			CIDL_MD5="$CIDL_MD5_DARWIN"
			CIDL_MD5FUNC="do_md5"
			;;
		linux-gnu*)
			CIDL_PLATFORM="linux"
			CIDL_MD5="$CIDL_MD5_LINUX"
			CIDL_MD5FUNC="do_md5sum"
			;;
		solaris*)
			CIDL_PLATFORM="illumos"
			CIDL_MD5="$CIDL_MD5_ILLUMOS"
			CIDL_MD5FUNC="do_md5sum"
			;;
		*)
			fail "unsupported OS: $1"
			;;
	esac

	TARBALL_DIRNAME="clickhouse-$CIDL_VERSION"
	TARBALL_FILENAME="$TARBALL_DIRNAME$CIDL_DASHREV.$CIDL_PLATFORM.tar.gz"

	TARBALL_FILE="$DOWNLOAD_DIR/$TARBALL_FILENAME"
}

function do_download_curl
{
	curl --silent --show-error --fail --location --output "$2" "$1"
}

function do_md5
{
	md5 < "$1"
}

function do_md5sum
{
	md5sum < "$1" | awk '{print $1}'
}

function do_untar
{
	mkdir -p "$2" && tar xzf "$1" -C "$2"
}

main "$@"
