#!/bin/bash
#
# This script fetches the following from CI
#
#   - the softnpu ASIC simulator (softnpu)
#   - a softnpu admin program (scadm)
#   - the sidecar-lite precompiled P4 program
#

set -euo pipefail

TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

OUT_DIR="out/softnpu"

# Pinned commit for softnpu ASIC simulator
SOFTNPU_REPO="softnpu"
SOFTNPU_COMMIT="88f5f1334364e5580fe778c44ac0746a35927351"

# Pinned commit for softnpu tools
SIDECAR_LITE_REPO="sidecar-lite"
SIDECAR_LITE_COMMIT="56abef043a9e2ba0363fea82528d7a9e86d3c0b0"

# This is the softnpu ASIC simulator
echo "fetching softnpu"
mkdir -p out/softnpu
$TOOLS_DIR/ensure_buildomat_artifact.sh \
    -O $OUT_DIR \
    "softnpu" \
    "$SOFTNPU_REPO" \
    "$SOFTNPU_COMMIT"
chmod +x $OUT_DIR/softnpu

# This is an ASIC administration program.
echo "fetching scadm"
$TOOLS_DIR/ensure_buildomat_artifact.sh \
    -O $OUT_DIR \
    -s "release" \
    "scadm" \
    "$SIDECAR_LITE_REPO" \
    "$SIDECAR_LITE_COMMIT"
chmod +x $OUT_DIR/scadm

# Fetch the pre-compiled sidecar_lite p4 program
echo "fetching libsidecar_lite.so"
$TOOLS_DIR/ensure_buildomat_artifact.sh \
    -O $OUT_DIR \
    -s "release" \
    "libsidecar_lite.so" \
    "$SIDECAR_LITE_REPO" \
    "$SIDECAR_LITE_COMMIT"
