#!/usr/bin/env bash

echo -e "\e[0;33m$0 is deprecated; running: cargo xtask download transceiver-control\e[0m"
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 42
exec cargo xtask download transceiver-control
