#!/bin/bash

mkdir -p internal_specs

cargo run --bin=nexus -- omicron-nexus/examples/config.toml --openapi-internal > internal_specs/nexus.json

cargo run --bin=sled-agent -- open-api > internal_specs/sled-agent.json

cargo run --bin=bootstrap-agent -- open-api > internal_specs/bootstrap-agent.json

cargo run --bin=oximeter -- oximeter/oximeter/examples/config.toml --openapi > internal_specs/oximeter.json