-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'vmm' AND column_name = 'cpu_platform')),'true','Schema change verification failed: column cpu_platform on table vmm does not exist (backfill may not have completed)') AS BOOL);
