// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Tools for managing Dendrite during development

use std::net::{Ipv6Addr, SocketAddr, SocketAddrV6};
use std::process::Stdio;
use std::time::Duration;

use anyhow::Context;
use camino::{Utf8Path, Utf8PathBuf};
use camino_tempfile::Utf8TempDir;
use slog::Logger;
use tokio::{
    fs::File,
    io::{AsyncBufReadExt, BufReader},
    time::{Instant, sleep},
};

use crate::dev::tcp_proxy::{ProxyTarget, RetargetableTcpProxy};

/// Specifies the amount of time we will wait for `dpd` to launch,
/// which is currently confirmed by watching `dpd`'s log output
/// for a message specifying the address and port `dpd` is listening on.
pub const DENDRITE_TIMEOUT: Duration = Duration::new(30, 0);

/// State of a running Dendrite instance.
#[derive(Debug)]
struct RunningDendrite {
    /// Child process spawned by running `dpd`.
    child: tokio::process::Child,
    /// Temporary directory where logging output and other files generated by
    /// `dpd` are stored.
    data_dir: Utf8PathBuf,
}

impl RunningDendrite {
    async fn stop(mut self) -> Result<(), anyhow::Error> {
        self.child.start_kill().context("Sending SIGKILL to child")?;
        self.child.wait().await.context("waiting for child")?;
        std::fs::remove_dir_all(&self.data_dir).with_context(|| {
            format!("cleaning up temporary directory {}", self.data_dir)
        })?;
        Ok(())
    }
}

/// The state of dpd before `stop_dpd` or `restart_dpd` was called.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PriorDpdState {
    /// dpd was running and was stopped (before being restarted in case of
    /// `restart_dpd`).
    Running,
    /// dpd was already stopped (before being started in case of `restart_dpd`).
    Stopped,
}

/// Represents a running instance of the Dendrite dataplane daemon (dpd).
#[derive(Debug)]
pub struct DendriteInstance {
    /// Holds a TCP port bound for the lifetime of this instance, allowing for
    /// dpd to be killed and restarted behind the scenes without worrying about
    /// ephemeral port reuse.
    ///
    /// This is always `Some` for the lifetime of the `DendriteInstance`, and is
    /// only `None` inside methods that consume the instance.
    proxy: Option<RetargetableTcpProxy>,
    /// Some while dpd is running, otherwise None.
    running: Option<RunningDendrite>,
    /// The address of the Nexus control plane.
    ///
    /// dpd uses it to notify the control plane that it has started.
    nexus_address: Option<SocketAddr>,
    /// The MGS address.
    mgs_address: SocketAddr,
}

impl DendriteInstance {
    pub async fn start(
        nexus_address: Option<SocketAddr>,
        mgs_address: SocketAddr,
        log: &Logger,
    ) -> Result<Self, anyhow::Error> {
        let proxy = RetargetableTcpProxy::bind(
            ProxyTarget::Refuse,
            &log.new(o!("test_component" => "DendriteInstance")),
        )
        .await
        .context("binding TCP proxy in front of dpd")?;
        let mut instance = Self {
            proxy: Some(proxy),
            running: None,
            nexus_address,
            mgs_address,
        };
        instance.spawn_dpd().await?;
        Ok(instance)
    }

    /// The address clients should use to connect to dpd.
    ///
    /// This address stays bound whether dpd is running or not.
    pub fn address(&self) -> SocketAddrV6 {
        self.proxy().local_addr()
    }

    /// The port clients should use to connect to dpd.
    ///
    /// This port stays bound whether dpd is running or not.
    pub fn port(&self) -> u16 {
        // This is the proxy's port.
        self.proxy().port()
    }

    /// Returns true whether dpd is currently running.
    ///
    /// Note that [`Self::port`] stays valid either way.
    pub fn is_dpd_running(&self) -> bool {
        self.running.is_some()
    }

    /// Stop the underlying dpd server.
    ///
    /// Note that [`Self::port`] remains valid after this, since the port
    /// represents a TCP proxy.
    pub async fn stop_dpd(&mut self) -> Result<PriorDpdState, anyhow::Error> {
        // Make the proxy reject connections before killing dpd.
        self.proxy().set_target(ProxyTarget::Refuse).await;
        match self.running.take() {
            Some(running) => {
                running.stop().await?;
                Ok(PriorDpdState::Running)
            }
            None => Ok(PriorDpdState::Stopped),
        }
    }

    /// Stop dpd if it is running, and then start it again.
    ///
    /// [`Self::port`] continues to return the same port after this, since it
    /// represents a TCP proxy.
    pub async fn restart_dpd(
        &mut self,
    ) -> Result<PriorDpdState, anyhow::Error> {
        // If Dendrite is started before Nexus, the `nexus_address` isn't
        // available. A restarted dpd would come up healthy but not be able to
        // notify Nexus. Let's panic here, and revisit this if a test
        // legitimately needs that combination.
        assert!(
            self.nexus_address.is_some(),
            "restarted dpd should be able to notify Nexus, but no Nexus \
             address was recorded at start (was dendrite started before \
             Nexus?)"
        );
        let outcome = self.stop_dpd().await?;
        self.spawn_dpd().await?;
        Ok(outcome)
    }

    async fn spawn_dpd(&mut self) -> Result<(), anyhow::Error> {
        let temp_dir = Utf8TempDir::new()?;

        // We always bind dpd to a fresh ephemeral port and front it by a TCP
        // proxy to avoid port reuse races. See
        // https://github.com/oxidecomputer/omicron/issues/10697.
        let mut args = vec![
            "run".to_string(),
            "--listen-addresses".to_string(),
            "[::1]:0".to_string(),
            "--enable-rpw".to_string(),
        ];

        if let Some(socket_addr) = self.nexus_address {
            args.push("--nexus-address".to_string());
            args.push(socket_addr.to_string());
        }

        args.push("--mgs-address".to_string());
        args.push(self.mgs_address.to_string());

        let mut child = tokio::process::Command::new("dpd")
            .args(&args)
            .stdin(Stdio::null())
            .stdout(Stdio::from(redirect_file(
                temp_dir.path(),
                "dendrite_stdout",
            )?))
            .stderr(Stdio::piped())
            // If any of the below checks produce an error/early return, kill
            // the dpd process.
            .kill_on_drop(true)
            .spawn()
            .with_context(|| {
                format!("failed to spawn `dpd` (with args: {:?})", &args)
            })?;
        let stderr = child.stderr.take().unwrap();

        let temp_dir = temp_dir.keep();
        let dpd_port = discover_port(
            &mut child,
            stderr,
            temp_dir.join("dendrite_stdout"),
        )
        .await
        .with_context(|| {
            format!("failed to discover dendrite port from files in {temp_dir}")
        })?;

        let dpd_address =
            SocketAddrV6::new(Ipv6Addr::LOCALHOST, dpd_port, 0, 0);
        self.proxy().set_target(ProxyTarget::Forward(dpd_address.into())).await;

        // Print both the proxy and the backend address to stderr. This is
        // captured by nextest and kept in the run recording. See
        // https://github.com/oxidecomputer/omicron/issues/10697.
        let address = self.proxy().local_addr();
        eprintln!("Dendrite address: {address} (dpd backend: {dpd_address})");

        self.running = Some(RunningDendrite { child, data_dir: temp_dir });
        Ok(())
    }

    pub async fn cleanup(mut self) -> Result<(), anyhow::Error> {
        self.stop_dpd().await?;
        if let Some(proxy) = self.proxy.take() {
            proxy.shutdown().await;
        }
        Ok(())
    }

    fn proxy(&self) -> &RetargetableTcpProxy {
        self.proxy
            .as_ref()
            .expect("proxy is running across all non-consuming methods")
    }
}

impl Drop for DendriteInstance {
    fn drop(&mut self) {
        if let Some(running) = &mut self.running {
            eprintln!(
                "WARN: dropped DendriteInstance without cleaning it up first \
                (there may still be a child process running and a \
                temporary directory leaked)"
            );
            let _ = running.child.start_kill();
            eprintln!(
                "WARN: dendrite temporary directory leaked: {}",
                running.data_dir
            );
        }
    }
}

fn redirect_file(
    temp_dir_path: &Utf8Path,
    label: &str,
) -> Result<std::fs::File, anyhow::Error> {
    let out_path = temp_dir_path.join(label);
    std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&out_path)
        .with_context(|| format!("open \"{out_path}\""))
}

async fn discover_port(
    child: &mut tokio::process::Child,
    stderr: tokio::process::ChildStderr,
    logfile: Utf8PathBuf,
) -> Result<u16, anyhow::Error> {
    let timeout = Instant::now() + DENDRITE_TIMEOUT;
    tokio::time::timeout_at(
        timeout,
        find_dendrite_port_in_log(child, stderr, logfile),
    )
    .await
    .context("time out while discovering dendrite port number")?
}

async fn find_dendrite_port_in_log(
    child: &mut tokio::process::Child,
    mut stderr: tokio::process::ChildStderr,
    logfile: Utf8PathBuf,
) -> Result<u16, anyhow::Error> {
    let re = regex::Regex::new(r#""local_addr":"\[::1\]:([0-9]+)""#).unwrap();
    let mut reader = BufReader::new(File::open(&logfile).await?);
    let mut lines = reader.lines();
    loop {
        // Exit early if the process has exited.
        if let Some(exit_status) = child.try_wait()? {
            let mut stderr_contents = String::new();
            tokio::io::AsyncReadExt::read_to_string(
                &mut stderr,
                &mut stderr_contents,
            )
            .await?;

            anyhow::bail!(
                "dpd exited with status {} before port could be discovered: {}",
                exit_status,
                stderr_contents
            );
        }

        match lines.next_line().await? {
            Some(line) => {
                if let Some(cap) = re.captures(&line) {
                    // unwrap on get(1) should be ok, since captures() returns `None`
                    // if there are no matches found
                    let port = cap.get(1).unwrap();
                    let result = port.as_str().parse::<u16>()?;
                    return Ok(result);
                }
            }
            None => {
                sleep(Duration::from_millis(10)).await;

                // We might have gotten a partial line; close the file, reopen
                // it, and start reading again from the beginning.
                reader = BufReader::new(File::open(&logfile).await?);
                lines = reader.lines();
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::find_dendrite_port_in_log;
    use camino_tempfile::NamedUtf8TempFile;
    use std::io::Write;
    use std::process::Stdio;

    const EXPECTED_PORT: u16 = 12345;

    #[tokio::test]
    async fn test_dpd_in_path() {
        // With no arguments, we expect to see the default help message.
        tokio::process::Command::new("dpd")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("Cannot find 'dpd' on PATH. Refer to README.md for installation instructions");
    }

    #[tokio::test]
    async fn test_discover_local_listening_port() {
        // Write some data to a fake log file
        // This line is representative of the kind of output that dpd currently logs
        let line = r#"{"msg":"registered endpoint","v":0,"name":"dpd","level":20,"time":"2023-03-31T21:29:27.715517984Z","hostname":"workstation-1","pid":7480,"local_addr":"[::1]:12345","server_id":"0","unit":"api-server","path":"/all-settings","method":"DELETE"}"#;
        let mut file = NamedUtf8TempFile::new().unwrap();
        writeln!(file, "A garbage line").unwrap();
        writeln!(file, "{}", line).unwrap();
        writeln!(file, "Another garbage line").unwrap();
        file.flush().unwrap();

        let mut child = tokio::process::Command::new("yes")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::piped())
            .kill_on_drop(true)
            .spawn()
            .unwrap();
        let stderr = child.stderr.take().unwrap();

        assert_eq!(
            find_dendrite_port_in_log(
                &mut child,
                stderr,
                file.path().to_owned()
            )
            .await
            .unwrap(),
            EXPECTED_PORT
        );
    }
}
