// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Tools for managing Maghemite during development

use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use anyhow::Context;
use tempfile::TempDir;
use tokio::{
    fs::File,
    io::{AsyncBufReadExt, BufReader},
    time::{Instant, sleep},
};

/// Specifies the amount of time we will wait for `mgd` to launch,
/// which is currently confirmed by watching `mgd`'s log output
/// for a message specifying the address and port `mgd` is listening on.
pub const MGD_TIMEOUT: Duration = Duration::new(5, 0);

pub struct MgdInstance {
    /// Port number the mgd instance is listening on. This can be provided
    /// manually, or dynamically determined if a value of 0 is provided.
    pub port: u16,
    /// Arguments provided to the `mgd` cli command.
    pub args: Vec<String>,
    /// Child process spawned by running `mgd`
    pub child: Option<tokio::process::Child>,
    /// Temporary directory where logging output and other files generated by
    /// `mgd` are stored.
    pub data_dir: Option<PathBuf>,
}

impl MgdInstance {
    pub async fn start(mut port: u16) -> Result<Self, anyhow::Error> {
        let temp_dir = TempDir::new()?;

        let args = vec![
            "run".to_string(),
            "--admin-addr".into(),
            "::1".into(),
            "--admin-port".into(),
            port.to_string(),
            "--no-bgp-dispatcher".into(),
            "--data-dir".into(),
            temp_dir.path().display().to_string(),
            "--rack-uuid".into(),
            uuid::Uuid::new_v4().to_string(),
            "--sled-uuid".into(),
            uuid::Uuid::new_v4().to_string(),
        ];

        let child = tokio::process::Command::new("mgd")
            .args(&args)
            .stdin(Stdio::null())
            .stdout(Stdio::from(redirect_file(temp_dir.path(), "mgd_stdout")?))
            .stderr(Stdio::from(redirect_file(temp_dir.path(), "mgd_stderr")?))
            .spawn()
            .with_context(|| {
                format!("failed to spawn `mgd` (with args: {:?})", &args)
            })?;

        let child = Some(child);

        let temp_dir = temp_dir.keep();
        if port == 0 {
            port = discover_port(
                temp_dir.join("mgd_stdout").display().to_string(),
            )
            .await
            .with_context(|| {
                format!(
                    "failed to discover mgd port from files in {}",
                    temp_dir.display()
                )
            })?;
        }

        Ok(Self { port, args, child, data_dir: Some(temp_dir) })
    }

    pub async fn cleanup(&mut self) -> Result<(), anyhow::Error> {
        if let Some(mut child) = self.child.take() {
            child.start_kill().context("Sending SIGKILL to child")?;
            child.wait().await.context("waiting for child")?;
        }
        if let Some(dir) = self.data_dir.take() {
            std::fs::remove_dir_all(&dir).with_context(|| {
                format!("cleaning up temporary directory {}", dir.display())
            })?;
        }
        Ok(())
    }
}

impl Drop for MgdInstance {
    fn drop(&mut self) {
        if self.child.is_some() || self.data_dir.is_some() {
            eprintln!(
                "WARN: dropped MgdInstance without cleaning it up first \
                (there may still be a child process running and a \
                temporary directory leaked)"
            );
            if let Some(child) = self.child.as_mut() {
                let _ = child.start_kill();
            }
            if let Some(path) = self.data_dir.take() {
                eprintln!(
                    "WARN: mgd temporary directory leaked: {}",
                    path.display()
                );
            }
        }
    }
}

fn redirect_file(
    temp_dir_path: &Path,
    label: &str,
) -> Result<std::fs::File, anyhow::Error> {
    let out_path = temp_dir_path.join(label);
    std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&out_path)
        .with_context(|| format!("open \"{}\"", out_path.display()))
}

async fn discover_port(logfile: String) -> Result<u16, anyhow::Error> {
    let timeout = Instant::now() + MGD_TIMEOUT;
    tokio::time::timeout_at(timeout, find_mgd_port_in_log(logfile))
        .await
        .context("time out while discovering mgd port number")?
}

async fn find_mgd_port_in_log(logfile: String) -> Result<u16, anyhow::Error> {
    let re = regex::Regex::new(r#""local_addr":"\[::1?\]:([0-9]+)""#).unwrap();
    let mut reader = BufReader::new(File::open(&logfile).await?);
    let mut lines = reader.lines();
    loop {
        match lines.next_line().await? {
            Some(line) => {
                if let Some(cap) = re.captures(&line) {
                    // unwrap on get(1) should be ok, since captures() returns
                    // `None` if there are no matches found
                    let port = cap.get(1).unwrap();
                    let result = port.as_str().parse::<u16>()?;
                    return Ok(result);
                }
            }
            None => {
                sleep(Duration::from_millis(10)).await;

                // We might have gotten a partial line; close the file, reopen
                // it, and start reading again from the beginning.
                reader = BufReader::new(File::open(&logfile).await?);
                lines = reader.lines();
            }
        }
    }
}

/// Simulated DDM admin API instance for integration tests.
///
/// `ddmd` only runs on real switch zones (requires `libnet`,
/// `opte-ioctl`, and physical network interfaces), so it is not
/// available in the test toolchain like `mgd` is. This provides a
/// dropshot server implementing the DDM admin API endpoints that
/// omicron consumes, backed by in-memory state.
///
/// Peers can be provided at construction time and updated at runtime
/// via `set_peers`.
pub struct DdmInstance {
    pub port: u16,
    server: Option<dropshot::HttpServer<DdmSimContext>>,
}

/// Server-side peer info type for the DDM sim.
///
/// Mirrors the wire format of the progenitor-generated
/// `ddm_admin_client::types::PeerInfo` but derives `JsonSchema` so
/// dropshot can serve it directly.
#[derive(
    Clone, Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema,
)]
pub struct SimPeerInfo {
    pub addr: std::net::Ipv6Addr,
    pub host: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub if_name: Option<String>,
    pub kind: i64,
    pub status: SimPeerStatus,
}

#[derive(
    Clone,
    Debug,
    serde::Serialize,
    serde::Deserialize,
    schemars::JsonSchema,
    PartialEq,
)]
pub enum SimPeerStatus {
    NoContact,
    Active,
    Expired,
}

pub type PeerMap = std::collections::HashMap<String, SimPeerInfo>;

pub struct DdmSimContext {
    peers: std::sync::Mutex<PeerMap>,
}

/// Configuration for starting a `DdmInstance`.
pub struct DdmInstanceConfig {
    /// Initial peers to serve from `GET /peers`.
    pub initial_peers: PeerMap,
    /// Port to bind on (0 for auto-assign).
    pub port: u16,
    /// Logger for the dropshot server.
    pub log: slog::Logger,
}

impl Default for DdmInstanceConfig {
    fn default() -> Self {
        Self {
            initial_peers: PeerMap::new(),
            port: 0,
            log: slog::Logger::root(slog::Discard, slog::o!()),
        }
    }
}

impl DdmInstance {
    /// Start a DDM sim server with default configuration (no peers,
    /// auto-assigned port).
    pub async fn start() -> Result<Self, anyhow::Error> {
        Self::start_with_config(DdmInstanceConfig::default()).await
    }

    /// Start a DDM sim server with the provided configuration.
    pub async fn start_with_config(
        config: DdmInstanceConfig,
    ) -> Result<Self, anyhow::Error> {
        let context = DdmSimContext {
            peers: std::sync::Mutex::new(config.initial_peers),
        };

        let dropshot_config = dropshot::ConfigDropshot {
            bind_address: std::net::SocketAddr::V6(
                std::net::SocketAddrV6::new(
                    std::net::Ipv6Addr::LOCALHOST,
                    config.port,
                    0,
                    0,
                ),
            ),
            ..Default::default()
        };

        let mut api = dropshot::ApiDescription::new();
        api.register(ddm_get_peers).unwrap();

        let server = dropshot::HttpServerStarter::new(
            &dropshot_config,
            api,
            context,
            &config.log,
        )
        .map_err(|e| anyhow::anyhow!("failed to start DDM sim server: {e}"))?
        .start();

        let port = server.local_addr().port();
        Ok(Self { port, server: Some(server) })
    }

    /// Replace the peers returned by `GET /peers`.
    pub fn set_peers(&self, peers: PeerMap) {
        let server = self.server.as_ref().expect("DDM sim server not running");
        *server.app_private().peers.lock().unwrap() = peers;
    }

    pub async fn cleanup(&mut self) {
        if let Some(server) = self.server.take() {
            server.close().await.expect("failed to close DDM sim server");
        }
    }
}

/// Build a `SimPeerInfo` for a sled connected through the specified
/// switch port interface.
///
/// `host` identifies the peer in DDM (typically the sled hostname).
/// `if_name` is the switch port interface (e.g., `"tfportrear0_0"`).
/// `kind` is the DDM router kind (0 = server, 1 = transit).
pub fn sim_peer_info(
    addr: std::net::Ipv6Addr,
    host: &str,
    if_name: &str,
    kind: i64,
    status: SimPeerStatus,
) -> SimPeerInfo {
    SimPeerInfo {
        addr,
        host: host.to_string(),
        if_name: Some(if_name.to_string()),
        kind,
        status,
    }
}

#[dropshot::endpoint {
    method = GET,
    path = "/peers",
}]
async fn ddm_get_peers(
    rqctx: dropshot::RequestContext<DdmSimContext>,
) -> Result<dropshot::HttpResponseOk<PeerMap>, dropshot::HttpError> {
    let peers = rqctx.context().peers.lock().unwrap().clone();
    Ok(dropshot::HttpResponseOk(peers))
}

#[cfg(test)]
mod tests {
    use super::find_mgd_port_in_log;
    use std::io::Write;
    use std::process::Stdio;
    use tempfile::NamedTempFile;

    const EXPECTED_PORT: u16 = 4676;

    #[tokio::test]
    async fn test_mgd_in_path() {
        // With no arguments, we expect to see the default help message.
        tokio::process::Command::new("mgd")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("Cannot find 'mgd' on PATH. Refer to README.md for installation instructions");
    }

    #[tokio::test]
    async fn test_discover_local_listening_port() {
        // Write some data to a fake log file
        // This line is representative of the kind of output that mgd currently logs
        let line = r#"msg":"registered endpoint","v":0,"name":"slog-rs","level":20,"time":"2024-05-15T19:45:52.620737793-07:00","hostname":"masaka","pid":6854,"local_addr":"[::]:4676","unit":"api-server","path":"/bfd/peers","method":"GET"}"#;
        let mut file = NamedTempFile::new().unwrap();
        writeln!(file, "A garbage line").unwrap();
        writeln!(file, "{}", line).unwrap();
        writeln!(file, "Another garbage line").unwrap();
        file.flush().unwrap();

        assert_eq!(
            find_mgd_port_in_log(file.path().display().to_string())
                .await
                .unwrap(),
            EXPECTED_PORT
        );
    }
}
