// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Tools for managing Maghemite during development

use std::net::SocketAddr;
use std::process::Stdio;
use std::time::Duration;

use anyhow::Context;
use camino::{Utf8Path, Utf8PathBuf};
use camino_tempfile::Utf8TempDir;

/// How long to wait for a daemon to bind its admin port and write the port
/// file.
const PORT_FILE_TIMEOUT: Duration = Duration::from_secs(30);

pub struct MgdInstance {
    /// Port number the mgd instance is listening on, read back from the port
    /// file. Equals the requested port when non-zero, or the OS-assigned
    /// ephemeral port when 0 is requested.
    pub port: u16,
    /// Arguments provided to the `mgd` cli command.
    pub args: Vec<String>,
    /// Child process spawned by running `mgd`
    pub child: Option<tokio::process::Child>,
    /// Temporary directory where logging output and other files generated by
    /// `mgd` are stored.
    pub data_dir: Option<Utf8PathBuf>,
}

impl MgdInstance {
    pub async fn start(
        port: u16,
        mgs_addr: SocketAddr,
    ) -> Result<Self, anyhow::Error> {
        let temp_dir = Utf8TempDir::new()?;
        let port_file = temp_dir.path().join("mgd_port");

        let args = vec![
            "run".to_string(),
            "--admin-addr".into(),
            "::1".into(),
            "--admin-port".into(),
            port.to_string(),
            "--admin-port-file".into(),
            port_file.to_string(),
            "--no-bgp-dispatcher".into(),
            "--data-dir".into(),
            temp_dir.path().to_string(),
            "--rack-uuid".into(),
            uuid::Uuid::new_v4().to_string(),
            "--sled-uuid".into(),
            uuid::Uuid::new_v4().to_string(),
            "--mgs-addr".into(),
            mgs_addr.to_string(),
        ];

        let mut child = tokio::process::Command::new("mgd")
            .args(&args)
            .stdin(Stdio::null())
            .stdout(Stdio::from(redirect_file(temp_dir.path(), "mgd_stdout")?))
            .stderr(Stdio::from(redirect_file(temp_dir.path(), "mgd_stderr")?))
            .kill_on_drop(true)
            .spawn()
            .with_context(|| {
                format!("failed to spawn `mgd` (with args: {:?})", &args)
            })?;

        let temp_dir = temp_dir.keep();
        let port = read_port_file(&port_file, &mut child, PORT_FILE_TIMEOUT)
            .await
            .with_context(|| {
                format!(
                    "failed to discover mgd admin port \
                     (see {temp_dir}/mgd_stdout, mgd_stderr)"
                )
            })?;

        Ok(Self { port, args, child: Some(child), data_dir: Some(temp_dir) })
    }

    pub async fn cleanup(&mut self) -> Result<(), anyhow::Error> {
        if let Some(mut child) = self.child.take() {
            child.start_kill().context("Sending SIGKILL to child")?;
            child.wait().await.context("waiting for child")?;
        }
        if let Some(dir) = self.data_dir.take() {
            std::fs::remove_dir_all(&dir).with_context(|| {
                format!("cleaning up temporary directory {dir}")
            })?;
        }
        Ok(())
    }
}

impl Drop for MgdInstance {
    fn drop(&mut self) {
        if self.child.is_some() || self.data_dir.is_some() {
            eprintln!(
                "WARN: dropped MgdInstance without cleaning it up first \
                (there may still be a child process running and a \
                temporary directory leaked)"
            );
            if let Some(child) = self.child.as_mut() {
                let _ = child.start_kill();
            }
            if let Some(path) = self.data_dir.take() {
                eprintln!("WARN: mgd temporary directory leaked: {path}");
            }
        }
    }
}

fn redirect_file(
    temp_dir_path: &Utf8Path,
    label: &str,
) -> Result<std::fs::File, anyhow::Error> {
    let out_path = temp_dir_path.join(label);
    std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&out_path)
        .with_context(|| format!("open \"{out_path}\""))
}

async fn read_port_file(
    path: &Utf8Path,
    child: &mut tokio::process::Child,
    timeout: Duration,
) -> Result<u16, anyhow::Error> {
    let addr: SocketAddr = port_file::wait_for(
        path,
        || child.try_wait(),
        port_file::PollInterval(Duration::from_millis(25)),
        port_file::Timeout(timeout),
    )
    .await?;
    Ok(addr.port())
}

/// Test fixture that spawns and supervises a legit `ddmd` subprocess.
///
/// Owns a `tokio::process::Child` and a tempdir; discovers the bound admin port
/// through a port file; kills the child on `cleanup`/`Drop`. Mirrors
/// `MgdInstance`.
///
/// `ddmd` runs in sled global zones and switch zones in production. Spawned
/// here with `--api-only`, which serves only the admin API and skips the
/// discovery / exchange / routing daemons that need real network interfaces
/// and illumos-only kernel facilities. Only switch-zone instances
/// are registered in internal DNS as `ServiceName::Ddm`; sled-global-zone
/// instances are accessed locally by their own host (RSS, sled-agent's
/// prefix advertisement, etc.) and don't need DNS publication.
pub struct DdmInstance {
    /// Port number the ddmd instance is listening on.
    pub port: u16,
    /// Arguments provided to the `ddmd` cli command.
    pub args: Vec<String>,
    /// Child process spawned by running `ddmd`.
    pub child: Option<tokio::process::Child>,
    /// Temporary directory where logging output and other files generated by
    /// `ddmd` are stored.
    pub data_dir: Option<Utf8PathBuf>,
}

impl DdmInstance {
    pub async fn start() -> Result<Self, anyhow::Error> {
        let temp_dir = Utf8TempDir::new()?;
        let port_file = temp_dir.path().join("ddmd_port");

        let args = vec![
            "--admin-addr".to_string(),
            "::1".into(),
            "--admin-port".into(),
            "0".into(),
            "--admin-port-file".into(),
            port_file.to_string(),
            "--api-only".into(),
            "--data-dir".into(),
            temp_dir.path().to_string(),
        ];

        let mut child = tokio::process::Command::new("ddmd")
            .args(&args)
            .stdin(Stdio::null())
            .stdout(Stdio::from(redirect_file(temp_dir.path(), "ddmd_stdout")?))
            .stderr(Stdio::from(redirect_file(temp_dir.path(), "ddmd_stderr")?))
            .kill_on_drop(true)
            .spawn()
            .with_context(|| {
                format!("failed to spawn `ddmd` (with args: {:?})", &args)
            })?;

        let temp_dir = temp_dir.keep();

        let port = read_port_file(&port_file, &mut child, PORT_FILE_TIMEOUT)
            .await
            .with_context(|| {
                format!(
                    "failed to discover ddmd admin port \
                     (see {temp_dir}/ddmd_stdout, ddmd_stderr)"
                )
            })?;

        Ok(Self { port, args, child: Some(child), data_dir: Some(temp_dir) })
    }

    pub async fn cleanup(&mut self) -> Result<(), anyhow::Error> {
        if let Some(mut child) = self.child.take() {
            child.start_kill().context("Sending SIGKILL to child")?;
            child.wait().await.context("waiting for child")?;
        }
        if let Some(dir) = self.data_dir.take() {
            std::fs::remove_dir_all(&dir).with_context(|| {
                format!("cleaning up temporary directory {dir}")
            })?;
        }
        Ok(())
    }
}

impl Drop for DdmInstance {
    fn drop(&mut self) {
        if self.child.is_some() || self.data_dir.is_some() {
            eprintln!(
                "WARN: dropped DdmInstance without cleaning it up first \
                (there may still be a child process running and a \
                temporary directory leaked)"
            );
            if let Some(child) = self.child.as_mut() {
                let _ = child.start_kill();
            }
            if let Some(path) = self.data_dir.take() {
                eprintln!("WARN: ddmd temporary directory leaked: {path}");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::process::Stdio;

    #[tokio::test]
    async fn test_mgd_in_path() {
        // With no arguments, we expect to see the default help message.
        tokio::process::Command::new("mgd")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("Cannot find 'mgd' on PATH. Refer to README.md for installation instructions");
    }

    #[tokio::test]
    async fn test_ddmd_in_path() {
        // Run ddmd --help to exit cleanly instead of actually launching the
        // daemon. The latter would attempt to write to /var/run, get EACCES as
        // non-root, and abort.
        //
        // In this test, we only care about ddmd being present, not whether it
        // works.
        tokio::process::Command::new("ddmd")
            .arg("--help")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("Cannot find 'ddmd' on PATH. Refer to README.md for installation instructions");
    }
}
