// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Tools for managing Maghemite during development

use std::net::SocketAddr;
use std::process::Stdio;
use std::time::Duration;

use anyhow::Context;
use camino::{Utf8Path, Utf8PathBuf};
use camino_tempfile::Utf8TempDir;
use tokio::{
    fs::File,
    io::{AsyncBufReadExt, BufReader},
    time::{Instant, sleep},
};

/// Specifies the amount of time we will wait for `mgd` to launch,
/// which is currently confirmed by watching `mgd`'s log output
/// for a message specifying the address and port `mgd` is listening on.
pub const MGD_TIMEOUT: Duration = Duration::from_secs(30);

pub struct MgdInstance {
    /// Port number the mgd instance is listening on. This can be provided
    /// manually, or dynamically determined if a value of 0 is provided.
    pub port: u16,
    /// Arguments provided to the `mgd` cli command.
    pub args: Vec<String>,
    /// Child process spawned by running `mgd`
    pub child: Option<tokio::process::Child>,
    /// Temporary directory where logging output and other files generated by
    /// `mgd` are stored.
    pub data_dir: Option<Utf8PathBuf>,
}

impl MgdInstance {
    pub async fn start(
        mut port: u16,
        mgs_addr: SocketAddr,
    ) -> Result<Self, anyhow::Error> {
        let temp_dir = Utf8TempDir::new()?;

        let args = vec![
            "run".to_string(),
            "--admin-addr".into(),
            "::1".into(),
            "--admin-port".into(),
            port.to_string(),
            "--no-bgp-dispatcher".into(),
            "--data-dir".into(),
            temp_dir.path().to_string(),
            "--rack-uuid".into(),
            uuid::Uuid::new_v4().to_string(),
            "--sled-uuid".into(),
            uuid::Uuid::new_v4().to_string(),
            "--mgs-addr".into(),
            mgs_addr.to_string(),
        ];

        let child = tokio::process::Command::new("mgd")
            .args(&args)
            .stdin(Stdio::null())
            .stdout(Stdio::from(redirect_file(temp_dir.path(), "mgd_stdout")?))
            .stderr(Stdio::from(redirect_file(temp_dir.path(), "mgd_stderr")?))
            .spawn()
            .with_context(|| {
                format!("failed to spawn `mgd` (with args: {:?})", &args)
            })?;

        let child = Some(child);

        let temp_dir = temp_dir.keep();
        if port == 0 {
            port = discover_port(temp_dir.join("mgd_stdout"))
                .await
                .with_context(|| {
                    format!(
                        "failed to discover mgd port from files in {temp_dir}"
                    )
                })?;
        }

        Ok(Self { port, args, child, data_dir: Some(temp_dir) })
    }

    pub async fn cleanup(&mut self) -> Result<(), anyhow::Error> {
        if let Some(mut child) = self.child.take() {
            child.start_kill().context("Sending SIGKILL to child")?;
            child.wait().await.context("waiting for child")?;
        }
        if let Some(dir) = self.data_dir.take() {
            std::fs::remove_dir_all(&dir).with_context(|| {
                format!("cleaning up temporary directory {dir}")
            })?;
        }
        Ok(())
    }
}

impl Drop for MgdInstance {
    fn drop(&mut self) {
        if self.child.is_some() || self.data_dir.is_some() {
            eprintln!(
                "WARN: dropped MgdInstance without cleaning it up first \
                (there may still be a child process running and a \
                temporary directory leaked)"
            );
            if let Some(child) = self.child.as_mut() {
                let _ = child.start_kill();
            }
            if let Some(path) = self.data_dir.take() {
                eprintln!("WARN: mgd temporary directory leaked: {path}");
            }
        }
    }
}

fn redirect_file(
    temp_dir_path: &Utf8Path,
    label: &str,
) -> Result<std::fs::File, anyhow::Error> {
    let out_path = temp_dir_path.join(label);
    std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&out_path)
        .with_context(|| format!("open \"{out_path}\""))
}

/// Per-OS configuration for asking the kernel which TCP port a pid is
/// listening on.
struct PortProbe {
    /// Command to invoke (`pfiles` on illumos, `ss` on Linux).
    command: &'static str,
    /// Arguments to pass to `command`.
    args: Vec<String>,
    /// Substring that must appear on a line for it to belong to the target
    /// pid. `None` when the command is already pid-scoped (e.g. `pfiles
    /// <pid>`).
    pid_marker: Option<String>,
    /// Pattern that extracts the listening port into capture group 1.
    port_re: regex::Regex,
}

impl PortProbe {
    #[cfg(target_os = "illumos")]
    fn for_pid(pid: u32) -> Self {
        // `pfiles <pid>` lines look like:
        //   sockname: AF_INET6 ::1  port: 41065
        Self {
            command: "pfiles",
            args: vec![pid.to_string()],
            pid_marker: None,
            port_re: regex::Regex::new(
                r"sockname:\s+AF_INET6\s+::1?\s+port:\s+(\d+)",
            )
            .unwrap(),
        }
    }

    #[cfg(target_os = "linux")]
    fn for_pid(pid: u32) -> Self {
        // `ss -tlnpH` lines look like:
        //   LISTEN 0 128 [::1]:41065 [::]:* users:(("ddmd",pid=12345,fd=8))
        Self {
            command: "ss",
            args: vec!["-tlnpH".to_string()],
            pid_marker: Some(format!("pid={pid}")),
            port_re: regex::Regex::new(r"\[::1?\]:(\d+)").unwrap(),
        }
    }

    #[cfg(target_os = "macos")]
    fn for_pid(pid: u32) -> Self {
        // `lsof` is part of base macOS, so this compiles and runs without
        // any extra install. `lsof -nP -p <pid> -iTCP -sTCP:LISTEN` lines
        // look like:
        //   ddmd 12345 user 10u IPv6 0x... 0t0 TCP [::1]:41065 (LISTEN)
        Self {
            command: "lsof",
            args: vec![
                "-nP".to_string(),
                "-p".to_string(),
                pid.to_string(),
                "-iTCP".to_string(),
                "-sTCP:LISTEN".to_string(),
            ],
            pid_marker: None,
            port_re: regex::Regex::new(r"\[::1?\]:(\d+)").unwrap(),
        }
    }

    async fn probe(&self) -> Result<Option<u16>, anyhow::Error> {
        let output = tokio::process::Command::new(self.command)
            .args(&self.args)
            .output()
            .await
            .with_context(|| format!("running {}", self.command))?;
        if !output.status.success() {
            // The probe command can transiently fail (process exiting,
            // permissions, etc.); leave it to the caller to retry.
            return Ok(None);
        }
        let text = std::str::from_utf8(&output.stdout)
            .with_context(|| format!("{} output not utf8", self.command))?;
        Ok(text
            .lines()
            .filter(|line| {
                self.pid_marker.as_deref().is_none_or(|m| line.contains(m))
            })
            .find_map(|line| {
                self.port_re
                    .captures(line)?
                    .get(1)?
                    .as_str()
                    .parse::<u16>()
                    .ok()
            }))
    }
}

/// Ask the kernel which TCP port `pid` is listening on. Retries until either
/// the port is found or [`DDMD_TIMEOUT`] elapses, since `ddmd` may not have
/// finished binding when we first probe.
async fn find_listening_port(
    pid: u32,
    child: &mut tokio::process::Child,
) -> Result<u16, anyhow::Error> {
    let probe = PortProbe::for_pid(pid);
    let deadline = Instant::now() + DDMD_TIMEOUT;
    loop {
        if let Some(port) = probe.probe().await? {
            return Ok(port);
        }
        if let Some(status) =
            child.try_wait().context("polling ddmd process status")?
        {
            anyhow::bail!(
                "ddmd (pid {pid}) exited before binding a listening port \
                 (status: {status})"
            );
        }
        if Instant::now() >= deadline {
            anyhow::bail!(
                "kernel reports no listening TCP port for pid {pid} after \
                 {DDMD_TIMEOUT:?}"
            );
        }
        sleep(Duration::from_millis(100)).await;
    }
}

async fn discover_port(logfile: Utf8PathBuf) -> Result<u16, anyhow::Error> {
    let timeout = Instant::now() + MGD_TIMEOUT;
    tokio::time::timeout_at(timeout, find_mgd_port_in_log(logfile))
        .await
        .context("time out while discovering port number")?
}

async fn find_mgd_port_in_log(
    logfile: Utf8PathBuf,
) -> Result<u16, anyhow::Error> {
    let re = regex::Regex::new(r#""local_addr":"\[::1?\]:([0-9]+)""#).unwrap();
    let mut reader = BufReader::new(File::open(&logfile).await?);
    let mut lines = reader.lines();
    loop {
        match lines.next_line().await? {
            Some(line) => {
                if let Some(cap) = re.captures(&line) {
                    // unwrap on get(1) should be ok, since captures() returns
                    // `None` if there are no matches found
                    let port = cap.get(1).unwrap();
                    let result = port.as_str().parse::<u16>()?;
                    return Ok(result);
                }
            }
            None => {
                sleep(Duration::from_millis(10)).await;

                // We might have gotten a partial line; close the file, reopen
                // it, and start reading again from the beginning.
                reader = BufReader::new(File::open(&logfile).await?);
                lines = reader.lines();
            }
        }
    }
}

/// Specifies the amount of time we will wait for `ddmd` to bind its admin
/// port, confirmed by asking the kernel which TCP port `ddmd`'s pid is
/// listening on.
const DDMD_TIMEOUT: Duration = Duration::from_secs(30);

/// Test fixture that spawns and supervises a legit `ddmd` subprocess.
///
/// Owns a `tokio::process::Child` and a tempdir; discovers the bound admin
/// port by scraping dropshot's startup `local_addr` records; kills the child
/// on `cleanup`/`Drop`. Mirrors `MgdInstance`.
///
/// `ddmd` runs in sled global zones and switch zones in production. Spawned
/// here with `--api-only`, which serves only the admin API and skips the
/// discovery / exchange / routing daemons that need real network interfaces
/// and illumos-only kernel facilities. Only switch-zone instances
/// are registered in internal DNS as `ServiceName::Ddm`; sled-global-zone
/// instances are accessed locally by their own host (RSS, sled-agent's
/// prefix advertisement, etc.) and don't need DNS publication.
pub struct DdmInstance {
    /// Port number the ddmd instance is listening on.
    pub port: u16,
    /// Arguments provided to the `ddmd` cli command.
    pub args: Vec<String>,
    /// Child process spawned by running `ddmd`.
    pub child: Option<tokio::process::Child>,
    /// Temporary directory where logging output and other files generated by
    /// `ddmd` are stored.
    pub data_dir: Option<Utf8PathBuf>,
}

impl DdmInstance {
    /// Start a `ddmd` instance with `--api-only`, bound to an auto-assigned
    /// admin port on localhost.
    ///
    /// `MgdInstance` discovers its admin port by scraping `local_addr` from
    /// `mgd`'s startup logs. That approach does not work for `ddmd`: the
    /// dropshot endpoint-registration records that carry `local_addr` are
    /// emitted at debug level, and `ddmd`'s slog drain is currently focused
    /// on errors, so those lines never reach stdout.
    ///
    /// Instead, this fixture asks the kernel directly via `pfiles` (illumos),
    /// `ss` (Linux), or `lsof` (macOS), which reports the listening TCP port
    /// for `ddmd`'s pid regardless of what `ddmd` chose to log.
    ///
    /// Tracked upstream as oxidecomputer/maghemite#740. Once unified logging
    /// levels land, this fixture can revert to the simpler log-scrape pattern
    /// that `MgdInstance` uses.
    pub async fn start() -> Result<Self, anyhow::Error> {
        let temp_dir = Utf8TempDir::new()?;

        let args = vec![
            "--admin-addr".to_string(),
            "::1".into(),
            "--admin-port".into(),
            "0".into(),
            "--api-only".into(),
            "--data-dir".into(),
            temp_dir.path().to_string(),
        ];

        let mut child = tokio::process::Command::new("ddmd")
            .args(&args)
            .stdin(Stdio::null())
            .stdout(Stdio::from(redirect_file(temp_dir.path(), "ddmd_stdout")?))
            .stderr(Stdio::from(redirect_file(temp_dir.path(), "ddmd_stderr")?))
            .spawn()
            .with_context(|| {
                format!("failed to spawn `ddmd` (with args: {:?})", &args)
            })?;

        let pid =
            child.id().context("ddmd child has no pid (already exited?)")?;
        let temp_dir = temp_dir.keep();

        let port =
            find_listening_port(pid, &mut child).await.with_context(|| {
                format!(
                    "failed to discover ddmd listening port for pid {pid} \
                     (see {temp_dir}/ddmd_stdout, ddmd_stderr)"
                )
            })?;

        Ok(Self { port, args, child: Some(child), data_dir: Some(temp_dir) })
    }

    pub async fn cleanup(&mut self) -> Result<(), anyhow::Error> {
        if let Some(mut child) = self.child.take() {
            child.start_kill().context("Sending SIGKILL to child")?;
            child.wait().await.context("waiting for child")?;
        }
        if let Some(dir) = self.data_dir.take() {
            std::fs::remove_dir_all(&dir).with_context(|| {
                format!("cleaning up temporary directory {dir}")
            })?;
        }
        Ok(())
    }
}

impl Drop for DdmInstance {
    fn drop(&mut self) {
        if self.child.is_some() || self.data_dir.is_some() {
            eprintln!(
                "WARN: dropped DdmInstance without cleaning it up first \
                (there may still be a child process running and a \
                temporary directory leaked)"
            );
            if let Some(child) = self.child.as_mut() {
                let _ = child.start_kill();
            }
            if let Some(path) = self.data_dir.take() {
                eprintln!("WARN: ddmd temporary directory leaked: {path}");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::find_mgd_port_in_log;
    use camino_tempfile::NamedUtf8TempFile;
    use std::io::Write;
    use std::process::Stdio;

    const EXPECTED_PORT: u16 = 4676;

    #[tokio::test]
    async fn test_mgd_in_path() {
        // With no arguments, we expect to see the default help message.
        tokio::process::Command::new("mgd")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("Cannot find 'mgd' on PATH. Refer to README.md for installation instructions");
    }

    #[tokio::test]
    async fn test_ddmd_in_path() {
        tokio::process::Command::new("ddmd")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("Cannot find 'ddmd' on PATH. Refer to README.md for installation instructions");
    }

    #[tokio::test]
    async fn test_discover_local_listening_port() {
        // Write some data to a fake log file
        // This line is representative of the kind of output that mgd currently logs
        let line = r#"msg":"registered endpoint","v":0,"name":"slog-rs","level":20,"time":"2024-05-15T19:45:52.620737793-07:00","hostname":"masaka","pid":6854,"local_addr":"[::]:4676","unit":"api-server","path":"/bfd/peers","method":"GET"}"#;
        let mut file = NamedUtf8TempFile::new().unwrap();
        writeln!(file, "A garbage line").unwrap();
        writeln!(file, "{}", line).unwrap();
        writeln!(file, "Another garbage line").unwrap();
        file.flush().unwrap();

        assert_eq!(
            find_mgd_port_in_log(file.path().to_owned()).await.unwrap(),
            EXPECTED_PORT
        );
    }
}
