-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'support_bundle' AND index_name = 'lookup_bundle_by_nexus')),'true','Schema change verification failed: index lookup_bundle_by_nexus on table support_bundle does not exist') AS BOOL);
