format_version = 1

[target]
name = "zone"
description = "Metrics for a host zone"
authz_scope = "fleet"

versions = [
    { version = 1, fields = [ "rack_id", "sled_id", "sled_model", "sled_revision", "sled_serial" ] },
]

[fields.rack_id]
type = "uuid"
description = "ID for the rack"

[fields.sled_id]
type = "uuid"
description = "ID for the sled"

[fields.sled_model]
type = "string"
description = "Model number of the sled"

[fields.sled_revision]
type = "u32"
description = "Revision number of the sled"

[fields.sled_serial]
type = "string"
description = "Serial number of the sled"

[fields.zone_name]
type = "string"
description = "Name of the host zone"

[fields.zone_type]
type = "string"
description = "Service type of the zone (e.g. cockroachdb, nexus)"

[fields.zone_id]
type = "uuid"
description = "UUID of the zone"

[fields.state]
type = "string"
description = "The CPU state (user, sys, waitrq)"

[[metrics]]
name = "cpu_nsec"
description = "Cumulative CPU nanoseconds across all threads in a zone, by scheduling state"
units = "nanoseconds"
datum_type = "cumulative_u64"
versions = [
    { added_in = 1, fields = [ "zone_name", "zone_type", "zone_id", "state" ] }
]
