:showtitle:
:toc: left
:icons: font

= Running Omicron (Non-Simulated)

Omicron is the control plane for an Oxide rack. It expects to execute
on Helios systems, and Sleds use Helios-specific interfaces to manage
resources.

If you're interested in running the control plane on other platforms, including
Linux and Mac, refer to the guide on xref:how-to-run-simulated.adoc[running
simulated Omicron].

== Installing Prerequisite Software

A major prerequisite is to have a machine already running Helios. An easy way to
do this is by using a https://github.com/oxidecomputer/helios-engvm[Helios VM].
ISOs are also available for download https://pkg.oxide.computer/install[here].

Any additional prerequisite software may be installed with the following script:

[source,text]
----
$ ./tools/install_prerequisites.sh
----

=== Make me a Gimlet!

The sled agent expects to manage a real Gimlet. However, until those are built,
developers generally make do with something else, usually a commodity machine.
To make your machine "look" like a Gimlet, the
`./tools/create_virtual_hardware.sh` script can be used. This creates a few
file-based ZFS vdevs and ZFS zpools on top of those, and a couple of VNICs. The
vdevs model the actual U.2s that will be in a Gimlet, and the VNICs model the
two Chelsio NIC ports.

You can clean up these resources with `./tools/destroy_virtual_hardware.sh`. Be
aware that this is a best effort script. If the sled agent or other Omicron
zones are still running, the zpools cannot be deleted. The script will warn you
about the things it cannot remove, so you can do so yourself. Also note that all
the networking bits are temporary, so a reboot should always clear them.

Both scripts must be run as root, e.g, `pfexec ./tools/create_virtual_hardware.sh`.

== Deploying Omicron

The control plane repository contains a packaging tool which bundles binaries
and SMF manifests. After building the expected binaries, they can be packaged
in a format which lets them be transferred to a Helios machine.

This tool acts on a `package-manifest.toml` file which describes the packages to be
bundled in the build.

Configuration files are used to select IP addresses, and to manage Zpools
utilized by the Sled Agent. These configuration files are located within
`smf/`, and likely need to be modified to use addresses and zpools which match
your hardware. Much of this configuration will be automated in the future
(e.g., IP addresses will be inferred and posted to a DNS system, Zpools will
automatically be detected on discovered disks), but for now it remains
hard-coded.

[source,text]
----
$ cargo run --release --bin omicron-package -- package
----

NOTE: Running in `release` mode isn't strictly required, but improves
the performance of the packaging tools significantly.

The aforementioned package command fills a target directory of choice
(by default, `out/` within the omicron repository) with tarballs ready
to be unpacked as services.

To install the services on a target machine, the following command
may be executed:

[source,text]
----
$ pfexec cargo run --release --bin omicron-package -- install
----

This service installs a bootstrap service, which itself loads other
requested services. The bootstrap service is currently the only
service which is "persistent" across reboots - although it will
initialize other service as part of its setup sequence anyway.

[source,text]
----
# List all services:
$ svcs
# View zones managed by Omicron (prefixed with "oxz_"):
$ zoneadm list -cv
# View logs for a service:
$ pfexec tail -f $(pfexec svcs -z oxz_nexus -L nexus)
----

To uninstall all Omicron services from a machine, the following may be
executed:

[source,text]
----
$ pfexec cargo run --release --bin omicron-package -- uninstall
----

=== Test Environment

When we deploy, we're effectively creating a number of different zones
for all the components that make up Omicron (Nexus, Clickhouse, Crucible, etc).
Since all these services run in different zones they cannot communicate with
each other (and Sled Agent in the global zone) via `localhost`. In practice,
we'll assign addresses as per RFD 63 as well as incorporating DNS based
service discovery.

For the purposes of local development today, we specify some hardcoded IPv6
unique local addresses in `fd00:1de::/16`:

[options="header"]
|===================================================================================================
| Service                    | Endpoint                                                             
| Sled Agent: Bootstrap      | `[::]:12346`                                                         
| Sled Agent: Dropshot API   | `[fd00:1de::]:12345`                                                 
| Cockroach DB               | `[fd00:1de::5]:32221`                                                
| Oximeter                   | `[fd00:1de::6]:12223`                                                
| Nexus: External API        | `[fd00:1de::7]:12220`                                                
| Nexus: Internal API        | `[fd00:1de::7]:12221`                                                
| Clickhouse                 | `[fd00:1de::8]:8123`                                                 
| Crucible Downstairs        | `[fd00:1de::9]:32345`, `[fd00:1de::10]:32345`, `[fd00:1de::11]:32345`
|===================================================================================================

Note that Sled Agent runs in the global zone and is the one responsible for bringing up all the other
other services and allocating them with vNICs and IPv6 addresses.
