:showtitle:
:toc: left

= The TUF Artifact and Deployment Unit Compendium

This document describes all artifact and deployment unit kinds in a TUF
repository, the file formats of each kind as expected by the control
plane, and references to where the artifacts/units are generated and
consumed.

https://rfd.shared.oxide.computer/rfd/557[RFD 557] describes our
terminology in more detail, but the quick summary is:

* An *artifacts* is a file in a TUF repository. Artifacts can either
  be *single-unit*, meaning they are a deployment unit, or *composite*,
  meaning they are a tarball consisting of deployment units.
* A *deployment unit* is a unit of system software that is deployed and
  updated separately. Deployment units are not further subdivided by the
  update system.

It is strongly recommended that future artifacts are single-unit.
Nexus supports registering artifacts of kinds it does not know about,
under the assumption that a future Nexus might know what to do with it.
This only works if Nexus does not need foreknowledge of how to extract
deployment units from a composite artifact.

== `control_plane`

Composite artifact; consists of one or more `zone`s.

The first file in the tarball is `oxide.json` with the contents:
....
{"v":"1","t":"control_plane"}
....

Zones are stored as gzip-compressed tarballs under the directory
`zones/` with the file extension `.tar.gz`.

`control_plane` is generated by tufaceous-lib (see
<<CompositeControlPlaneArchiveBuilder>>).

In Nexus-driven update, update-common splits the composite artifact
using tufaceous-lib's <<ControlPlaneZoneImages::extract>>; see
<<UpdatePlanBuilder::extract_control_plane_zones>>. The name and
version of the deployment unit are read from the zone's `oxide.json`;
the name and version of the `control_plane` composite artifact is
ignored.

In MUPdate, update-common leaves the composite artifact as-is and makes
it available to Installinator, which fetches the composite tarball
via the underlay network and extracts the zones into memory using
tufaceous-lib's <<ControlPlaneZoneImages::extract>>. The zones are
then written to the install datasets using the original filenames as
found in the composite artifact.

Note that the file name and the `name` field of oxide.json do
not necessarily match. Currently, the internal DNS zone is named
`zones/internal_dns.tar.gz` in the tarball but is named `internal-dns`
according to its `oxide.json`; the tarball name is derived from the
`service_name` field in `package-manifset.toml`, while the `name` field
is derived from the key in the `package` table.

In the future we may do away with the `control_plane` composite artifact
and include `zone` units as separate artifacts in the TUF repo.

=== `zone`

Deployment unit; a zone image using the <<omicron1(7)>> zone brand.

Per the Image Archives section of <<omicron1(7)>>, the first file in the
image is `oxide.json` with the contents:
....
{"v":"1","t":"layer"}
....

<<omicron-package>> has extended this format via its `stamp` subcommand
(called by <<omicron-releng>>), which adds the top-level `pkg` and
`version` fields; for example:
....
{"v":"1","t":"layer","pkg":"internal-dns","version":"13.0.0-0.ci+gite491b783874"}
....

Zone images are generated via <<omicron-package>> and consumed by the
host OS. The `oxide.json` file is used to identify the name and version
of the deployment unit when the TUF repository is consumed by Nexus; see
<<UpdatePlanBuilder::extract_control_plane_zones>>.

== `gimlet_sp`, `psc_sp`, `switch_sp`

Single-unit artifact; the Hubris archive for a Service Processor.

The artifact's name must match the board name in the caboose, otherwise
the artifact is ignored.

Hubris archives are generated by the Hubris xtask; see
<<dist::build_archive>>. These archives are sent as-is to MGS when
updating the SP.

== `gimlet_rot`, `psc_rot`, `switch_rot`

Composite artifact; consists of Hubris archives for slots A and B of the
Root of Trust.

The first file in the tarball is `oxide.json` with the contents:
....
{"v":"1","t":"rot"}
....

This is followed by the slot A Hubris archive at `archive-a.zip`, then
the slot B Hubris archive at `archive-b.zip`.

RoT images have the same board type across our hardware. The name of the
artifact is used solely as a key to differentiate RoT images signed with
different sets of keys.

The composite archive format is managed by tufaceous-lib; it is
generated by <<CompositeRotArchiveBuilder>> and extracted by
<<RotArchives::extract>>.

=== `gimlet_rot_image_a`, `psc_rot_image_a`, `switch_rot_image_a`

The Root of Trust slot A Hubris archive.

Hubris archives are generated by the Hubris xtask; see
<<dist::build_archive>>. These archives are sent as-is to MGS when
updating the RoT.

=== `gimlet_rot_image_b`, `psc_rot_image_b`, `switch_rot_image_b`

The Root of Trust slot B Hubris archive.

Hubris archives are generated by the Hubris xtask; see
<<dist::build_archive>>. These archives are sent as-is to MGS when
updating the RoT.

== `gimlet_rot_bootloader`, `psc_rot_bootloader`, `switch_rot_bootloader`

Single-unit artifact; the Hubris archive for the Root of Trust
bootloader, https://github.com/oxidecomputer/bootleby[Bootleby].

== `host`, `trampoline`

Composite artifact; the gzip-compressed tarball generated by
<<helios-build>>'s `experiment-image` subcommand.

The `host` OS image is used during normal operation. The `trampoline`
image, generally called the "recovery" image outside of TUF repos,
contains just enough of a system to run Installinator which installs the
host OS image and control plane artifacts via the underlay network.

The first file in the tarball is `oxide.json` with contents similar to:
....
{"v":"1","t":"os","i":{"checksum":"6c5916f113b26a62bf5a7ec3ebf85801db314e4bbb5a80979304195b01ae030c","name":"ci e491b78/f6f918a 2025-02-19 18:12"}}
....

The phase 1 OS image is stored at `image/rom`, and the phase 2 OS image
is stored at `image/zfs.img`. The tarball contains a number of other
files relevant to the image's provenance which are not used by the
control plane.

The `checksum` from `oxide.json` refers to the checksum of the phase 2
zpool, which starts at offset 4096 in `image/zfs.img`. This checksum is
also contained in the phase 1 OS image, which verifies the checksum in
the phase 2 header matches before booting it.

=== `host_phase_1`, `trampoline_phase_1`

The phase 1 OS image is 32 MiB and written to the flash ROM of the
compute sled. It is generated by <<amd-host-image-builder>>.

=== `host_phase_2`, `trampoline_phase_2`

The phase 2 OS image is generated by `mkimage` from
<<boot-image-tools>>; the image consists of a 4 KiB header (see
<<bootserver::diskimage>>) and is followed by a zpool generated using
<<illumos/image-builder>>. It is copied as-is to the first partition of
the M.2 drive.

[bibliography]
== References

* [[[amd-host-image-builder]]] https://github.com/oxidecomputer/amd-host-image-builder
* [[[boot-image-tools]]] https://github.com/oxidecomputer/boot-image-tools
* [[[bootserver::diskimage]]] https://github.com/oxidecomputer/boot-image-tools/blob/main/src/diskimage.rs
* [[[CompositeControlPlaneArchiveBuilder]]] https://github.com/search?q=repo%3Aoxidecomputer%2Ftufaceous+symbol%3ACompositeControlPlaneArchiveBuilder&type=code
* [[[CompositeRotArchiveBuilder]]] https://github.com/search?q=repo%3Aoxidecomputer%2Ftufaceous+symbol%3ACompositeRotArchiveBuilder&type=code
* [[[ControlPlaneZoneImages::extract]]] https://github.com/search?q=repo%3Aoxidecomputer%2Ftufaceous+symbol%3AControlPlaneZoneImages%3A%3Aextract&type=code
* [[[dist::build_archive]]] https://github.com/search?q=repo%3Aoxidecomputer%2Fhubris+path%3Axtask+symbol%3Abuild_archive&type=code
* [[[helios-build]]] https://github.com/oxidecomputer/helios/tree/master/tools/helios-build
* [[[illumos/image-builder]]] https://github.com/illumos/image-builder
* [[[illumos/image-builder]]] https://github.com/illumos/image-builder
* [[[omicron-package]]] https://github.com/oxidecomputer/omicron/tree/main/package
* [[[omicron-releng]]] https://github.com/oxidecomputer/omicron/blob/main/docs/releng.adoc
* [[[omicron1(7)]]] https://github.com/oxidecomputer/helios-omicron-brand
* [[[RotArchives::extract]]] https://github.com/search?q=repo%3Aoxidecomputer%2Ftufaceous%20symbol%3ARotArchives%3A%3Aextract&type=code
* [[[UpdatePlanBuilder::extract_control_plane_zones]]] https://github.com/search?q=repo%3Aoxidecomputer%2Fomicron+symbol%3AUpdatePlanBuilder%3A%3Aextract_control_plane_zones&type=code
