-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT 1 FROM [SHOW CONSTRAINTS FROM audit_log] WHERE constraint_name = 'actor_kind_and_id_consistent' AND validated = true)),'true','Schema change verification failed: constraint actor_kind_and_id_consistent not found on table audit_log') AS BOOL);
