-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'rack' AND index_name = 'rack_initialized')),'true','Schema change verification failed: index rack_initialized on table rack does not exist') AS BOOL);
