-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'address_lot' AND index_name = 'address_lot_names')),'true','Schema change verification failed: index address_lot_names on table address_lot does not exist') AS BOOL);
