# To run this check locally, install SkyWalking Eyes
# (https://github.com/apache/skywalking-eyes). On macOS you can `brew install
# license-eye` and run `license-eye header check` or `license-eye header fix`.

name: license-check

on:
  push:
    branches: [main]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # see omicron#4461
      - name: Check License Header
        uses: apache/skywalking-eyes/header@e9f91c35e4d4ae4420f722aa6598c4a13cc69093 # v0.8.0
